name = "RealRooted"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["RealRooted"]
packagesDir = "/lake-cache/ai-projects/packages"
buildDir = "/lake-cache/ai-projects/build/RealRooted"

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
weak.linter.style.header = false
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
git = "https://github.com/YaelDillies/mathlib4.git"
rev = "e2e81af06ad0d26773192ed7dc95ad4c837a81d6"

[[lean_lib]]
name = "RealRooted"
