name = "SuperEulerian"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["SuperEulerian"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
weak.linter.style.header = false
maxSynthPendingDepth = 3

[[require]]
name = "RealRooted"
path = ".."

[[lean_lib]]
name = "SuperEulerian"
