import RealRooted.CombinatorialExamples.BigDescents321.Certificate.Data
import RealRooted.CombinatorialExamples.BigDescents321.KernelSum

/-!
# The universal kernel certificate

The neighbouring-coefficient inequality of issue #1143 reduces to the positivity of
`∑_(k ≤ R) W_k P(R, X, k)`, where `W_k = W_(R,k)(X)` are the kernel weights and

`P = 4A L₁ F(R-1, X+2, k) - 8A L₂ F(R-2, X+2, k) - B F(R, X, k) + 2B L₃ F(R-1, X, k)`.

The certificate is a polynomial `p₀(R, X, k)` with `89` integer terms and a positive integer
`L`. With `g(k) = k p₀(R, X, k) / (L d_g(k))` and `ρ(k) = W_(k+1)/W_k`,

`P - ρ(k) g(k + 1) + g(k) = H̃(R, X, k) / (2 L d(k))`,

and `27720 R¹² H̃(R, X, k) = P₊(R - 7, X, k, R - k)` for a polynomial `P₊` with
natural-number coefficients. Hence `H̃ ≥ 0` for `R ≥ 7`, `X ≥ 0`, `0 ≤ k ≤ R`, and `H̃ > 0` at
`k = 0`; the sum telescopes because `g(0) = 0` and `ρ(R) = 0`.

The certificate data and the kernel checks are in `Certificate/Data.lean`, generated by
`scripts/gen_big_descents_certificate.py`.

## Main statements

* `bernH_nonneg`, `bernH_pos_zero`: the signs of `H̃`.
* `bernP_eq`: the telescoping identity.
-/

namespace RealRooted.BigDescents321

open Reflect CertData

section Generic

variable {α : Type*} [CommRing α]

/-- The certificate numerator `p₀(R, X, k)`. -/
def bernP0 (R X k : α) : α := termsFn p0Data R X k

/-- The numerator `N = dP`, an integer polynomial of total degree `10`. -/
def bernN (R X k : α) : α :=
  (X + 3) * (2 * X + 7) * (R - k) * (R + 2 * X + k + 2) * (R + 2 * X + k + 3) *
      (R + 2 * X + k + 4) * (R + k - 3) * (R + 2 * X + k + 1) * certF (R - 1) (X + 2) k
    - 2 * ((X + 3) * (2 * X + 7)) * (R - k) * (R - k - 1) * (R + 2 * X + k + 2) *
      (R + 2 * X + k + 3) * (R + X + k + 2) * (R + 2 * X + k + 1) * certF (R - 2) (X + 2) k
    - (X + 2) * (2 * X + 3) * certF R X k * ((R + k - 3) * (R + k - 2) * (2 * X + 2 * k + 5) *
      (2 * X + 2 * k + 7) * (R + X + k + 2) * (R + 2 * X + k + 1))
    + 2 * ((X + 2) * (2 * X + 3)) * (R - k) * (R + X + k + 1) * (R + k - 3) *
      (2 * X + 2 * k + 5) * (2 * X + 2 * k + 7) * (R + X + k + 2) * certF (R - 1) X k

/-- The polynomial `H̃(R, X, k)`. -/
def bernH (R X k : α) : α :=
  2 * (lden : α) * bernN R X k -
      (R - k) * (R + k - 3) * (R + 2 * X + k + 1) * bernP0 R X (k + 1) +
    2 * k * (2 * X + 2 * k + 7) * (R + X + k + 2) * bernP0 R X k

/-- The polynomial `P₊(S, X, K, T)`, with natural-number coefficients. -/
noncomputable def bernPlus (S X K T : α) : α := pplusE.denote (ctx4 S X K T)

private theorem denote_htildeE (R X k : α) : htildeE.denote (ctx3 R X k) = bernH R X k := by
  simp only [htildeE, nE, aE, bE, fE, lin, List.foldr_cons, List.foldr_nil, denote_add,
    denote_sub, denote_mul, denote_num, denote_var, denote_termsExpr, ctx3_zero, ctx3_one,
    ctx3_two, bernH, bernN, certF, bernP0]
  push_cast
  ring

private theorem ctx4_get_eq (R X k : α) (i : ℕ) :
    (ctx4 (R - 7) X k (R - k)).get i = (σ i).denote (ctx3 R X k) := by
  rw [ctx4_get]
  rcases i with _ | _ | _ | i <;> simp [σ]

/-- The certificate identity `27720 R¹² H̃(R, X, k) = P₊(R - 7, X, k, R - k)`. -/
theorem bernH_eq_bernPlus (R X k : α) :
    27720 * R ^ 12 * bernH R X k = bernPlus (R - 7) X k (R - k) := by
  have hA := check_sound (ctx3 R X k) htilde_check
  rw [denote_htildeE, denote_termsExpr] at hA
  simp only [htData, termsFn_append, denote_var, ctx3_zero, ctx3_one, ctx3_two] at hA
  have e := fun {l r : Lean.Grind.CommRing.Expr} (h : check l (subst σ r) = true) ↦
    (check_sound (ctx3 R X k) h).trans
      (denote_subst (ctx3 R X k) (ctx4 (R - 7) X k (R - k)) σ (ctx4_get_eq R X k) r)
  have h0 := e chunk_check_0
  have h1 := e chunk_check_1
  have h2 := e chunk_check_2
  have h3 := e chunk_check_3
  have h4 := e chunk_check_4
  have h5 := e chunk_check_5
  have h6 := e chunk_check_6
  simp only [denote_mul, denote_pow, denote_num, denote_var, denote_termsExpr, denote_add,
    ctx3_zero, ctx3_one, ctx3_two] at h0 h1 h2 h3 h4 h5 h6
  simp only [bernPlus, pplusE, prestE, denote_add]
  rw [hA]
  push_cast at h0 h1 h2 h3 h4 h5 h6 ⊢
  linear_combination h0 + h1 + h2 + h3 + h4 + h5 + h6

end Generic

section Positivity

variable {α : Type*} [CommRing α] [LinearOrder α] [IsStrictOrderedRing α]

theorem bernPlus_nonneg {S X K T : α} (hS : 0 ≤ S) (hX : 0 ≤ X) (hK : 0 ≤ K) (hT : 0 ≤ T) :
    0 ≤ bernPlus S X K T := by
  have hctx := ctx4_nonneg hS hX hK hT
  simp only [bernPlus, pplusE, denote_add]
  exact add_nonneg (denote_nonneg _ hctx _ (by decide +kernel)) (denote_nonneg _ hctx _ prest_posB)

theorem bernPlus_pos {S X K T : α} (hS : 0 ≤ S) (hX : 0 ≤ X) (hK : 0 ≤ K) (hT : 0 < T) :
    0 < bernPlus S X K T := by
  have hctx := ctx4_nonneg hS hX hK hT.le
  have hT' : (ctx4 S X K T).get 3 = T := by rw [ctx4_get]; simp
  simp only [bernPlus, pplusE, denote_add, pTop, denote_mul, denote_num, denote_pow, denote_var,
    hT']
  exact add_pos_of_pos_of_nonneg (mul_pos (by norm_num) (pow_pos hT 12))
    (denote_nonneg _ hctx _ prest_posB)

theorem bernH_nonneg {R X k : α} (hR : 7 ≤ R) (hX : 0 ≤ X) (hk : 0 ≤ k) (hkR : k ≤ R) :
    0 ≤ bernH R X k := by
  have hR' : (0 : α) < 27720 * R ^ 12 := by
    have : (0 : α) < R := by linarith
    positivity
  have hP := bernPlus_nonneg (sub_nonneg.2 hR) hX hk (sub_nonneg.2 hkR)
  rw [← bernH_eq_bernPlus] at hP
  exact (mul_nonneg_iff_of_pos_left hR').mp hP

theorem bernH_pos_zero {R X : α} (hR : 7 ≤ R) (hX : 0 ≤ X) : 0 < bernH R X 0 := by
  have hR0 : (0 : α) < R := by linarith
  have hR' : (0 : α) < 27720 * R ^ 12 := by positivity
  have hP := bernPlus_pos (sub_nonneg.2 hR) hX le_rfl (by simpa using hR0)
  have hc := bernH_eq_bernPlus R X 0
  rw [sub_zero] at hc
  rw [← hc] at hP
  exact (mul_pos_iff_of_pos_left hR').mp hP

end Positivity

/-! ### The telescoping identity -/

/-- `L₁ = W_(R-1,k)(X+2) / W_(R,k)(X)`. -/
def bernL1 (R X k : ℚ) : ℚ :=
  (R - k) * (R + 2 * X + k + 2) * (R + 2 * X + k + 3) * (R + 2 * X + k + 4) /
    (4 * (R + k - 2) * (2 * X + 2 * k + 5) * (2 * X + 2 * k + 7) * (R + X + k + 2))

/-- `L₂ = W_(R-2,k)(X+2) / W_(R,k)(X)`. -/
def bernL2 (R X k : ℚ) : ℚ :=
  (R - k) * (R - k - 1) * (R + 2 * X + k + 2) * (R + 2 * X + k + 3) /
    (4 * (R + k - 3) * (R + k - 2) * (2 * X + 2 * k + 5) * (2 * X + 2 * k + 7))

/-- `L₃ = W_(R-1,k)(X) / W_(R,k)(X)`. -/
def bernL3 (R X k : ℚ) : ℚ := (R - k) * (R + X + k + 1) / ((R + k - 2) * (R + 2 * X + k + 1))

/-- The summand `P(R, X, k)`, divided by the weight `W_(R,k)(X)`. -/
def bernP (R X k : ℚ) : ℚ :=
  4 * ((X + 3) * (2 * X + 7)) * bernL1 R X k * certF (R - 1) (X + 2) k
    - 8 * ((X + 3) * (2 * X + 7)) * bernL2 R X k * certF (R - 2) (X + 2) k
    - (X + 2) * (2 * X + 3) * certF R X k
    + 2 * ((X + 2) * (2 * X + 3)) * bernL3 R X k * certF (R - 1) X k

/-- The common denominator `d(R, X, k)`. -/
def bernD (R X k : ℚ) : ℚ :=
  (R + k - 3) * (R + k - 2) * (2 * X + 2 * k + 5) * (2 * X + 2 * k + 7) * (R + X + k + 2) *
    (R + 2 * X + k + 1)

/-- The telescoping function `g(k) = k p₀(R, X, k) / (L d_g(k))`. -/
def bernG (R X k : ℚ) : ℚ :=
  k * bernP0 R X k / ((lden : ℚ) * ((R + k - 3) * (R + k - 2) * (2 * X + 2 * k + 5) *
    (R + 2 * X + k + 1)))

theorem bernD_pos {R X k : ℚ} (hR : 7 ≤ R) (hX : 0 ≤ X) (hk : 0 ≤ k) : 0 < bernD R X k := by
  unfold bernD
  have : 0 < R + k - 3 := by linarith
  have : 0 < R + k - 2 := by linarith
  positivity

theorem lden_pos : (0 : ℚ) < lden := by norm_num [lden]

/-- `N = dP`. -/
theorem bernD_mul_bernP {R X k : ℚ} (hR : 7 ≤ R) (hX : 0 ≤ X) (hk : 0 ≤ k) :
    bernD R X k * bernP R X k = bernN R X k := by
  have h1 : R + k - 2 ≠ 0 := by linarith
  have h2 : R + k - 3 ≠ 0 := by linarith
  have h3 : 2 * X + 2 * k + 5 ≠ 0 := by linarith
  have h4 : 2 * X + 2 * k + 7 ≠ 0 := by linarith
  have h5 : R + X + k + 2 ≠ 0 := by linarith
  have h6 : R + 2 * X + k + 1 ≠ 0 := by linarith
  unfold bernD bernP bernN bernL1 bernL2 bernL3
  generalize certF (R - 1) (X + 2) k = F1
  generalize certF (R - 2) (X + 2) k = F2
  generalize certF R X k = F3
  generalize certF (R - 1) X k = F4
  field_simp
  ring

/-- The telescoping identity `P = H̃ / (2 L d) + ρ(k) g(k + 1) - g(k)`, where
`ρ(k) = W_(R,k+1)(X) / W_(R,k)(X)` is `certBq (R - 1) X k`. -/
theorem bernP_eq {R X k : ℚ} (hR : 7 ≤ R) (hX : 0 ≤ X) (hk : 0 ≤ k) :
    bernP R X k = bernH R X k / (2 * lden * bernD R X k) +
      certBq (R - 1) X k * bernG R X (k + 1) - bernG R X k := by
  have hd := (bernD_pos hR hX hk).ne'
  have hL := lden_pos.ne'
  have h1 : R + k - 2 ≠ 0 := by linarith
  have h2 : R + k - 3 ≠ 0 := by linarith
  have h3 : 2 * X + 2 * k + 5 ≠ 0 := by linarith
  have h4 : 2 * X + 2 * k + 7 ≠ 0 := by linarith
  have h5 : R + X + k + 2 ≠ 0 := by linarith
  have h6 : R + 2 * X + k + 1 ≠ 0 := by linarith
  have h7 : R + k - 1 ≠ 0 := by linarith
  have h8 : R + 2 * X + k + 2 ≠ 0 := by linarith
  have h9 : k + 1 ≠ 0 := by linarith
  have h10 : 2 * X + 2 * k + 4 ≠ 0 := by linarith
  have hP : bernP R X k = bernN R X k / bernD R X k := by
    rw [eq_div_iff hd, mul_comm]
    exact bernD_mul_bernP hR hX hk
  have hg0 : bernG R X k = 2 * k * (2 * X + 2 * k + 7) * (R + X + k + 2) * bernP0 R X k /
      (2 * lden * bernD R X k) := by
    unfold bernG bernD
    rw [div_eq_div_iff (by simp [*]) (by simp [*])]
    ring
  have hg1 : certBq (R - 1) X k * bernG R X (k + 1) = (R - k) * (R + k - 3) *
      (R + 2 * X + k + 1) * bernP0 R X (k + 1) / (2 * lden * bernD R X k) := by
    unfold certBq bernG bernD
    have e1 : R + (k + 1) - 3 = R + k - 2 := by ring
    have e2 : R + (k + 1) - 2 = R + k - 1 := by ring
    have e3 : 2 * X + 2 * (k + 1) + 5 = 2 * X + 2 * k + 7 := by ring
    have e4 : R + 2 * X + (k + 1) + 1 = R + 2 * X + k + 2 := by ring
    have e5 : X + k + (R - 1) + 3 = R + X + k + 2 := by ring
    rw [e1, e2, e3, e4, e5]
    field_simp
    ring
  rw [hP, hg0, hg1]
  unfold bernH
  field_simp
  ring

end RealRooted.BigDescents321
