/-
Copyright (c) 2026 Per Alexandersson. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Per Alexandersson
-/
import RealRooted.GammaPencil.Invariants
import RealRooted.GammaPencil.Preserver
import RealRooted.Interlacing.NegativeRoots
import RealRooted.ProductOrientation

/-!
# The all-rank gamma-pencil theorem

The degree-box preserver transports the full real pencil generated by the two
gamma components.  Their constant coefficients and nonnegative coefficients
then select the orientation `Prec (gammaU n) (gammaV n)`.
-/

open Polynomial

noncomputable section

namespace RealRooted

/-- Every real linear combination of the two gamma components splits. -/
theorem gammaUV_allComboRealRooted_add_two (n : ℕ) :
    AllComboRealRooted (gammaU (n + 2)) (gammaV (n + 2)) := by
  induction n with
  | zero =>
      intro a b
      apply Polynomial.Splits.of_natDegree_le_one
      simpa [gammaU, gammaV] using
        (Polynomial.natDegree_C_mul_le b X).trans (by simp)
  | succ n ih =>
      change AllComboRealRooted
        (gammaOperator (n + 2) (gammaU (n + 2)))
        (gammaOperator (n + 2) (gammaV (n + 2)))
      exact gammaOperator_allComboRealRooted (by lia)
        (gammaU_natDegree_le_add_two n)
        (gammaV_natDegree_le_add_two n) ih

/-- Every real linear combination of the rank-`n` gamma components splits. -/
theorem gammaUV_allComboRealRooted (n : ℕ) (hn : 2 ≤ n) :
    AllComboRealRooted (gammaU n) (gammaV n) := by
  rw [← Nat.sub_add_cancel hn]
  exact gammaUV_allComboRealRooted_add_two (n - 2)

private theorem gammaU_coeff_zero (n : ℕ) (hn : 2 ≤ n) :
    (gammaU n).coeff 0 = 1 := by
  rw [← Nat.sub_add_cancel hn]
  exact gammaU_constantCoeff_add_two (n - 2)

private theorem gammaV_coeff_zero (n : ℕ) (hn : 2 ≤ n) :
    (gammaV n).coeff 0 = 0 := by
  rw [← Nat.sub_add_cancel hn]
  exact gammaV_constantCoeff_add_two (n - 2)

private theorem gammaU_roots_neg (n : ℕ) (hn : 2 ≤ n) :
    ∀ r, (gammaU n).IsRoot r → r < 0 := by
  intro r hr
  have hrmem : r ∈ (gammaU n).roots :=
    (Polynomial.mem_roots (gammaU_ne_zero n hn)).mpr hr
  have hrle : r ≤ 0 :=
    roots_nonpos_of_hasNonnegCoeffs (gammaU_hasNonnegCoeffs n hn) r hrmem
  have hrne : r ≠ 0 := by
    intro hrzero
    subst r
    have heval : (gammaU n).eval 0 = 0 := hr
    rw [← Polynomial.coeff_zero_eq_eval_zero, gammaU_coeff_zero n hn] at heval
    norm_num at heval
  exact lt_of_le_of_ne hrle hrne

/-- The gamma components occur in the directed proper position selected by
the zero root of `gammaV n` and the nonzero constant term of `gammaU n`. -/
theorem gammaU_prec_gammaV (n : ℕ) (hn : 2 ≤ n) :
    Prec (gammaU n) (gammaV n) := by
  have hall := gammaUV_allComboRealRooted n hn
  have hUne := gammaU_ne_zero n hn
  have hVne := gammaV_ne_zero n hn
  have hUsplits := hall.left_splits
  have hVsplits := hall.right_splits
  have hUnn := gammaU_hasNonnegCoeffs n hn
  have hVnn := gammaV_hasNonnegCoeffs n hn
  have hUzero := gammaU_coeff_zero n hn
  have hVzero := gammaV_coeff_zero n hn
  have hVroot : (gammaV n).IsRoot 0 := by
    rw [Polynomial.IsRoot.def, ← Polynomial.coeff_zero_eq_eval_zero]
    exact hVzero
  rcases natDegree_eq_or_succ_or_revSucc_of_allComboRealRooted
      hall hUne hVne with hsame | hsucc | hrevsucc
  · apply prec_of_allComboRealRooted_of_sameDegree_of_nonneg_of_eval_cross_gt
      hUne hVne hUnn hVnn hall hsame
    have hVpos := hasPosLeadingCoeff_of_nonnegCoeffs_of_ne_zero hVnn hVne
    rw [← Polynomial.coeff_zero_eq_eval_zero,
      ← Polynomial.coeff_zero_eq_eval_zero, hUzero, hVzero]
    simpa only [zero_mul, one_mul, HasPosLeadingCoeff] using hVpos
  · rcases prec_of_allComboRealRooted hUne hUsplits hVne hVsplits hall
        (Or.inl hsucc) with hprec | hreverse
    · exact hprec
    · exact (not_prec_of_right_natDegree_lt_left (by lia) hreverse).elim
  · have hreverse : Prec (gammaV n) (gammaU n) := by
      rcases prec_of_allComboRealRooted hVne hVsplits hUne hUsplits
          (allComboRealRooted_comm hall) (Or.inl hrevsucc) with hprec | hprec
      · exact hprec
      · exact (not_prec_of_right_natDegree_lt_left (by lia) hprec).elim
    have hVneg : ∀ r, (gammaV n).IsRoot r → r < 0 :=
      roots_neg_of_interlaces_of_right_roots_neg
        (hreverse.toInterlaces hrevsucc) (gammaU_roots_neg n hn)
    exact ((lt_irrefl 0) (hVneg 0 hVroot)).elim

/-- Every displayed affine gamma-pencil member is nonzero. -/
theorem gammaU_add_C_mul_gammaV_ne_zero (a : ℝ) (n : ℕ) (hn : 2 ≤ n) :
    gammaU n + C a * gammaV n ≠ 0 := by
  simpa [gammaPencil, Polynomial.smul_eq_C_mul] using
    gammaPencil_ne_zero a n hn

/-- Every displayed affine gamma-pencil member splits over the reals. -/
theorem gammaU_add_C_mul_gammaV_splits (a : ℝ) (n : ℕ) (hn : 2 ≤ n) :
    (gammaU n + C a * gammaV n).Splits := by
  simpa using gammaUV_allComboRealRooted n hn 1 a

end RealRooted
