/-
Generated by scripts/gen_big_descents_small_cases.py; do not edit by hand.
-/
import RealRooted.CombinatorialExamples.BigDescents321.SmallCases.Literals
import RealRooted.Basic.PolynomialFacts
import RealRooted.Bezoutian.Successor
import RealRooted.Tactic.InterlacesExplicit

/-!
# Finite interlacing certificates for the small big-descent polynomials

For `3 ≤ n ≤ 24`, `M_(n-2)` interlaces `A_n`, by the exact Euclid chain of
`rr_interlaces_explicit`. An integer Bezout identity `U A_n + V M_(n-2) = D`, checked as an
integer-list computation, shows that the two polynomials have no common root, so both have
simple roots.
-/

open Polynomial

namespace RealRooted.BigDescents321.SmallCases

/-- Interlacing together with a Bezout identity `U * A + V * M = D`, `D ≠ 0`, gives simple
roots of both polynomials and no common root. -/
theorem nodup_of_interlaces_of_bezout {A M U V : ℝ[X]} {D : ℝ} (hI : Interlaces M A)
    (hB : U * A + V * M = C D) (hD' : D ≠ 0) :
    A.roots.Nodup ∧ M.roots.Nodup ∧ ∀ x, M.IsRoot x → ¬ A.IsRoot x := by
  have hcop : IsCoprime M A :=
    ⟨C D⁻¹ * V, C D⁻¹ * U, by
      rw [mul_assoc, mul_assoc, ← mul_add, add_comm, hB, ← C_mul, inv_mul_cancel₀ hD', C_1]⟩
  have hdisj : ∀ x, A.IsRoot x → ¬ M.IsRoot x := fun x hA hM ↦ hcop.not_isRoot_right hM hA
  exact ⟨(hI.roots_nodup_of_disjoint hdisj).1, (hI.roots_nodup_of_disjoint hdisj).2,
    fun x hM hA ↦ hdisj x hA hM⟩

private theorem interlaces_3 :
    Interlaces (motzkinRef 1 : ℝ[X]) (bigDescentPoly 3) := by
  rw [motzkinRef_one, bigDescentPoly_three]
  rr_interlaces_explicit

private theorem bezout_3 :
    ofList [0] * (bigDescentPoly 3 : ℝ[X])
      + ofList [1] * motzkinRef 1
      = C (2 : ℝ) := by
  rw [motzkinRef_1, bigDescentPoly_3, ← ofList_mulList, ← ofList_mulList,
    ← ofList_addList]
  trans ofList (2 :: List.replicate 1 0)
  · exact congrArg ofList (by decide +kernel)
  · rw [ofList_cons_replicate_zero]
    norm_cast

theorem interlaces_and_nodup_3 :
    Interlaces (motzkinRef 1 : ℝ[X]) (bigDescentPoly 3) ∧
      (bigDescentPoly 3 : ℝ[X]).roots.Nodup ∧ (motzkinRef 1 : ℝ[X]).roots.Nodup ∧
      ∀ x, (motzkinRef 1 : ℝ[X]).IsRoot x → ¬ (bigDescentPoly 3 : ℝ[X]).IsRoot x :=
  ⟨interlaces_3, nodup_of_interlaces_of_bezout interlaces_3 bezout_3 (by norm_num)⟩

private theorem interlaces_4 :
    Interlaces (motzkinRef 2 : ℝ[X]) (bigDescentPoly 4) := by
  rw [motzkinRef_2, bigDescentPoly_4]
  simp only [ofList_cons, ofList_nil, Int.cast_ofNat, Int.cast_one, map_ofNat, map_one, mul_zero,
    add_zero, mul_one]
  rr_interlaces_explicit

private theorem bezout_4 :
    ofList [-1] * (bigDescentPoly 4 : ℝ[X])
      + ofList [4, 1] * motzkinRef 2
      = C (11 : ℝ) := by
  rw [motzkinRef_2, bigDescentPoly_4, ← ofList_mulList, ← ofList_mulList,
    ← ofList_addList]
  trans ofList (11 :: List.replicate 2 0)
  · exact congrArg ofList (by decide +kernel)
  · rw [ofList_cons_replicate_zero]
    norm_cast

theorem interlaces_and_nodup_4 :
    Interlaces (motzkinRef 2 : ℝ[X]) (bigDescentPoly 4) ∧
      (bigDescentPoly 4 : ℝ[X]).roots.Nodup ∧ (motzkinRef 2 : ℝ[X]).roots.Nodup ∧
      ∀ x, (motzkinRef 2 : ℝ[X]).IsRoot x → ¬ (bigDescentPoly 4 : ℝ[X]).IsRoot x :=
  ⟨interlaces_4, nodup_of_interlaces_of_bezout interlaces_4 bezout_4 (by norm_num)⟩

private theorem interlaces_5 :
    Interlaces (motzkinRef 3 : ℝ[X]) (bigDescentPoly 5) := by
  rw [motzkinRef_3, bigDescentPoly_5]
  simp only [ofList_cons, ofList_nil, Int.cast_ofNat, map_ofNat, mul_zero, add_zero]
  rr_interlaces_explicit

private theorem bezout_5 :
    ofList [-9] * (bigDescentPoly 5 : ℝ[X])
      + ofList [23, 12] * motzkinRef 3
      = C (112 : ℝ) := by
  rw [motzkinRef_3, bigDescentPoly_5, ← ofList_mulList, ← ofList_mulList,
    ← ofList_addList]
  trans ofList (112 :: List.replicate 2 0)
  · exact congrArg ofList (by decide +kernel)
  · rw [ofList_cons_replicate_zero]
    norm_cast

theorem interlaces_and_nodup_5 :
    Interlaces (motzkinRef 3 : ℝ[X]) (bigDescentPoly 5) ∧
      (bigDescentPoly 5 : ℝ[X]).roots.Nodup ∧ (motzkinRef 3 : ℝ[X]).roots.Nodup ∧
      ∀ x, (motzkinRef 3 : ℝ[X]).IsRoot x → ¬ (bigDescentPoly 5 : ℝ[X]).IsRoot x :=
  ⟨interlaces_5, nodup_of_interlaces_of_bezout interlaces_5 bezout_5 (by norm_num)⟩

private theorem interlaces_6 :
    Interlaces (motzkinRef 4 : ℝ[X]) (bigDescentPoly 6) := by
  rw [motzkinRef_4, bigDescentPoly_6]
  simp only [ofList_cons, ofList_nil, Int.cast_ofNat, map_ofNat, mul_zero, add_zero]
  rr_interlaces_explicit

private theorem bezout_6 :
    ofList [-4394, -392] * (bigDescentPoly 6 : ℝ[X])
      + ofList [7721, 8510, 392] * motzkinRef 4
      = C (66414 : ℝ) := by
  rw [motzkinRef_4, bigDescentPoly_6, ← ofList_mulList, ← ofList_mulList,
    ← ofList_addList]
  trans ofList (66414 :: List.replicate 4 0)
  · exact congrArg ofList (by decide +kernel)
  · rw [ofList_cons_replicate_zero]
    norm_cast

theorem interlaces_and_nodup_6 :
    Interlaces (motzkinRef 4 : ℝ[X]) (bigDescentPoly 6) ∧
      (bigDescentPoly 6 : ℝ[X]).roots.Nodup ∧ (motzkinRef 4 : ℝ[X]).roots.Nodup ∧
      ∀ x, (motzkinRef 4 : ℝ[X]).IsRoot x → ¬ (bigDescentPoly 6 : ℝ[X]).IsRoot x :=
  ⟨interlaces_6, nodup_of_interlaces_of_bezout interlaces_6 bezout_6 (by norm_num)⟩

private theorem interlaces_7 :
    Interlaces (motzkinRef 5 : ℝ[X]) (bigDescentPoly 7) := by
  rw [motzkinRef_5, bigDescentPoly_7]
  simp only [ofList_cons, ofList_nil, Int.cast_ofNat, map_ofNat, mul_zero, add_zero]
  rr_interlaces_explicit

private theorem bezout_7 :
    ofList [-28075, -8200] * (bigDescentPoly 7 : ℝ[X])
      + ofList [37227, 73745, 11480] * motzkinRef 5
      = C (601689 : ℝ) := by
  rw [motzkinRef_5, bigDescentPoly_7, ← ofList_mulList, ← ofList_mulList,
    ← ofList_addList]
  trans ofList (601689 :: List.replicate 4 0)
  · exact congrArg ofList (by decide +kernel)
  · rw [ofList_cons_replicate_zero]
    norm_cast

theorem interlaces_and_nodup_7 :
    Interlaces (motzkinRef 5 : ℝ[X]) (bigDescentPoly 7) ∧
      (bigDescentPoly 7 : ℝ[X]).roots.Nodup ∧ (motzkinRef 5 : ℝ[X]).roots.Nodup ∧
      ∀ x, (motzkinRef 5 : ℝ[X]).IsRoot x → ¬ (bigDescentPoly 7 : ℝ[X]).IsRoot x :=
  ⟨interlaces_7, nodup_of_interlaces_of_bezout interlaces_7 bezout_7 (by norm_num)⟩

private theorem interlaces_8 :
    Interlaces (motzkinRef 6 : ℝ[X]) (bigDescentPoly 8) := by
  rw [motzkinRef_6, bigDescentPoly_8]
  simp only [ofList_cons, ofList_nil, Int.cast_ofNat, map_ofNat, mul_zero, add_zero]
  rr_interlaces_explicit

private theorem bezout_8 :
    ofList [-4024829725, -2527643850, -107352150] * (bigDescentPoly 8 : ℝ[X])
      + ofList [4156189046, 13679358090, 4536102720, 128822580] * motzkinRef 6
      = C (129151888294 : ℝ) := by
  rw [motzkinRef_6, bigDescentPoly_8, ← ofList_mulList, ← ofList_mulList,
    ← ofList_addList]
  trans ofList (129151888294 :: List.replicate 6 0)
  · exact congrArg ofList (by decide +kernel)
  · rw [ofList_cons_replicate_zero]
    norm_cast

theorem interlaces_and_nodup_8 :
    Interlaces (motzkinRef 6 : ℝ[X]) (bigDescentPoly 8) ∧
      (bigDescentPoly 8 : ℝ[X]).roots.Nodup ∧ (motzkinRef 6 : ℝ[X]).roots.Nodup ∧
      ∀ x, (motzkinRef 6 : ℝ[X]).IsRoot x → ¬ (bigDescentPoly 8 : ℝ[X]).IsRoot x :=
  ⟨interlaces_8, nodup_of_interlaces_of_bezout interlaces_8 bezout_8 (by norm_num)⟩

private theorem interlaces_9 :
    Interlaces (motzkinRef 7 : ℝ[X]) (bigDescentPoly 9) := by
  rw [motzkinRef_7, bigDescentPoly_9]
  simp only [ofList_cons, ofList_nil, Int.cast_ofNat, map_ofNat, mul_zero, add_zero]
  rr_interlaces_explicit

private theorem bezout_9 :
    ofList [-63555861894, -70749568260, -9280720540] * (bigDescentPoly 9 : ℝ[X])
      + ofList [52157735564, 267998169579, 156605298066, 13655917366] * motzkinRef 7
      = C (3180617748022 : ℝ) := by
  rw [motzkinRef_7, bigDescentPoly_9, ← ofList_mulList, ← ofList_mulList,
    ← ofList_addList]
  trans ofList (3180617748022 :: List.replicate 6 0)
  · exact congrArg ofList (by decide +kernel)
  · rw [ofList_cons_replicate_zero]
    norm_cast

theorem interlaces_and_nodup_9 :
    Interlaces (motzkinRef 7 : ℝ[X]) (bigDescentPoly 9) ∧
      (bigDescentPoly 9 : ℝ[X]).roots.Nodup ∧ (motzkinRef 7 : ℝ[X]).roots.Nodup ∧
      ∀ x, (motzkinRef 7 : ℝ[X]).IsRoot x → ¬ (bigDescentPoly 9 : ℝ[X]).IsRoot x :=
  ⟨interlaces_9, nodup_of_interlaces_of_bezout interlaces_9 bezout_9 (by norm_num)⟩

private theorem interlaces_10 :
    Interlaces (motzkinRef 8 : ℝ[X]) (bigDescentPoly 10) := by
  rw [motzkinRef_8, bigDescentPoly_10]
  simp only [ofList_cons, ofList_nil, Int.cast_ofNat, map_ofNat, mul_zero, add_zero]
  rr_interlaces_explicit

private theorem bezout_10 :
    ofList [-1131848609796264178, -1989494994259792096, -535710423002257426, -13500960656556912]
      * (bigDescentPoly 10 : ℝ[X])
      + ofList [746906408383578703, 5720693536691724038, 5268460220778571894, 945288796334626590,
      17358377987001744] * motzkinRef 8
      = C (90473514274328636126 : ℝ) := by
  rw [motzkinRef_8, bigDescentPoly_10, ← ofList_mulList, ← ofList_mulList,
    ← ofList_addList]
  trans ofList (90473514274328636126 :: List.replicate 8 0)
  · exact congrArg ofList (by decide +kernel)
  · rw [ofList_cons_replicate_zero]
    norm_cast

theorem interlaces_and_nodup_10 :
    Interlaces (motzkinRef 8 : ℝ[X]) (bigDescentPoly 10) ∧
      (bigDescentPoly 10 : ℝ[X]).roots.Nodup ∧ (motzkinRef 8 : ℝ[X]).roots.Nodup ∧
      ∀ x, (motzkinRef 8 : ℝ[X]).IsRoot x → ¬ (bigDescentPoly 10 : ℝ[X]).IsRoot x :=
  ⟨interlaces_10, nodup_of_interlaces_of_bezout interlaces_10 bezout_10 (by norm_num)⟩

private theorem interlaces_11 :
    Interlaces (motzkinRef 9 : ℝ[X]) (bigDescentPoly 11) := by
  rw [motzkinRef_9, bigDescentPoly_11]
  simp only [ofList_cons, ofList_nil, Int.cast_ofNat, map_ofNat, mul_zero, add_zero]
  rr_interlaces_explicit

private theorem bezout_11 :
    ofList [-1292880061113728256, -3320478369026957376, -1524978402495662016, -116808965701558578]
      * (bigDescentPoly 11 : ℝ[X])
      + ofList [691772245935950621, 7611483375308931228, 10268941423317682716, 3153748825837993281,
      177067559119029273] * motzkinRef 9
      = C (168012661118829849088 : ℝ) := by
  rw [motzkinRef_9, bigDescentPoly_11, ← ofList_mulList, ← ofList_mulList,
    ← ofList_addList]
  trans ofList (168012661118829849088 :: List.replicate 8 0)
  · exact congrArg ofList (by decide +kernel)
  · rw [ofList_cons_replicate_zero]
    norm_cast

theorem interlaces_and_nodup_11 :
    Interlaces (motzkinRef 9 : ℝ[X]) (bigDescentPoly 11) ∧
      (bigDescentPoly 11 : ℝ[X]).roots.Nodup ∧ (motzkinRef 9 : ℝ[X]).roots.Nodup ∧
      ∀ x, (motzkinRef 9 : ℝ[X]).IsRoot x → ¬ (bigDescentPoly 11 : ℝ[X]).IsRoot x :=
  ⟨interlaces_11, nodup_of_interlaces_of_bezout interlaces_11 bezout_11 (by norm_num)⟩

private theorem interlaces_12 :
    Interlaces (motzkinRef 10 : ℝ[X]) (bigDescentPoly 12) := by
  rw [motzkinRef_10, bigDescentPoly_12]
  simp only [ofList_cons, ofList_nil, Int.cast_ofNat, map_ofNat, mul_zero, add_zero]
  rr_interlaces_explicit

private theorem bezout_12 :
    ofList [-63871679426453224410185864502, -226579531125865401548241680328,
      -159299287744898372939379295182, -24696963773522310663113664132, -413300123607464915457838860]
      * (bigDescentPoly 12 : ℝ[X])
      + ofList [27885595022095225185770279222, 427706787650744439841135113546,
      802212270986718825397447299048, 378884184963764352205637283537, 43259382320527666050017603022,
      560907310610130956692781310] * motzkinRef 10
      = C (13672747996261909302655459494362 : ℝ) := by
  rw [motzkinRef_10, bigDescentPoly_12, ← ofList_mulList, ← ofList_mulList,
    ← ofList_addList]
  trans ofList (13672747996261909302655459494362 :: List.replicate 10 0)
  · exact congrArg ofList (by decide +kernel)
  · rw [ofList_cons_replicate_zero]
    norm_cast

theorem interlaces_and_nodup_12 :
    Interlaces (motzkinRef 10 : ℝ[X]) (bigDescentPoly 12) ∧
      (bigDescentPoly 12 : ℝ[X]).roots.Nodup ∧ (motzkinRef 10 : ℝ[X]).roots.Nodup ∧
      ∀ x, (motzkinRef 10 : ℝ[X]).IsRoot x → ¬ (bigDescentPoly 12 : ℝ[X]).IsRoot x :=
  ⟨interlaces_12, nodup_of_interlaces_of_bezout interlaces_12 bezout_12 (by norm_num)⟩

private theorem interlaces_13 :
    Interlaces (motzkinRef 11 : ℝ[X]) (bigDescentPoly 13) := by
  rw [motzkinRef_11, bigDescentPoly_13]
  simp only [ofList_cons, ofList_nil, Int.cast_ofNat, map_ofNat, mul_zero, add_zero]
  rr_interlaces_explicit

private theorem bezout_13 :
    ofList [-54157060848811507432572029252708, -254318548257519498887053769077536,
      -254846300224226648671458546432072, -66571613033521895739655793050704,
      -3365163046143738123656714641068] * (bigDescentPoly 13 : ℝ[X])
      + ofList [19393530450868138872515859108792, 404441488142275453075455637224892,
      1013876747182883301960236758790708, 686176215460951296494052932390021,
      132627693269712022341258229075288, 5215274331253066009822960352824] * motzkinRef 11
      = C (19300738423376010108832824426535100 : ℝ) := by
  rw [motzkinRef_11, bigDescentPoly_13, ← ofList_mulList, ← ofList_mulList,
    ← ofList_addList]
  trans ofList (19300738423376010108832824426535100 :: List.replicate 10 0)
  · exact congrArg ofList (by decide +kernel)
  · rw [ofList_cons_replicate_zero]
    norm_cast

theorem interlaces_and_nodup_13 :
    Interlaces (motzkinRef 11 : ℝ[X]) (bigDescentPoly 13) ∧
      (bigDescentPoly 13 : ℝ[X]).roots.Nodup ∧ (motzkinRef 11 : ℝ[X]).roots.Nodup ∧
      ∀ x, (motzkinRef 11 : ℝ[X]).IsRoot x → ¬ (bigDescentPoly 13 : ℝ[X]).IsRoot x :=
  ⟨interlaces_13, nodup_of_interlaces_of_bezout interlaces_13 bezout_13 (by norm_num)⟩

private theorem interlaces_14 :
    Interlaces (motzkinRef 12 : ℝ[X]) (bigDescentPoly 14) := by
  rw [motzkinRef_12, bigDescentPoly_14]
  simp only [ofList_cons, ofList_nil, Int.cast_ofNat, map_ofNat, mul_zero, add_zero]
  rr_interlaces_explicit

private theorem bezout_14 :
    ofList [-2475978900006454640365982603704682838, -14888608151266885367243289020853630024,
      -20208781013849302144838902367256245088, -7997402414836017052871547037863376566,
      -813701165164296818754807697796869572, -9709477060297184908193774727835668]
      * (bigDescentPoly 14 : ℝ[X])
      + ofList [730563989247700818609866139217598990, 20285789762714315329054408754309145351,
      65905489978357449037449726213381156072, 60781349702982972745919982665431605897,
      17882932588727179487260981841000083569, 1421239424725067399512043838060273672,
      13681535857691487825182137116495714] * motzkinRef 12
      = C (1482042970954645222402762317975428931860 : ℝ) := by
  rw [motzkinRef_12, bigDescentPoly_14, ← ofList_mulList, ← ofList_mulList,
    ← ofList_addList]
  trans ofList (1482042970954645222402762317975428931860 :: List.replicate 12 0)
  · exact congrArg ofList (by decide +kernel)
  · rw [ofList_cons_replicate_zero]
    norm_cast

theorem interlaces_and_nodup_14 :
    Interlaces (motzkinRef 12 : ℝ[X]) (bigDescentPoly 14) ∧
      (bigDescentPoly 14 : ℝ[X]).roots.Nodup ∧ (motzkinRef 12 : ℝ[X]).roots.Nodup ∧
      ∀ x, (motzkinRef 12 : ℝ[X]).IsRoot x → ¬ (bigDescentPoly 14 : ℝ[X]).IsRoot x :=
  ⟨interlaces_14, nodup_of_interlaces_of_bezout interlaces_14 bezout_14 (by norm_num)⟩

private theorem interlaces_15 :
    Interlaces (motzkinRef 13 : ℝ[X]) (bigDescentPoly 15) := by
  rw [motzkinRef_13, bigDescentPoly_15]
  simp only [ofList_cons, ofList_nil, Int.cast_ofNat, map_ofNat, mul_zero, add_zero]
  rr_interlaces_explicit

private theorem bezout_15 :
    ofList [-252943149015019812075261577582859878, -1896580407637716372566535801305071884,
      -3356126969671060323503067290329852224, -1876259624337256683166627247233812984,
      -320058765228235239650775268008121908, -11503211479391125776683542776709932]
      * (bigDescentPoly 15 : ℝ[X])
      + ofList [61751576783371374152789196835425558, 2242768209849502485218851154099328874,
      9211532556486711997305548313664405851, 11148176547984560671403378684419048778,
      4656143696485399129315950430273145995, 622933402488657275790665246794588436,
      18126272634192076981440734072391408] * motzkinRef 13
      = C (256214028931553742541365923401523471550 : ℝ) := by
  rw [motzkinRef_13, bigDescentPoly_15, ← ofList_mulList, ← ofList_mulList,
    ← ofList_addList]
  trans ofList (256214028931553742541365923401523471550 :: List.replicate 12 0)
  · exact congrArg ofList (by decide +kernel)
  · rw [ofList_cons_replicate_zero]
    norm_cast

theorem interlaces_and_nodup_15 :
    Interlaces (motzkinRef 13 : ℝ[X]) (bigDescentPoly 15) ∧
      (bigDescentPoly 15 : ℝ[X]).roots.Nodup ∧ (motzkinRef 13 : ℝ[X]).roots.Nodup ∧
      ∀ x, (motzkinRef 13 : ℝ[X]).IsRoot x → ¬ (bigDescentPoly 15 : ℝ[X]).IsRoot x :=
  ⟨interlaces_15, nodup_of_interlaces_of_bezout interlaces_15 bezout_15 (by norm_num)⟩

private theorem interlaces_16 :
    Interlaces (motzkinRef 14 : ℝ[X]) (bigDescentPoly 16) := by
  rw [motzkinRef_14, bigDescentPoly_16]
  simp only [ofList_cons, ofList_nil, Int.cast_ofNat, map_ofNat, mul_zero, add_zero]
  rr_interlaces_explicit

private theorem bezout_16 :
    ofList [(-888414144540577401011996925695103973940764433513329467448657 + -3 * 10 ^ 60),
      (-574755749509666923806947196082422462572123705544861319423560 + -35 * 10 ^ 60),
      (-662299419817849967310303942962450951361327263729265053970719 + -79 * 10 ^ 60),
      (-870281045649154976773391734619336512794233408312132738959864 + -59 * 10 ^ 60),
      (-403735738750067400646602425965637744932233521437090307067768 + -15 * 10 ^ 60),
      (-111425577352759505690135473848014847312626672894522171919674 + -1 * 10 ^ 60),
      -9937714327489444276379958433394354435296029442151934331098] * (bigDescentPoly 16 : ℝ[X])
      + ofList [788510412696580573774693220709416602524075604753480425064756,
      (889074459035129121645500064308141034355882963385892773548065 + 36 * 10 ^ 60),
      (660050852704571028477343009122976537397126536242973051828314 + 187 * 10 ^ 60),
      (406096176417002306829831734883320756332190885401578018971864 + 289 * 10 ^ 60),
      (295580785695469261026633072327024241592446900993796981897394 + 163 * 10 ^ 60),
      (83743471948450799443079660730621351754045680370509338679862 + 33 * 10 ^ 60),
      (939266299011764633889495189936741582743037760386309943094956 + 1 * 10 ^ 60),
      14408527533096583542909869803196476593832471592117722969564] * motzkinRef 14
      = C ((157212789474011308414637768000569371053907960236124745457075 + 6709 * 10 ^ 60)
        : ℝ) := by
  rw [motzkinRef_14, bigDescentPoly_16, ← ofList_mulList, ← ofList_mulList,
    ← ofList_addList]
  trans ofList ((157212789474011308414637768000569371053907960236124745457075 + 6709 * 10 ^ 60)
    :: List.replicate 14 0)
  · exact congrArg ofList (by decide +kernel)
  · rw [ofList_cons_replicate_zero]
    norm_cast

theorem interlaces_and_nodup_16 :
    Interlaces (motzkinRef 14 : ℝ[X]) (bigDescentPoly 16) ∧
      (bigDescentPoly 16 : ℝ[X]).roots.Nodup ∧ (motzkinRef 14 : ℝ[X]).roots.Nodup ∧
      ∀ x, (motzkinRef 14 : ℝ[X]).IsRoot x → ¬ (bigDescentPoly 16 : ℝ[X]).IsRoot x :=
  ⟨interlaces_16, nodup_of_interlaces_of_bezout interlaces_16 bezout_16 (by norm_num)⟩

private theorem interlaces_17 :
    Interlaces (motzkinRef 15 : ℝ[X]) (bigDescentPoly 17) := by
  rw [motzkinRef_15, bigDescentPoly_17]
  simp only [ofList_cons, ofList_nil, Int.cast_ofNat, map_ofNat, mul_zero, add_zero]
  rr_interlaces_explicit

private theorem bezout_17 :
    ofList [(-913456686182053313576139053518026594665161216715092344958976 + -3 * 10 ^ 60),
      (-907943402046646127168575362132308033516431061728435206211584 + -42 * 10 ^ 60),
      (-719745412863865171947203243164955852338535495747702175641600 + -118 * 10 ^ 60),
      (-577474093567834550278931765386151473517436711958336952047040 + -115 * 10 ^ 60),
      (-843709443979334974677668086433853840393679777714363301565712 + -41 * 10 ^ 60),
      (-49753656472708211292192908880241691097478264544949487385980 + -5 * 10 ^ 60),
      -135797350593858024214703856955986479115253652472400165742295] * (bigDescentPoly 17 : ℝ[X])
      + ofList [661659692848076505458752559630142845939148747134836183291573,
      (345683402665351123699145106095792155057902594215796247095404 + 39 * 10 ^ 60),
      (683734760471717160754075525181693027875347977490172349850044 + 243 * 10 ^ 60),
      (722603506290830710987612818208228723704775203103075685788597 + 467 * 10 ^ 60),
      (566829710128244955311460197031189013432761187346293108562628 + 343 * 10 ^ 60),
      (338295383928427919589039181386089572658535353526776147687384 + 98 * 10 ^ 60),
      (673623847144678865016638464910515517727743728537461229486752 + 9 * 10 ^ 60),
      216790393574312895533434766512641662774048293993623450298461] * motzkinRef 15
      = C ((892738151345168591660559669940055119249562122513434724270080 + 11568 * 10 ^ 60)
        : ℝ) := by
  rw [motzkinRef_15, bigDescentPoly_17, ← ofList_mulList, ← ofList_mulList,
    ← ofList_addList]
  trans ofList ((892738151345168591660559669940055119249562122513434724270080 + 11568 * 10 ^ 60)
    :: List.replicate 14 0)
  · exact congrArg ofList (by decide +kernel)
  · rw [ofList_cons_replicate_zero]
    norm_cast

theorem interlaces_and_nodup_17 :
    Interlaces (motzkinRef 15 : ℝ[X]) (bigDescentPoly 17) ∧
      (bigDescentPoly 17 : ℝ[X]).roots.Nodup ∧ (motzkinRef 15 : ℝ[X]).roots.Nodup ∧
      ∀ x, (motzkinRef 15 : ℝ[X]).IsRoot x → ¬ (bigDescentPoly 17 : ℝ[X]).IsRoot x :=
  ⟨interlaces_17, nodup_of_interlaces_of_bezout interlaces_17 bezout_17 (by norm_num)⟩

private theorem interlaces_18 :
    Interlaces (motzkinRef 16 : ℝ[X]) (bigDescentPoly 18) := by
  rw [motzkinRef_16, bigDescentPoly_18]
  simp only [ofList_cons, ofList_nil, Int.cast_ofNat, map_ofNat, mul_zero, add_zero]
  rr_interlaces_explicit

private theorem bezout_18 :
    ofList [(-676579574735703313815195574021955721047334559851205333817082
      + -98160211887407188 * 10 ^ 60),
      (-798927648261420855961783431399097185647910605114053425313280
      + -1270422444101666534 * 10 ^ 60),
      (-89221162986239481297155822339834419125592760617488421521662
      + -4259013750824786541 * 10 ^ 60),
      (-990606146260265508596156422895292311254326962665862250566076
      + -5218316482551403246 * 10 ^ 60),
      (-840343441804205166472843596193811568626333338507407871154710
      + -2530932817402641204 * 10 ^ 60),
      (-882743324215803090222957911032143792975783199135108582696020
      + -459680321947231870 * 10 ^ 60),
      (-620369638922147000944813216099224535651334320546254127241170
      + -24782453987375853 * 10 ^ 60), (-79982353745016955299503878100240856620555425267859497246800
      + -172262758997944 * 10 ^ 60)] * (bigDescentPoly 18 : ℝ[X])
      + ofList [(28173082937508513772641057117854782896926309606567506517487
      + 13888012903079432 * 10 ^ 60), (351083902290557478856646983261097620624608314643191330863502
      + 1037501401292675393 * 10 ^ 60),
      (459091812544518551834137554885144114071662442108724772607512
      + 7708967405099289561 * 10 ^ 60), (40094146849038471536601103347902751163073729159728976244080
      + 18062435579297409140 * 10 ^ 60),
      (623824001282751681101751536264159160201199754937911883705890
      + 16782228917549024477 * 10 ^ 60),
      (567432954062101480416828152672684259286031464456484094582586
      + 6460492120768682154 * 10 ^ 60),
      (583523004757287984529632282146577175087927930526907188411764 + 959612978480650526 * 10 ^ 60),
      (441616936385514548203535041806253175618667879930049932384440 + 43235329627531442 * 10 ^ 60),
      (866826985971633528136327427673084346878026224872630863051200 + 255382551801147 * 10 ^ 60)]
      * motzkinRef 16
      = C ((571961422582403542471624289934182234056831638118606440808190
        + 499756967714964201541 * 10 ^ 60) : ℝ) := by
  rw [motzkinRef_16, bigDescentPoly_18, ← ofList_mulList, ← ofList_mulList,
    ← ofList_addList]
  trans ofList ((571961422582403542471624289934182234056831638118606440808190
    + 499756967714964201541 * 10 ^ 60) :: List.replicate 16 0)
  · exact congrArg ofList (by decide +kernel)
  · rw [ofList_cons_replicate_zero]
    norm_cast

theorem interlaces_and_nodup_18 :
    Interlaces (motzkinRef 16 : ℝ[X]) (bigDescentPoly 18) ∧
      (bigDescentPoly 18 : ℝ[X]).roots.Nodup ∧ (motzkinRef 16 : ℝ[X]).roots.Nodup ∧
      ∀ x, (motzkinRef 16 : ℝ[X]).IsRoot x → ¬ (bigDescentPoly 18 : ℝ[X]).IsRoot x :=
  ⟨interlaces_18, nodup_of_interlaces_of_bezout interlaces_18 bezout_18 (by norm_num)⟩

private theorem interlaces_19 :
    Interlaces (motzkinRef 17 : ℝ[X]) (bigDescentPoly 19) := by
  rw [motzkinRef_17, bigDescentPoly_19]
  simp only [ofList_cons, ofList_nil, Int.cast_ofNat, map_ofNat, mul_zero, add_zero]
  rr_interlaces_explicit

private theorem bezout_19 :
    ofList [(-797054822688132699871067319463899952738844846972162276313156
      + -17110954804581247584 * 10 ^ 60),
      (-715000441887099078418715790518753780400403038034318625385632
      + -258063461207134643858 * 10 ^ 60),
      (-663629186081648040202976551850428932857233765765313523274016
      + -1031266444511163424224 * 10 ^ 60),
      (-347080144206961717287178999240041531334832252853627162728400
      + -1553981752692339258809 * 10 ^ 60),
      (-127437245347911660734398742372486303103804758411208832222184
      + -973302223594396614707 * 10 ^ 60),
      (-978318607109035210352501867303874354116734853648122561675152
      + -248260455459936433101 * 10 ^ 60),
      (-829850191109527437966058119237689103548518788511948117427120
      + -22357737830435832794 * 10 ^ 60),
      (-814288157418656138671275805318338803777174836417322566601120
      + -467008089098165787 * 10 ^ 60)] * (bigDescentPoly 19 : ℝ[X])
      + ofList [(164351816880376734420261578284946725698864188828854988485245
      + 2033207049767290950 * 10 ^ 60),
      (402025392661386816239713605241334311736004692032165543194180
      + 188839199573687460855 * 10 ^ 60),
      (61890494476030234252659000745153412311302956599840086443656
      + 1662119806858790786225 * 10 ^ 60),
      (918988116699755150053892847312680728865665150347928062144788
      + 4677620313236993109077 * 10 ^ 60),
      (899862268285362968175485702283237352556408916695440958518666
      + 5372016033956316739978 * 10 ^ 60),
      (697956118927040956578651934822363994000418271496298954765820
      + 2681005711661510101722 * 10 ^ 60),
      (338219127416065097486418291525599561376211157616719492519996
      + 561066460077243533946 * 10 ^ 60),
      (865296407286716040017977502127162029062840262393217269731128
      + 42343325746790548144 * 10 ^ 60),
      (615415588549767850531061066761604739059368273739800757587936 + 753398734605177534 * 10 ^ 60)]
      * motzkinRef 17
      = C ((845466659521619304755172791254050523241568409003251479532300
        + 150740905174106219508789 * 10 ^ 60) : ℝ) := by
  rw [motzkinRef_17, bigDescentPoly_19, ← ofList_mulList, ← ofList_mulList,
    ← ofList_addList]
  trans ofList ((845466659521619304755172791254050523241568409003251479532300
    + 150740905174106219508789 * 10 ^ 60) :: List.replicate 16 0)
  · exact congrArg ofList (by decide +kernel)
  · rw [ofList_cons_replicate_zero]
    norm_cast

theorem interlaces_and_nodup_19 :
    Interlaces (motzkinRef 17 : ℝ[X]) (bigDescentPoly 19) ∧
      (bigDescentPoly 19 : ℝ[X]).roots.Nodup ∧ (motzkinRef 17 : ℝ[X]).roots.Nodup ∧
      ∀ x, (motzkinRef 17 : ℝ[X]).IsRoot x → ¬ (bigDescentPoly 19 : ℝ[X]).IsRoot x :=
  ⟨interlaces_19, nodup_of_interlaces_of_bezout interlaces_19 bezout_19 (by norm_num)⟩

private theorem interlaces_20 :
    Interlaces (motzkinRef 18 : ℝ[X]) (bigDescentPoly 20) := by
  rw [motzkinRef_18, bigDescentPoly_20]
  simp only [ofList_cons, ofList_nil, Int.cast_ofNat, map_ofNat, mul_zero, add_zero]
  rr_interlaces_explicit

private theorem bezout_20 :
    ofList [(-258884383318109708116217644208789823591337806255591465533861
      + -40688535163868869185521408166428 * 10 ^ 60),
      (-926872564350595197087532397485462624881238511101296371415198
      + -707209786916900685978607568412160 * 10 ^ 60),
      (-667608054588535735985961436294513991160265198188374575761746
      + -3322531214461705649987121326638193 * 10 ^ 60),
      (-701114628084194773242242421809936194447184963794898846201977
      + -6042223828183790637676195398916040 * 10 ^ 60),
      (-725484741676863763854628551049005928900573064242867657454807
      + -4749851317888651411894650295134678 * 10 ^ 60),
      (-603590738551833352664308263894169876719666898351834008133152
      + -1620141594347075679301387220742163 * 10 ^ 60),
      (-944969376560623672244282213087657846892432925410764220642266
      + -219329031907334993675054841267270 * 10 ^ 60),
      (-400806263630344238404269950656949676992044420231118683459516
      + -9177348306065651252465262753965 * 10 ^ 60),
      (-268242935654383078904651646926416725140009788672592352096757
      + -51018333622180339667833523616 * 10 ^ 60)] * (bigDescentPoly 20 : ℝ[X])
      + ofList [(183654303597895762259918022879372566097077283949410361558854
      + 4075198045831331209992569333831 * 10 ^ 60),
      (474041571122753563027802440370601343624175093963530332431344
      + 466178628414612287812947161147967 * 10 ^ 60),
      (998649304048730782271705303680988412951633504158634989878355
      + 4806866587187089963510687033488478 * 10 ^ 60),
      (26169698322231895330056877448621764351120630688962179667802
      + 16026083930790524754306398422923878 * 10 ^ 60),
      (221566936886271185556298129047450817411370605809545750693298
      + 22324172687479350729887769842195124 * 10 ^ 60),
      (618123953660470061719918084402114898894256492234761019034038
      + 14037523254608255463665047744190283 * 10 ^ 60),
      (349531391402950496953685314510753420109645529085576418745806
      + 3940903193953813402679171219629776 * 10 ^ 60),
      (331972111695671432485837546057917552610288106981937031429972
      + 448289624620715443184193982950019 * 10 ^ 60),
      (779399579692272448054666988123665835169954954101643897039741
      + 16015328136463988093615132936391 * 10 ^ 60),
      (701844233202769031880364826233246797424391573278379818939943
      + 76999698091229809231296255922 * 10 ^ 60)] * motzkinRef 18
      = C ((125302566757836823831856180828557921443896360525638750580470
        + 622912010622699846607574761658118086 * 10 ^ 60) : ℝ) := by
  rw [motzkinRef_18, bigDescentPoly_20, ← ofList_mulList, ← ofList_mulList,
    ← ofList_addList]
  trans ofList ((125302566757836823831856180828557921443896360525638750580470
    + 622912010622699846607574761658118086 * 10 ^ 60) :: List.replicate 18 0)
  · exact congrArg ofList (by decide +kernel)
  · rw [ofList_cons_replicate_zero]
    norm_cast

theorem interlaces_and_nodup_20 :
    Interlaces (motzkinRef 18 : ℝ[X]) (bigDescentPoly 20) ∧
      (bigDescentPoly 20 : ℝ[X]).roots.Nodup ∧ (motzkinRef 18 : ℝ[X]).roots.Nodup ∧
      ∀ x, (motzkinRef 18 : ℝ[X]).IsRoot x → ¬ (bigDescentPoly 20 : ℝ[X]).IsRoot x :=
  ⟨interlaces_20, nodup_of_interlaces_of_bezout interlaces_20 bezout_20 (by norm_num)⟩

private theorem interlaces_21 :
    Interlaces (motzkinRef 19 : ℝ[X]) (bigDescentPoly 21) := by
  rw [motzkinRef_19, bigDescentPoly_21]
  simp only [ofList_cons, ofList_nil, Int.cast_ofNat, map_ofNat, mul_zero, add_zero]
  rr_interlaces_explicit

private theorem bezout_21 :
    ofList [(-469592216636455658017381541616264259126050994216387236889996
      + -2723558075399572097496387071259513515856 * 10 ^ 60),
      (-789690019392698753881462656723363359314373680851181007910184
      + -54032303282296878410594267662236450133950 * 10 ^ 60),
      (-717759964632484652293322210042830115565601768198941210548744
      + -294916343536192804068808340808275675621324 * 10 ^ 60),
      (-798247667007416756714492874596706590736807135029088873736688
      + -637147032903873716241117365439016623987419 * 10 ^ 60),
      (-947076744908709540530705834238444578760050246860622382064060
      + -614496690750475132567440432427174220594010 * 10 ^ 60),
      (-279642060120185259582089253860878245731312405935273867189728
      + -270230604547391907295229132658957552908356 * 10 ^ 60),
      (-639497490006212325523152563940703615354185310229547730204192
      + -51320201019097715029759260426561781811379 * 10 ^ 60),
      (-666109197837044813773968404895607481895016399374169453015712
      + -3584432702959264695336145791829843836749 * 10 ^ 60),
      (-455170960037221837998334737366801653605496139666782971005556
      + -59849024381436176630846860312782633165 * 10 ^ 60)] * (bigDescentPoly 21 : ℝ[X])
      + ofList [(994818996152128623215194700335287677244194055554190176081752
      + 230755653150165722908929734962351022289 * 10 ^ 60),
      (259079203493638787817946845354821606466803868233638686463310
      + 32236747456635546088673703138883182580493 * 10 ^ 60),
      (969899506521963494884407460951930376256119874474267046844380
      + 385605215957447324822448714890699013078570 * 10 ^ 60),
      (306377875150333851127605750126600798223842066196777167395239
      + 1505088208243069073036123372489169099785997 * 10 ^ 60),
      (103357864256081748900705237763766568104078315327594384623238
      + 2503201494514199032117997996146639745869583 * 10 ^ 60),
      (847364505469450570864638599581798083708450012693773027900308
      + 1938473200429951064249680060663879946016537 * 10 ^ 60),
      (474750082469160889004061984338916363765735948651241502546720
      + 703813372527358742117770418825355977117174 * 10 ^ 60),
      (420163146333929696853288291294331879458334444333203635795386
      + 112609562377579085655302730738912475091682 * 10 ^ 60),
      (646301976614125360441850553089402838539359122996556962221542
      + 6730580847733818025396464430599343380588 * 10 ^ 60),
      (977293169054050880558506149207634836938134282214720849505436
      + 97386668329783316360991127200165189245 * 10 ^ 60)] * motzkinRef 19
      = C ((714105758945449102154565821649433622523839828824684990873420
        + 72745482805392265113718441464863848895042870 * 10 ^ 60) : ℝ) := by
  rw [motzkinRef_19, bigDescentPoly_21, ← ofList_mulList, ← ofList_mulList,
    ← ofList_addList]
  trans ofList ((714105758945449102154565821649433622523839828824684990873420
    + 72745482805392265113718441464863848895042870 * 10 ^ 60) :: List.replicate 18 0)
  · exact congrArg ofList (by decide +kernel)
  · rw [ofList_cons_replicate_zero]
    norm_cast

theorem interlaces_and_nodup_21 :
    Interlaces (motzkinRef 19 : ℝ[X]) (bigDescentPoly 21) ∧
      (bigDescentPoly 21 : ℝ[X]).roots.Nodup ∧ (motzkinRef 19 : ℝ[X]).roots.Nodup ∧
      ∀ x, (motzkinRef 19 : ℝ[X]).IsRoot x → ¬ (bigDescentPoly 21 : ℝ[X]).IsRoot x :=
  ⟨interlaces_21, nodup_of_interlaces_of_bezout interlaces_21 bezout_21 (by norm_num)⟩

private theorem interlaces_22 :
    Interlaces (motzkinRef 20 : ℝ[X]) (bigDescentPoly 22) := by
  rw [motzkinRef_20, bigDescentPoly_22]
  simp only [ofList_cons, ofList_nil, Int.cast_ofNat, map_ofNat, mul_zero, add_zero]
  rr_interlaces_explicit

private theorem bezout_22 :
    ofList [(-809087330620416412781968906129068346833376171373405779427436
      + -831730575580874897371916545196445274866147981950431188028747 * 10 ^ 60 + -172 * 10 ^ 120),
      (-67403976738902450984133863966016050527765034835391668400768
      + -758993106640331646498725790345822410429997938420151589473847 * 10 ^ 60 + -3880 * 10 ^ 120),
      (-276884289619185548877898187879783756563866743718775842735676
      + -837079741558119305450664296679920007516696544319163631160946 * 10 ^ 60
      + -24356 * 10 ^ 120), (-182258412302786632877428890722641788436135353631123786317824
      + -412201133610083603158636622472548805278435393464977336598880 * 10 ^ 60
      + -61685 * 10 ^ 120), (-333832526598594603613681018282605973447477342199540209802748
      + -250899990977342755026042686003873762835258827980627817089986 * 10 ^ 60
      + -71643 * 10 ^ 120), (-115115519447165281004909575466609737081486320953937282598600
      + -450778644881349606047047016881986659757272912348471936494234 * 10 ^ 60
      + -39484 * 10 ^ 120), (-946015914495792557182412911369190569049487642688255650425876
      + -399396036457099496589756236924575756745003448661927593451489 * 10 ^ 60
      + -10017 * 10 ^ 120), (-952493508628258497744162237845291531131350314942925176308320
      + -16837500047007024550413735932433132944213059837131113407064 * 10 ^ 60 + -1051 * 10 ^ 120),
      (-263378784388071930047601314416249444792791293943039754015728
      + -136730692717060986519553427785433465332660806713231858051647 * 10 ^ 60 + -35 * 10 ^ 120),
      (-448771004088612455437661198028716879108596936136092480350624
      + -159786283554018830788633245834993553003706050235339969828806 * 10 ^ 60)]
      * (bigDescentPoly 22 : ℝ[X])
      + ofList [(499352674565194846190263325431370957783653418443777563528092
      + 432450573656202856741765973395467089006909903331253656508644 * 10 ^ 60 + 12 * 10 ^ 120),
      (19463585061651260301452376372976135513718084814097829696236
      + 538809574695756028346114340750492169958099118480210425026468 * 10 ^ 60 + 2104 * 10 ^ 120),
      (157803467114214946244011626917162144424674152798061655214176
      + 560174741705427277380963894574755721086722948345112368441082 * 10 ^ 60 + 28949 * 10 ^ 120),
      (986112591166901481541986809374929330747055715096319233023752
      + 808579293995242283554128147390001302463263771365620788652465 * 10 ^ 60 + 130927 * 10 ^ 120),
      (404923011460674887845305307802833131768615467766474652986316
      + 516326495124359563980786760724312404042545647231290468954477 * 10 ^ 60 + 256532 * 10 ^ 120),
      (196627844408602777612952018057437065482989687966086209093876
      + 386761613213568377348482906918546649161384744601685036579250 * 10 ^ 60 + 240131 * 10 ^ 120),
      (267996203858460705861926976217045895663155749080289473826607
      + 390939752338365066871259874309744118512430326371647695460855 * 10 ^ 60 + 109599 * 10 ^ 120),
      (787683206244902700900621014254655736254948604541801301336556
      + 644366255539947525451166171849515177693518187076407980247367 * 10 ^ 60 + 23486 * 10 ^ 120),
      (251146183643615881257843330002731690165790352803975093747412
      + 429027369161651568803642240993138620330266468359624772435106 * 10 ^ 60 + 2113 * 10 ^ 120),
      (760060580276612946690794514039424946313258061756661872152648
      + 347360123646230930674504928993790197473752500994540943336763 * 10 ^ 60 + 61 * 10 ^ 120),
      (481077953630356442229006707435741426422335531386332636612256
      + 244721502628219838247606669198581457339088737571676910209348 * 10 ^ 60)] * motzkinRef 20
      = C ((214451284477897708673784584521813748105955054813032980563540
        + 389617705434776866984883430766080670356076719127571868588588 * 10 ^ 60
        + 8083530 * 10 ^ 120) : ℝ) := by
  rw [motzkinRef_20, bigDescentPoly_22, ← ofList_mulList, ← ofList_mulList,
    ← ofList_addList]
  trans ofList ((214451284477897708673784584521813748105955054813032980563540
    + 389617705434776866984883430766080670356076719127571868588588 * 10 ^ 60 + 8083530 * 10 ^ 120)
    :: List.replicate 20 0)
  · exact congrArg ofList (by decide +kernel)
  · rw [ofList_cons_replicate_zero]
    norm_cast

theorem interlaces_and_nodup_22 :
    Interlaces (motzkinRef 20 : ℝ[X]) (bigDescentPoly 22) ∧
      (bigDescentPoly 22 : ℝ[X]).roots.Nodup ∧ (motzkinRef 20 : ℝ[X]).roots.Nodup ∧
      ∀ x, (motzkinRef 20 : ℝ[X]).IsRoot x → ¬ (bigDescentPoly 22 : ℝ[X]).IsRoot x :=
  ⟨interlaces_22, nodup_of_interlaces_of_bezout interlaces_22 bezout_22 (by norm_num)⟩

private theorem interlaces_23 :
    Interlaces (motzkinRef 21 : ℝ[X]) (bigDescentPoly 23) := by
  rw [motzkinRef_21, bigDescentPoly_23]
  simp only [ofList_cons, ofList_nil, Int.cast_ofNat, map_ofNat, mul_zero, add_zero]
  rr_interlaces_explicit

private theorem bezout_23 :
    ofList [(-231918995109333495868974488209349483511556501699459514105856
      + -148623971718650250782543993914831596760261760513688263392489 * 10 ^ 60),
      (-681789415711649908977903892347141210624745334785506228174848
      + -749082336460535253116441573411921094189308787834348217893297 * 10 ^ 60 + -3 * 10 ^ 120),
      (-2824641435980498601776574758777572120140118010441768239104
      + -815229375848322752836370699250802197626102889664391425175158 * 10 ^ 60 + -26 * 10 ^ 120),
      (-684695714900686979088512101534089373873190718437960425521152
      + -703674719751926295456600510852471634429370287219784912981297 * 10 ^ 60 + -78 * 10 ^ 120),
      (-442086029022633797997080170175360136090295712459705234710528
      + -383878122429953110170073983602422355564436421077467986991845 * 10 ^ 60 + -108 * 10 ^ 120),
      (-850018889177828236897302743994151213118849147987704558200832
      + -185429221927947852627392829256292741851136271442799950871887 * 10 ^ 60 + -73 * 10 ^ 120),
      (-997879710772100916760589570368652096862883301336925754999808
      + -916115628123508180503432901806776575013727647602849159925175 * 10 ^ 60 + -23 * 10 ^ 120),
      (-952752057029386909254711371637482042219920034464151822333408
      + -517833396500343280671781391357267873859088166739186708149241 * 10 ^ 60 + -3 * 10 ^ 120),
      (-539947599268917417901373629491695431175882062299028507087024
      + -196218640074272927413293862164136492052388703235467095132707 * 10 ^ 60),
      (-420770539686626644357993595031145016235884161565043136092460
      + -2679194039576898895488096229222357761283298061703372291844 * 10 ^ 60)]
      * (bigDescentPoly 23 : ℝ[X])
      + ofList [(482162631068071888852016478229214140659054758272900665670319
      + 9110242393318688966941451909468949604074113736123998200351 * 10 ^ 60),
      (383943110616808004128812605075935003277729637482340515829068
      + 855189542388728618017255876497816870602864734421665054942752 * 10 ^ 60 + 1 * 10 ^ 120),
      (247873552011301723170255421864885265490962501362000773885980
      + 118700317896256312294694481896666772259922522691853762437146 * 10 ^ 60 + 29 * 10 ^ 120),
      (722541031202457620997542482617763505195324412303118985705075
      + 214273043420072032696416693278984456904538608723604645583280 * 10 ^ 60 + 151 * 10 ^ 120),
      (609382410051806624338955570055523278344359099040382956049937
      + 55002489776216368448954731231846553935116752378140713175682 * 10 ^ 60 + 345 * 10 ^ 120),
      (819830555879718252039239658479892035729445389449005397780048
      + 394504404230687127814741016159126089491159183717961338550280 * 10 ^ 60 + 384 * 10 ^ 120),
      (709914724006972878970582506620220328553280968456540808787244
      + 598961137473023498177489333936263710722388791176231657273724 * 10 ^ 60 + 215 * 10 ^ 120),
      (746106295575726841659902333737479916426412699143216380583144
      + 661382577648560505629954523343475062253599391980417130788002 * 10 ^ 60 + 59 * 10 ^ 120),
      (822379202281973111026257635389164154234675491698357084029926
      + 542849908749808988380225926848629480042617327227110958442035 * 10 ^ 60 + 7 * 10 ^ 120),
      (264615849002237404024416563200453472971650980593609994243326
      + 366002603438974103246391451885168023185510489597921633814278 * 10 ^ 60),
      (447229284664151167918353432580134575737611048253501533007390
      + 4391141879345331059799656101611692374747124909792437263071 * 10 ^ 60)] * motzkinRef 21
      = C ((706104439522313331452282061776659954152550729638061780500480
        + 166734982700376114199845003715121503418458441217676880570814 * 10 ^ 60 + 12214 * 10 ^ 120)
        : ℝ) := by
  rw [motzkinRef_21, bigDescentPoly_23, ← ofList_mulList, ← ofList_mulList,
    ← ofList_addList]
  trans ofList ((706104439522313331452282061776659954152550729638061780500480
    + 166734982700376114199845003715121503418458441217676880570814 * 10 ^ 60 + 12214 * 10 ^ 120)
    :: List.replicate 20 0)
  · exact congrArg ofList (by decide +kernel)
  · rw [ofList_cons_replicate_zero]
    norm_cast

theorem interlaces_and_nodup_23 :
    Interlaces (motzkinRef 21 : ℝ[X]) (bigDescentPoly 23) ∧
      (bigDescentPoly 23 : ℝ[X]).roots.Nodup ∧ (motzkinRef 21 : ℝ[X]).roots.Nodup ∧
      ∀ x, (motzkinRef 21 : ℝ[X]).IsRoot x → ¬ (bigDescentPoly 23 : ℝ[X]).IsRoot x :=
  ⟨interlaces_23, nodup_of_interlaces_of_bezout interlaces_23 bezout_23 (by norm_num)⟩

private theorem interlaces_24 :
    Interlaces (motzkinRef 22 : ℝ[X]) (bigDescentPoly 24) := by
  rw [motzkinRef_22, bigDescentPoly_24]
  simp only [ofList_cons, ofList_nil, Int.cast_ofNat, map_ofNat, mul_zero, add_zero]
  rr_interlaces_explicit

private theorem bezout_24 :
    ofList [(-377698471641110077334799477758285937096176780742863167630594
      + -392625129003592204201273297765639381743732581782096077833789 * 10 ^ 60
      + -9969814760659751878944410158 * 10 ^ 120),
      (-843794527060151091251991521676810511724033506345765580371368
      + -772865714441969947144280709437583238217792463483467904957351 * 10 ^ 60
      + -280668724823154572654518297534 * 10 ^ 120),
      (-80027863426804705850763562674352426327663120838298086100834
      + -357610517519545169626900064365184280530141444832390473790645 * 10 ^ 60
      + -2269645728737804921424827648199 * 10 ^ 120),
      (-392687329937575307383102545311987628897731965059939421570860
      + -165098765688049657029966542304979497492795758190037920062987 * 10 ^ 60
      + -7643885769123180171783432903913 * 10 ^ 120),
      (-470531153800751411185127521239048937045275946146204675584816
      + -913060281091032415343418971420589573172146517498148317253650 * 10 ^ 60
      + -12318561370048609894897946828064 * 10 ^ 120),
      (-132363213368863585107811896729864470984059600769634631407260
      + -990420313215380370987040239615386523952353035591754650823673 * 10 ^ 60
      + -10004557066709205516190327325748 * 10 ^ 120),
      (-918572787191757914834884419941043743666072536177705607004432
      + -828928185313835906720478119606684375741657928180286434401398 * 10 ^ 60
      + -4093788961231043631278448868274 * 10 ^ 120),
      (-683748863244233014829149617237179518642226201858475868264716
      + -304731573434796139700071194245459920251859123463114241422960 * 10 ^ 60
      + -803938343244812009465802077971 * 10 ^ 120),
      (-856841992563029618058102111815182751414078380597723129153710
      + -123523391586974174778382493563007164970229948634501607462315 * 10 ^ 60
      + -67332379264531165552433698105 * 10 ^ 120),
      (-243966877232504445928824945088432842173420886406698042974544
      + -995428105152867144279839891400934359336069186542832116315923 * 10 ^ 60
      + -1840213633753265670014322550 * 10 ^ 120),
      (-432608003922225985904882325083926866943057012256263148021094
      + -468135309217409029399318158531700328134740160376325467681889 * 10 ^ 60
      + -6972875792019737725806002 * 10 ^ 120)] * (bigDescentPoly 24 : ℝ[X])
      + ofList [(477826602702185194312177916816673291617600393211681972207782
      + 102013297837053998122307433752546976045996416544124468920576 * 10 ^ 60
      + 522683572885368147428295857 * 10 ^ 120),
      (750326712982061659181940931267112685210834178369975569967610
      + 598559673700932420836739832582992051088484109663206721060391 * 10 ^ 60
      + 127180543654161497161904787310 * 10 ^ 120),
      (575349709416014249393126589303775184092564212685641927556728
      + 724787686684975721546988124501504737784577485486751766880125 * 10 ^ 60
      + 2261742522685832770428684693727 * 10 ^ 120),
      (7296192258514296408381382130100153322786996985988480528280
      + 997497397075515985318491459202530368700888158820050085501592 * 10 ^ 60
      + 13378376677697761353674567306809 * 10 ^ 120),
      (128988352764413108963994967775530552051523296696367853952154
      + 609064203693070386081801333103413859592015544853558056225435 * 10 ^ 60
      + 35200338728786354653214308239619 * 10 ^ 120),
      (273291854157840768747206606298571925306649360266911125680371
      + 991928219662697798203414085091865334496365839870726999774265 * 10 ^ 60
      + 46056589500481416282974446038732 * 10 ^ 120),
      (596606641692070078258103024473667023051684802798860984885986
      + 426605906081626995945338675710140116296830068724452939268700 * 10 ^ 60
      + 31161329614000424830841598899327 * 10 ^ 120),
      (405874810555608850074106284972412662329375234158278787107672
      + 230283366874061097835116919127609135997915110886407950825768 * 10 ^ 60
      + 10824260725019400068329201871330 * 10 ^ 120),
      (269868312849154452564837603708478097852015017146450669470920
      + 773232699254998173768814811166598990772774737089168421284419 * 10 ^ 60
      + 1830956897246981373283391840523 * 10 ^ 120),
      (509255174062746459905120915899382700710603253995670319842386
      + 41624941371303725882937998839965179757271002998571036156818 * 10 ^ 60
      + 133650943739337054111227051305 * 10 ^ 120),
      (756996915376638359347308890425026490509786181883443233050150
      + 131846587391505845024986347314294255370081608662379853336277 * 10 ^ 60
      + 3214851461229316309003115945 * 10 ^ 120),
      (691927055922964060478933668517154260549416329144436572708376
      + 870610768266449980872511384363850146421133555223009023005445 * 10 ^ 60
      + 10811005871939696105890216 * 10 ^ 120)] * motzkinRef 22
      = C ((203185311885692301754397024651294227136674097233607503558878
        + 82867652427420186029453175697202303416948485678251969555192 * 10 ^ 60
        + 1444308448068893277513286654492996 * 10 ^ 120) : ℝ) := by
  rw [motzkinRef_22, bigDescentPoly_24, ← ofList_mulList, ← ofList_mulList,
    ← ofList_addList]
  trans ofList ((203185311885692301754397024651294227136674097233607503558878
    + 82867652427420186029453175697202303416948485678251969555192 * 10 ^ 60
    + 1444308448068893277513286654492996 * 10 ^ 120) :: List.replicate 22 0)
  · exact congrArg ofList (by decide +kernel)
  · rw [ofList_cons_replicate_zero]
    norm_cast

theorem interlaces_and_nodup_24 :
    Interlaces (motzkinRef 22 : ℝ[X]) (bigDescentPoly 24) ∧
      (bigDescentPoly 24 : ℝ[X]).roots.Nodup ∧ (motzkinRef 22 : ℝ[X]).roots.Nodup ∧
      ∀ x, (motzkinRef 22 : ℝ[X]).IsRoot x → ¬ (bigDescentPoly 24 : ℝ[X]).IsRoot x :=
  ⟨interlaces_24, nodup_of_interlaces_of_bezout interlaces_24 bezout_24 (by norm_num)⟩

/-- The finite cases `3 ≤ n + 3 ≤ 24`: `M_(n+1)` interlaces `A_(n+3)`, both have simple
roots, and they have no common root. -/
theorem interlaces_and_nodup_of_le {n : ℕ} (hn : n ≤ 21) :
    Interlaces (motzkinRef (n + 1) : ℝ[X]) (bigDescentPoly (n + 3)) ∧
      (bigDescentPoly (n + 3) : ℝ[X]).roots.Nodup ∧
      (motzkinRef (n + 1) : ℝ[X]).roots.Nodup ∧
      ∀ x, (motzkinRef (n + 1) : ℝ[X]).IsRoot x →
        ¬ (bigDescentPoly (n + 3) : ℝ[X]).IsRoot x := by
  interval_cases n
  · exact interlaces_and_nodup_3
  · exact interlaces_and_nodup_4
  · exact interlaces_and_nodup_5
  · exact interlaces_and_nodup_6
  · exact interlaces_and_nodup_7
  · exact interlaces_and_nodup_8
  · exact interlaces_and_nodup_9
  · exact interlaces_and_nodup_10
  · exact interlaces_and_nodup_11
  · exact interlaces_and_nodup_12
  · exact interlaces_and_nodup_13
  · exact interlaces_and_nodup_14
  · exact interlaces_and_nodup_15
  · exact interlaces_and_nodup_16
  · exact interlaces_and_nodup_17
  · exact interlaces_and_nodup_18
  · exact interlaces_and_nodup_19
  · exact interlaces_and_nodup_20
  · exact interlaces_and_nodup_21
  · exact interlaces_and_nodup_22
  · exact interlaces_and_nodup_23
  · exact interlaces_and_nodup_24

end RealRooted.BigDescents321.SmallCases
