import RealRooted.BernsteinCone.Preserver
import RealRooted.Transforms.BrandenE.WeightedSum

/-!
# Interval-root preservation for Brändén's E transform

The ambient-degree Brändén basis images are exactly the Bernstein-basis
images of the ordered-Bell coefficient transform. Their checked interlacing
row therefore instantiates the generic Bernstein-image preserver criterion.
-/

open Polynomial

noncomputable section

namespace RealRooted

/-- The Brändén basis-image row is the generic Bernstein-image row for the
ordered-Bell coefficient transform. -/
theorem brandenBasisImageRow_eq_bernsteinBasisImageRow (n : ℕ) :
    brandenBasisImageRow n =
      bernsteinBasisImageRow (orderedBellPolynomial (R := ℝ)) n := by
  simp [brandenBasisImageRow, bernsteinBasisImageRow, brandenBasisImage,
    brandenBinomialBasis, brandenE, add_comm]

/-- Brändén's E transform sends a positive-leading split polynomial rooted
in `[-1, 0]` to a Pólya-frequency polynomial. -/
theorem brandenE_isPFPolynomial_of_roots_mem_Icc
    {p : ℝ[X]} (hp : p.Splits) (hlead : HasPosLeadingCoeff p)
    (hroots : ∀ r ∈ p.roots, r ∈ Set.Icc (-1 : ℝ) 0) :
    IsPFPolynomial (brandenE p) := by
  have hrow : IsInterlacingSeqNonneg
      (bernsteinBasisImageRow (orderedBellPolynomial (R := ℝ)) p.natDegree) := by
    rw [← brandenBasisImageRow_eq_bernsteinBasisImageRow]
    exact brandenBasisImageRow_isInterlacingSeqNonneg p.natDegree
  simpa [brandenE] using
    hrow.basisTransform_isPF_of_roots_mem_Icc hp hlead hroots

/-- Without choosing the sign of the input, Brändén's E transform sends a
split polynomial rooted in `[-1, 0]` either to zero or to a nonzero split
polynomial whose roots are all nonpositive. -/
theorem brandenE_eq_zero_or_splits_and_roots_nonpos
    {p : ℝ[X]} (hp : p.Splits)
    (hroots : ∀ r ∈ p.roots, r ∈ Set.Icc (-1 : ℝ) 0) :
    brandenE p = 0 ∨
      (brandenE p ≠ 0 ∧ (brandenE p).Splits ∧
        ∀ r ∈ (brandenE p).roots, r ≤ 0) := by
  have hrow : IsInterlacingSeqNonneg
      (bernsteinBasisImageRow (orderedBellPolynomial (R := ℝ)) p.natDegree) := by
    rw [← brandenBasisImageRow_eq_bernsteinBasisImageRow]
    exact brandenBasisImageRow_isInterlacingSeqNonneg p.natDegree
  simpa [brandenE] using
    hrow.basisTransform_eq_zero_or_splits_and_roots_nonpos hp hroots

/-- In every ambient degree, the closed nonnegative cone generated by the
in-range Brändén basis images consists of Pólya-frequency polynomials. -/
theorem brandenBasisWeightedSum_isPFPolynomial_of_le
    (n : ℕ) (s : Finset ℕ) (a : ℕ → ℝ)
    (hkn : ∀ k ∈ s, k ≤ n) (ha : ∀ k ∈ s, 0 ≤ a k) :
    IsPFPolynomial (brandenBasisWeightedSum n s a) := by
  classical
  let ws : List (ℝ × ℝ[X]) :=
    s.toList.map fun k ↦ (a k, brandenBasisImage n k)
  have hmem : ∀ ap ∈ ws, ap.2 ∈ brandenBasisImageRow n := by
    intro ap hap
    dsimp [ws] at hap
    rw [List.mem_map] at hap
    rcases hap with ⟨k, hk, rfl⟩
    rw [brandenBasisImageRow, List.mem_ofFn]
    have hks : k ∈ s := by simpa using hk
    have hk_le : k ≤ n := hkn k hks
    exact ⟨⟨k, by lia⟩, rfl⟩
  have hweights : ∀ ap ∈ ws, 0 ≤ ap.1 := by
    intro ap hap
    dsimp [ws] at hap
    rw [List.mem_map] at hap
    rcases hap with ⟨k, hk, rfl⟩
    exact ha k (by simpa using hk)
  have hpf :=
    (brandenBasisImageRow_isInterlacingSeqNonneg n).weightedSum_isPFPolynomial
      ws hmem hweights
  simpa [ws, weightedSum_eq_sum_map, brandenBasisWeightedSum] using hpf

end RealRooted
