import RealRooted.CommonInterleaver.FamilyUpgrade
import RealRooted.Transforms.BrandenE.ProperPosition

/-!
# Positive cones generated by Brändén basis images

Positive and nonnegative finite combinations of the ambient-degree basis
images remain real-rooted.  The zero-aware API also packages the whole closed
cone as Pólya-frequency polynomials.
-/

open Polynomial

noncomputable section

namespace RealRooted

universe u

variable {R : Type u}

section Semiring

variable [Semiring R]

/-- A finite weighted sum of ambient-degree Brändén basis images. -/
def brandenBasisWeightedSum (n : ℕ) (s : Finset ℕ) (a : ℕ → R) : R[X] :=
  ∑ k ∈ s, C (a k) * brandenBasisImage n k

/-- The corresponding weighted sum before applying `brandenE`. -/
def brandenBasisWeightedInput (n : ℕ) (s : Finset ℕ) (a : ℕ → R) : R[X] :=
  ∑ k ∈ s, C (a k) * brandenBinomialBasis n k

end Semiring

section CommSemiring

variable [CommSemiring R]

theorem brandenE_basisWeightedInput
    (n : ℕ) (s : Finset ℕ) (a : ℕ → R) :
    brandenE (brandenBasisWeightedInput n s a) =
      brandenBasisWeightedSum n s a := by
  rw [brandenBasisWeightedInput, brandenBasisWeightedSum, brandenE,
    Polynomial.basisTransform_finset_sum]
  apply Finset.sum_congr rfl
  intro k _
  rw [show C (a k) * brandenBinomialBasis n k =
      a k • brandenBinomialBasis n k by rw [Polynomial.smul_eq_C_mul],
    Polynomial.basisTransform_smul]
  rfl

end CommSemiring

section Real

/-- Nonnegative weights give a polynomial with nonnegative coefficients. -/
theorem brandenBasisWeightedSum_nonneg
    (n : ℕ) (s : Finset ℕ) (a : ℕ → ℝ)
    (ha : ∀ k ∈ s, 0 ≤ a k) :
    HasNonnegCoeffs (brandenBasisWeightedSum n s a) := by
  rw [brandenBasisWeightedSum]
  apply hasNonnegCoeffs_finsetSum
  intro k hk
  exact nonnegCoeffs_C_mul (ha k hk) (brandenBasisImage_nonneg n k)

/-- Strictly positive combinations of in-range basis images are nonzero and
split over the reals. -/
theorem brandenBasisWeightedSum_ne_zero_and_splits
    (n : ℕ) (s : Finset ℕ) (a : ℕ → ℝ)
    (hn : 3 ≤ n) (hs : s.Nonempty)
    (hkn : ∀ k ∈ s, k ≤ n) (ha : ∀ k ∈ s, 0 < a k) :
    brandenBasisWeightedSum n s a ≠ 0 ∧
      (brandenBasisWeightedSum n s a).Splits := by
  classical
  let fs : List ℝ[X] :=
    s.toList.map fun k => C (a k) * brandenBasisImage n k
  have hfs_sum : fs.sum = brandenBasisWeightedSum n s a := by
    simp [fs, brandenBasisWeightedSum]
  have hcommon : HasCommonLeftInterleaver fs := by
    refine ⟨brandenBasisImage n 0, ?_⟩
    intro p hp
    simp only [fs, Finset.mem_toList, List.mem_map] at hp
    rcases hp with ⟨k, hk, rfl⟩
    exact prec_C_mul_right
      (brandenBasisImage_first_prec n k hn (hkn k hk)) (ha k hk).ne'
  have hpos : ∀ p ∈ fs, HasPosLeadingCoeff p := by
    intro p hp
    simp only [fs, Finset.mem_toList, List.mem_map] at hp
    rcases hp with ⟨k, hk, rfl⟩
    exact hasPosLeadingCoeff_C_mul (ha k hk)
      (brandenBasisImage_degree_pos n k (hkn k hk)).2
  have hne : fs ≠ [] := by
    simpa [fs] using hs.ne_empty
  rw [← hfs_sum]
  exact isRealRooted_sum_of_commonLeftInterleaver hcommon hpos hne

theorem brandenBasisWeightedSum_splits
    (n : ℕ) (s : Finset ℕ) (a : ℕ → ℝ)
    (hn : 3 ≤ n) (hs : s.Nonempty)
    (hkn : ∀ k ∈ s, k ≤ n) (ha : ∀ k ∈ s, 0 < a k) :
    (brandenBasisWeightedSum n s a).Splits :=
  (brandenBasisWeightedSum_ne_zero_and_splits n s a hn hs hkn ha).2

/-- A nonnegative combination with at least one positive weight is nonzero
and split. -/
theorem brandenBasisWeightedSum_ne_zero_and_splits_of_nonneg
    (n : ℕ) (s : Finset ℕ) (a : ℕ → ℝ)
    (hn : 3 ≤ n) (hkn : ∀ k ∈ s, k ≤ n)
    (ha : ∀ k ∈ s, 0 ≤ a k)
    (hpos : ∃ k ∈ s, 0 < a k) :
    brandenBasisWeightedSum n s a ≠ 0 ∧
      (brandenBasisWeightedSum n s a).Splits := by
  classical
  let t := s.filter fun k => 0 < a k
  have ht : t.Nonempty := by
    rcases hpos with ⟨k, hks, hkpos⟩
    exact ⟨k, by simp [t, hks, hkpos]⟩
  have hsum : brandenBasisWeightedSum n s a =
      brandenBasisWeightedSum n t a := by
    rw [brandenBasisWeightedSum, brandenBasisWeightedSum]
    symm
    apply Finset.sum_subset
    · exact Finset.filter_subset _ _
    · intro k hks hkt
      have hk_nonpos : ¬0 < a k := by
        intro hkpos
        apply hkt
        exact Finset.mem_filter.mpr ⟨hks, hkpos⟩
      have hkzero : a k = 0 :=
        le_antisymm (le_of_not_gt hk_nonpos) (ha k hks)
      simp [hkzero]
  rw [hsum]
  apply brandenBasisWeightedSum_ne_zero_and_splits n t a hn ht
  · intro k hkt
    exact hkn k (Finset.filter_subset _ _ hkt)
  · intro k hkt
    exact (Finset.mem_filter.mp hkt).2

theorem brandenBasisWeightedSum_splits_of_nonneg
    (n : ℕ) (s : Finset ℕ) (a : ℕ → ℝ)
    (hn : 3 ≤ n) (hkn : ∀ k ∈ s, k ≤ n)
    (ha : ∀ k ∈ s, 0 ≤ a k)
    (hpos : ∃ k ∈ s, 0 < a k) :
    (brandenBasisWeightedSum n s a).Splits :=
  (brandenBasisWeightedSum_ne_zero_and_splits_of_nonneg
    n s a hn hkn ha hpos).2

/-- The first basis image weakly precedes every nonnegative combination. -/
theorem brandenBasisWeightedSum_prec0
    (n : ℕ) (s : Finset ℕ) (a : ℕ → ℝ)
    (hn : 3 ≤ n) (hkn : ∀ k ∈ s, k ≤ n)
    (ha : ∀ k ∈ s, 0 ≤ a k) :
    Prec0 (brandenBasisImage n 0) (brandenBasisWeightedSum n s a) := by
  rw [brandenBasisWeightedSum]
  apply prec0_finsetSum_left_of_nonneg
  · intro k hk
    exact prec0_C_mul_right_of_nonneg
      (brandenBasisImage_first_prec n k hn (hkn k hk)).toPrec0 (ha k hk)
  · intro k hk
    exact nonnegCoeffs_C_mul (ha k hk) (brandenBasisImage_nonneg n k)

/-- With at least one positive weight, the weak cone relation is strict. -/
theorem brandenBasisWeightedSum_prec
    (n : ℕ) (s : Finset ℕ) (a : ℕ → ℝ)
    (hn : 3 ≤ n) (hkn : ∀ k ∈ s, k ≤ n)
    (ha : ∀ k ∈ s, 0 ≤ a k)
    (hpos : ∃ k ∈ s, 0 < a k) :
    Prec (brandenBasisImage n 0) (brandenBasisWeightedSum n s a) := by
  apply (brandenBasisWeightedSum_prec0 n s a hn hkn ha).toPrec_of_ne
  · exact (brandenBasisImage_degree_pos n 0 (by lia)).2.ne_zero
  · exact (brandenBasisWeightedSum_ne_zero_and_splits_of_nonneg
      n s a hn hkn ha hpos).1

/-- The closed nonnegative cone generated by the in-range basis images
consists of Pólya-frequency polynomials, including the zero polynomial. -/
theorem brandenBasisWeightedSum_isPFPolynomial
    (n : ℕ) (s : Finset ℕ) (a : ℕ → ℝ)
    (hn : 3 ≤ n) (hkn : ∀ k ∈ s, k ≤ n)
    (ha : ∀ k ∈ s, 0 ≤ a k) :
    IsPFPolynomial (brandenBasisWeightedSum n s a) := by
  by_cases hpos : ∃ k ∈ s, 0 < a k
  · exact IsPFPolynomial.of_realRooted_nonneg
      (brandenBasisWeightedSum_nonneg n s a ha)
      (brandenBasisWeightedSum_splits_of_nonneg n s a hn hkn ha hpos)
  · have hzero : brandenBasisWeightedSum n s a = 0 := by
      rw [brandenBasisWeightedSum]
      apply Finset.sum_eq_zero
      intro k hk
      have hk_nonpos : ¬0 < a k := fun hkpos => hpos ⟨k, hk, hkpos⟩
      have hkzero : a k = 0 :=
        le_antisymm (le_of_not_gt hk_nonpos) (ha k hk)
      simp [hkzero]
    rw [hzero]
    exact IsPFPolynomial.zero

end Real

end RealRooted
