import RealRooted.Tactic.AllCombo
import RealRooted.Tactic.AffineDerivative
import RealRooted.Tactic.MaWang
import RealRooted.Tactic.CubicDiscriminant
import RealRooted.Tactic.CoefficientShape
import RealRooted.Tactic.CommonInterleaver.BasicRules
import RealRooted.Tactic.Derivative
import RealRooted.Tactic.EulerOperator
import RealRooted.Tactic.Favard
import RealRooted.Tactic.GammaRealRoots
import RealRooted.Tactic.Hadamard
import RealRooted.Tactic.HermiteBiehler
import RealRooted.Tactic.HermitePoulain
import RealRooted.Tactic.IteratedDerivativeShift
import RealRooted.Tactic.J1Chebyshev
import RealRooted.Tactic.J1Gap3Reciprocal
import RealRooted.Tactic.Kurtz
import RealRooted.Tactic.Linear
import RealRooted.Tactic.InterlacingSequence
import RealRooted.Tactic.LinearPowerFamily
import RealRooted.Tactic.LiuWang
import RealRooted.Tactic.LiuWangRecursion
import RealRooted.Tactic.Matrix
import RealRooted.Tactic.MagnitudeDominated
import RealRooted.Tactic.MultiplierSequence
import RealRooted.Tactic.OperatorPreservesInterlacing
import RealRooted.Tactic.PFPolynomial
import RealRooted.Tactic.PFBidiagonal
import RealRooted.Tactic.Product
import RealRooted.Tactic.PosCombo
import RealRooted.Tactic.Narayana
import RealRooted.Tactic.RootBounds
import RealRooted.Tactic.RootCount
import RealRooted.Tactic.SecondDerivative
import RealRooted.Tactic.StaircaseSum
import RealRooted.Tactic.SymmetricDecomposition
import RealRooted.Tactic.VeroneseSection
import RealRooted.Tactic.WeightedSum
import RealRooted.Tactic.Wagner
import RealRooted.Tactic.WagnerX
import RealRooted.Tactic.OEIS.Basic
import RealRooted.Tactic.OEIS.DerivativeLag
import RealRooted.Tactic.OEIS.PositiveLag
import RealRooted.Tactic.OEIS.NegativeLag
import RealRooted.Tactic.OEIS.ProductExit
import RealRooted.Tactic.OEIS.ProductFactor
import RealRooted.Tactic.OEIS.ProductLift
import RealRooted.Tactic.OEIS.ProductParity

/-!
# OEIS tactic wrapper stub

Planned user-facing dispatch:

```lean
rr_oeis ma_wang
rr_oeis favard
rr_oeis liu_wang
rr_oeis matrix
rr_favard using ...
rr_favard_const_unit using ...
rr_favard_const_row_sign_unit using ...
rr_favard_affine_param_den_auto using ...
rr_favard_affine_param_den_raw_auto using ...
rr_prec_C_mul_left_sequence using ...
rr_prec_C_mul_right_sequence using ...
rr_prec_C_mul_both_sequence using ...
rr_C_mul_realrooted_sequence using ...
rr_X_mul_realrooted_sequence using ...
rr_coeff_shape using ...
rr_fPolynomial_sequence_realrooted using ...
rr_of_fPolynomial_sequence_realrooted using ...
rr_fPolynomial_sequence_prec using ...
rr_of_fPolynomial_sequence_prec using ...
rr_fPolynomial_sequence_pos_combo using ...
rr_gamma_transform_sequence_realrooted_nonneg using ...
rr_gamma_transform_sequence_roots_nonpos_nonneg using ...
rr_gamma_transform_sequence_realrooted_nonpos using ...
rr_gamma_transform_sequence_backward using ...
rr_gamma_transform_sequence_backward_minimal using ...
rr_gamma_sequence_realrooted_iff using ...
rr_veronese_section_sequence_nonneg using ...
rr_veronese_section_sequence_pf_coeff using ...
rr_veronese_section_sequence_splits_pf using ...
rr_veronese_section_sequence_splits_nonneg using ...
rr_veronese_section_sequence_prec0 using ...
rr_veronese_section_sequence_prec using ...
rr_veronese_pair_sequence_prec0 using ...
rr_veronese_pair_sequence_prec using ...
rr_veronese_pair_fin_sequence_prec0 using ...
rr_veronese_pair_fin_sequence_prec using ...
rr_compatible_sequence_comm using ...
rr_compatible_sequence_comp_X_add_C using ...
rr_compatible_sequence_reflect using ...
rr_compatible_sequence_reflect_iff using ...
rr_compatible_sequence_derivative using ...
rr_compatible_sequence_left_realrooted using ...
rr_compatible_sequence_right_realrooted using ...
rr_compatible_sequence_right_degree_le_succ using ...
rr_compatible_sequence_degree_close using ...
rr_compatible_sequence_to_pos_combo using ...
rr_compatible_sequence_of_pos_combo using ...
rr_compatible_sequence_of_pos_combo_same_degree using ...
rr_compatible_sequence_of_pos_combo_succ_degree using ...
rr_compatible_sequence_of_common_left using ...
rr_compatible_sequence_of_common_right using ...
rr_pos_combo_sequence_comp_X_add_C using ...
rr_pairwise_compatible_sequence_of_common_left using ...
rr_pairwise_compatible_sequence_of_pairwise_common_left using ...
rr_pairwise_compatible_sequence_of_common_right using ...
rr_pairwise_compatible_sequence_of_pairwise_common_right using ...
rr_common_interleaver_sequence_of_pairwise using ...
rr_common_left_interleaver_sequence_of_pairwise using ...
rr_common_interleaver_sum_sequence_realrooted using ...
rr_common_left_interleaver_sum_sequence_realrooted using ...
rr_prec_affine_derivative_sequence using ...
rr_prec_affine_derivative_sequence_realrooted using ...
rr_prec_affine_derivative_nonneg_sequence using ...
rr_prec_affine_derivative_nonneg_sequence_realrooted using ...
rr_affine_deriv_coeff_sequence using ...
rr_affine_deriv_natDegree_sequence using ...
rr_affine_deriv_leadingCoeff_sequence using ...
rr_affine_deriv_ne_zero_sequence using ...
rr_all_combo_sequence_derivative using ...
rr_all_combo_sequence_to_pos_combo_sameDegree using ...
rr_derivative_sequence_prec using ...
rr_nonneg_coeffs_sequence_derivative using ...
rr_operator_all_combo_sequence using ...
rr_operator_prec0_sequence_up_to_order using ...
rr_pf_sequence_mul using ...
rr_pf_sequence_zero_or_splits using ...
rr_pos_combo_sequence_of_prec using ...
rr_pos_combo_sequence_add_realrooted using ...
rr_weighted_sum_sequence_left_prec using ...
rr_weighted_sum_sequence_right_prec using ...
rr_sum_sequence_left_prec using ...
rr_sum_sequence_right_prec using ...
rr_staircaseSum_sequence_prec using ...
rr_staircaseSum_sequence_realrooted using ...
rr_natDegree_add_C_mul_lt_sequence using ...
rr_leadingCoeff_add_C_mul_lt_sequence using ...
rr_exists_root_lt_succDegree_add_right_small_sequence using ...
rr_degreeIncreasing_local_lower_count_sequence using ...
rr_positiveParameter_local_lower_count_sequence using ...
rr_rightFamily_card_roots_gt_eq_local_lower_sequence using ...
rr_card_filter_gt_endpoint_eq_local_lower_sequence using ...
rr_closedSegment_not_isRoot_same_sign_sequence using ...
rr_rightFamily_eval_ne_zero_same_sign_sequence using ...
rr_exists_nonRoot_threshold_count_eq_sequence using ...
rr_exists_nonRoot_threshold_count_gt_eq_sequence using ...
rr_rootCount_diff_le_one_nonRoot_sequence using ...
rr_rootCount_abs_diff_le_one_nonRoot_sequence using ...
rr_rootCount_diff_le_one_nonRoot_isRoot_sequence using ...
rr_rootCountAbove_diff_le_one_nonRoot_sequence using ...
rr_rootCountAbove_diff_le_one_nonRoot_isRoot_sequence using ...
rr_rootCount_max_abs_diff_le_one_sequence using ...
rr_card_roots_filter_le_eq_no_isRoot_Ioc_sequence using ...
rr_card_roots_filter_gt_eq_no_isRoot_Ioc_sequence using ...
rr_card_roots_filter_Ioc_zero_no_isRoot_Ioc_sequence using ...
rr_card_roots_filter_all_eq_no_isRoot_Ioc_sequence using ...
rr_card_roots_filter_le_mono_sequence using ...
rr_card_roots_filter_gt_antitone_sequence using ...
rr_card_roots_filter_le_and_gt_mono_sequence using ...
rr_card_roots_filter_le_eq_no_isRoot_Icc_sequence using ...
rr_card_roots_filter_gt_eq_no_isRoot_Icc_sequence using ...
rr_card_roots_filter_Ioc_zero_no_isRoot_Icc_sequence using ...
rr_card_roots_filter_all_eq_no_isRoot_Icc_sequence using ...
rr_card_roots_filter_le_sub_eq_no_isRoot_Ioc_sequence using ...
rr_card_roots_filter_gt_sub_eq_no_isRoot_Ioc_sequence using ...
rr_card_roots_filter_le_bound_no_isRoot_Ioc_sequence using ...
rr_card_roots_filter_gt_bound_no_isRoot_Ioc_sequence using ...
rr_card_roots_filter_le_and_gt_bound_no_isRoot_Ioc_sequence using ...
rr_card_roots_filter_le_sub_eq_no_isRoot_Icc_sequence using ...
rr_card_roots_filter_gt_sub_eq_no_isRoot_Icc_sequence using ...
rr_card_roots_filter_le_bound_no_isRoot_Icc_sequence using ...
rr_card_roots_filter_gt_bound_no_isRoot_Icc_sequence using ...
rr_card_roots_filter_le_and_gt_bound_no_isRoot_Icc_sequence using ...
rr_left_card_roots_succDegree_sequence using ...
rr_right_card_roots_succDegree_sequence using ...
rr_left_ne_zero_card_roots_succDegree_sequence using ...
rr_right_ne_zero_card_roots_succDegree_sequence using ...
rr_rightFamily_sameDegree_gt_count_eq_sequence using ...
rr_rightFamily_zero_one_gt_count_eq_sequence using ...
rr_sameDegree_gt_count_eq_no_rightFamily_sequence using ...
rr_sameDegree_rootCountAbove_no_rightFamily_sequence using ...
rr_sameDegree_rootCountAbove_no_pos_crossing_sequence using ...
rr_sameDegree_rootCountAbove_pos_crossing_sequence using ...
rr_posCombo_sameDegree_rootCount_degree_le_two_sequence using ...
rr_posCombo_sameDegree_rootCountAbove_degree_le_two_sequence using ...
rr_sameDegree_rootCrossing_degree_le_one_sequence using ...
rr_posCombo_sameDegree_rootCrossing_degree_le_two_sequence using ...
rr_compatible_succDegree_rootCountAbove_le_two_sequence using ...
rr_posCombo_sameDegree_rootCount_degree_le_three using ...
rr_posCombo_sameDegree_rootCount_degree_le_three_sequence using ...
rr_posCombo_sameDegree_rootCountAbove_degree_le_three using ...
rr_posCombo_sameDegree_rootCountAbove_degree_le_three_sequence using ...
rr_posCombo_sameDegree_rootCrossing_degree_le_three using ...
rr_posCombo_sameDegree_rootCrossing_degree_le_three_sequence using ...
rr_posCombo_sameDegree_rootCount_cubicInterior_sequence using ...
rr_posCombo_sameDegree_rootCountAbove_cubicInterior_sequence using ...
rr_posCombo_sameDegree_rootCrossing_cubicInterior_sequence using ...
rr_theta_sequence_pf using ...
rr_thetaPlusOne_sequence_pf using ...
rr_iterateThetaPlusOne_sequence_pf using ...
rr_thetaPlusOne_sequence_prec0 using ...
rr_iterateThetaPlusOne_sequence_prec0 using ...
rr_TDeriv_sequence_splits using ...
rr_TDeriv_sequence_prec using ...
rr_iterateTDeriv_sequence_splits using ...
rr_iterateTDeriv_sequence_prec_succ using ...
rr_wagner_common_left_add_sequence using ...
rr_wagner_common_right_add_sequence using ...
rr_wagner_mulX_iff_sequence using ...
rr_hadamard_pf using ...
rr_hadamard_nonneg_realrooted using ...
rr_hadamard_nonneg_coeffs using ...
rr_hadamard_sequence_pf using ...
rr_hadamard_sequence_nonneg_realrooted using ...
rr_hadamard_sequence_nonneg_coeffs using ...
rr_hadamard_sequence_prec0 using ...
rr_schur_szego_sequence using ...
rr_schur_szego_sequence_splits using ...
rr_schur_szego_pf_factor_degree_le_two using ...
rr_schur_szego_pf_factor_degree_le_three_cubic using ...
rr_schur_szego_pf_factor_degree_le_three_num_left_degree using ...
rr_hermite_biehler_odd_even_hurwitz using ...
rr_hermite_biehler_odd_even_hurwitz_stable_sequence using ...
rr_hermite_poulain using ...
rr_hermite_poulain_sequence using ...
rr_jensen_sequence_nonneg using ...
rr_jensen_sequence_pf_of_finite_multiplier using ...
rr_jensen_sequence_pf_of_finite_pf_multiplier using ...
rr_finite_multiplier_sequence_mono using ...
rr_finite_multiplier_sequence_mul using ...
rr_finite_pf_multiplier_sequence_of_finite_multiplier using ...
rr_i2_derivative_lag_sequence using ... certificate := directHalfLine
rr_i2_derivative_lag_sequence using ... certificate := wagnerGap
rr_i2_derivative_lag_sequence_den_coeff using ... certificate := directHalfLine
rr_i2_derivative_lag_sequence_den using ... certificate := wagnerGap
rr_magnitude_dominated_sequence using ...
rr_e_positive_t_lag_sequence using ... certificate := currentX
rr_e_positive_t_lag_sequence using ... certificate := currentCX
rr_e_positive_t_lag_sequence using ... certificate := currentOneAddX
rr_e_positive_t_lag_sequence using ... certificate := plateauX
rr_e_positive_t_lag_sequence using ... certificate := xOneSubX
rr_e_positive_t_lag_sequence using ... certificate := xCSubCMulX
rr_e_positive_t_lag_sequence using ... certificate := cMulXCSubCMulX
rr_e_positive_t_lag_sequence using ... certificate := tR
rr_e_positive_t_lag_sequence using ... certificate := cTR
rr_e_positive_t_lag_sequence using ... certificate := cTRAuto
rr_g_negative_lag_sequence using ... certificate := negativeSquare
rr_g_negative_lag_sequence using ... certificate := negativeMonicQuadratic
rr_g_negative_lag_sequence using ... certificate := negativeQuadratic
rr_g_negative_lag_sequence using ... certificate := globalNonpos
rr_g_negative_lag_sequence_den_coeff using ... certificate := negativeSquare
rr_g_negative_lag_sequence_den_coeff using ... certificate := negativeQuadratic
rr_j1_factorable_sequence_realrooted using ... certificate := finiteLinearProduct
rr_j1_gap3_reciprocal_sequence_realrooted using ... certificate := modelRealRooted
rr_j1_gap3_reciprocal_sequence_realrooted using ... certificate := modelPF
rr_kurtz using ...
rr_kurtz_sequence using ...
rr_mw_plus_derivative_sequence using ...
rr_mw_plus_derivative_sequence_expanded_auto using ...
rr_narayana_polynomial_splits using ...
rr_narayana_polynomial_sequence_splits using ...
rr_root_nonpos_sequence using ...
rr_root_le_neg_shift_sequence using ...
rr_derivative_root_nonpos_sequence using ...
rr_sign_at_roots_sequence using ...
rr_sign_at_roots_sequence_with_factor using ...
rr_product_exit_sequence using ... certificate := identity
rr_product_exit_sequence using ... certificate := rootZero
rr_product_exit_sequence using ... certificate := auto
rr_product_exit_sequence using ... certificate := periodTwo
rr_product_factor_sequence using ... certificate := suppliedFactor
rr_product_factor_sequence using ... certificate := auto
rr_product_factor_sequence using ... certificate := affine
rr_product_factor_sequence using ... certificate := affineAuto
rr_product_factor_sequence using ... certificate := constFirstAffine
rr_product_factor_sequence using ... certificate := constFirstAffineAuto
rr_product_factor_sequence using ... certificate := xAddC
rr_product_factor_sequence using ... certificate := cAddX
rr_product_factor_sequence using ... certificate := rootZeroPow
rr_product_factor_sequence using ... certificate := xAddCPow
rr_product_factor_sequence using ... certificate := cAddXPow
rr_product_factor_sequence using ... certificate := scalar
rr_product_factor_sequence using ... certificate := scalarAuto
rr_product_factor_sequence using ... certificate := scalarPow
rr_product_factor_sequence using ... certificate := scalarPowAuto
rr_product_factor_sequence using ... certificate := affinePow
rr_product_factor_sequence using ... certificate := affinePowAuto
rr_product_factor_sequence using ... certificate := constFirstAffinePow
rr_product_factor_sequence using ... certificate := constFirstAffinePowAuto
rr_product_formula_sequence using ... certificate := finiteLinearProduct
rr_product_formula_sequence using ... certificate := scalarFiniteLinearProduct
rr_product_parity_sequence using ... certificate := scalarThenFactor
rr_product_parity_sequence using ... certificate := scalarThenFactorAuto
rr_product_parity_sequence using ... certificate := scalarThenXAddC
rr_product_parity_sequence using ... certificate := scalarThenXAddCAuto
rr_product_parity_sequence using ... certificate := scalarThenCAddX
rr_product_parity_sequence using ... certificate := scalarThenCAddXAuto
rr_product_parity_sequence using ... certificate := scalarThenRootZeroPow
rr_product_parity_sequence using ... certificate := scalarThenRootZeroPowAuto
rr_product_parity_sequence using ... certificate := scalarThenXAddCPow
rr_product_parity_sequence using ... certificate := scalarThenXAddCPowAuto
rr_product_parity_sequence using ... certificate := scalarThenCAddXPow
rr_product_parity_sequence using ... certificate := scalarThenCAddXPowAuto
rr_product_parity_lift_sequence using ... certificate := scalarXOdd
rr_endpoint_pair_sequence using ... certificate := sumThenX
rr_endpoint_pair_sequence_realrooted using ... certificate := sumThenX
rr_endpoint_pair_sequence using ... certificate := xThenSum
rr_endpoint_pair_sequence_realrooted using ... certificate := xThenSum
rr_endpoint_pair_lift_sequence using ... certificate := sumThenX
rr_endpoint_pair_lift_sequence using ... certificate := xThenSum
rr_endpoint_pair_lift_sequence using ... certificate := xThenSumSwapped
rr_product_lift_sequence using ... certificate := suppliedFactor
rr_product_lift_sequence using ... certificate := auto
rr_product_lift_sequence using ... certificate := rootZero
rr_product_lift_sequence using ... certificate := rootZeroPow
rr_product_lift_sequence using ... certificate := xAddC
rr_product_lift_sequence using ... certificate := cAddX
rr_product_lift_sequence using ... certificate := fixedXAddCPow
rr_product_lift_sequence using ... certificate := rowXAddCPow
rr_product_lift_sequence using ... certificate := cAddXPow
rr_product_lift_sequence using ... certificate := scalar
rr_product_lift_sequence using ... certificate := scalarAuto
rr_product_lift_sequence using ... certificate := scalarPow
rr_product_lift_sequence using ... certificate := scalarPowAuto
rr_product_lift_sequence using ... certificate := affine
rr_product_lift_sequence using ... certificate := affineAuto
rr_product_lift_sequence using ... certificate := constFirstAffine
rr_product_lift_sequence using ... certificate := constFirstAffineAuto
rr_product_lift_sequence using ... certificate := affinePow
rr_product_lift_sequence using ... certificate := affinePowAuto
rr_product_lift_sequence using ... certificate := constFirstAffinePow
rr_product_lift_sequence using ... certificate := constFirstAffinePowAuto
```

This should remain a thin wrapper over explicit family tactics.  Generated
OEIS files should expose the recurrence and certificate lemmas, then call the
appropriate engine-specific tactic.
-/
