#!/usr/bin/env python3
"""Generate the finite cases 3 <= n <= 24 of the 321 big-descent theorem (issue #1143).

Writes two Lean modules under RealRooted/CombinatorialExamples/BigDescents321/SmallCases/:

* `Literals.lean`: `motzkinRef k = ofList [...]` (k <= 22) and
  `bigDescentPoly n = ofList [...]` (n <= 24) over the reals.  Each is checked against its
  convolution recurrence by kernel computation on integer lists (`decide +kernel`).
* `Certificates.lean`: for each n, `Interlaces (M_(n-2)) (A_n)` by `rr_interlaces_explicit`
  and a Bezout identity `U * A_n + V * M_(n-2) = D` with integer data, again checked on
  integer lists.  Together they give simple roots and no common root.

Lean checks every identity; this script only produces the data.
Requires sympy.  Usage: python3 scripts/gen_big_descents_small_cases.py
"""
from functools import reduce
from math import comb, lcm
from pathlib import Path

import sympy as sp

N = 24
WIDTH = 100
ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "RealRooted/CombinatorialExamples/BigDescents321/SmallCases"
t = sp.Symbol("t")

HEADER = "/-\nGenerated by scripts/gen_big_descents_small_cases.py; do not edit by hand.\n-/\n"


def catalan(a):
    return comb(2 * a, a) // (a + 1)


def motzkin(k):
    return [comb(k, 2 * a) * catalan(a) * 2 ** (k - 2 * a) for a in range(k // 2 + 1)]


def poly_mul(p, q):
    r = [0] * (len(p) + len(q) - 1)
    for i, a in enumerate(p):
        for j, b in enumerate(q):
            r[i + j] += a * b
    return r


def poly_add(p, q):
    n = max(len(p), len(q))
    return [(p[i] if i < len(p) else 0) + (q[i] if i < len(q) else 0) for i in range(n)]


def first_return(j):
    return [1] if j in (1, 2) else [0] + motzkin(j - 2)


def big_descent(n_max):
    rows = [[1]]
    for n in range(1, n_max + 1):
        s = [0]
        for j in range(1, n + 1):
            s = poly_add(s, poly_mul(first_return(j), rows[n - j]))
        rows.append(s)
    return rows


def integer(c):
    """An integer term; long values are split as `d0 + d1 * 10 ^ 60 + ...`."""
    if len(str(abs(c))) <= 60:
        return str(c)
    sign = -1 if c < 0 else 1
    c, j, parts = abs(c), 0, []
    while c:
        c, d = divmod(c, 10 ** 60)
        if d:
            parts.append(str(sign * d) + (f" * 10 ^ {60 * j}" if j else ""))
        j += 1
    return "(" + " + ".join(parts) + ")"


def wrap_list(head, items, indent, tail):
    """`head[i0, i1, ...]tail`, wrapped at WIDTH; items may break at ` + `."""
    tokens = []
    for k, item in enumerate(items):
        sep = "," if k + 1 < len(items) else "]"
        pieces = item.split(" + ")
        for m, piece in enumerate(pieces):
            tokens.append(("" if m == 0 else "+ ") + piece + (sep if m + 1 == len(pieces) else ""))
    lines, cur = [], head + "["
    for tok in tokens:
        piece = tok if cur.endswith("[") else " " + tok
        if len(cur) + len(piece) > WIDTH:
            lines.append(cur)
            cur = " " * indent + tok
        else:
            cur += piece
    if len(cur) + len(tail) > WIDTH:
        lines.append(cur)
        cur = " " * indent + tail.strip()
    else:
        cur += tail
    lines.append(cur)
    return "\n".join(lines)


def wrap_sum(head, expr, indent, tail):
    """`head expr tail` with `expr` broken at ` + ` to fit WIDTH."""
    pieces = expr.split(" + ")
    lines, cur = [], head + pieces[0]
    for piece in pieces[1:]:
        if len(cur) + len(piece) + 3 > WIDTH:
            lines.append(cur)
            cur = " " * indent + "+ " + piece
        else:
            cur += " + " + piece
    if len(cur) + len(tail) > WIDTH:
        lines.append(cur)
        cur = " " * indent + tail.strip()
    else:
        cur += tail
    lines.append(cur)
    return "\n".join(lines)


def ofl(head, coeffs, tail, indent=4):
    return wrap_list(head + "ofList ", [integer(c) for c in coeffs], indent, tail)


def simp_only(items, indent="  "):
    lines, cur = [], indent + "simp only ["
    for k, item in enumerate(items):
        piece = item if k == 0 else f", {item}"
        if len(cur) + len(piece) + 1 > WIDTH:
            lines.append(cur + ",")
            cur = indent + "  " + item
        else:
            cur += piece
    lines.append(cur + "]")
    return "\n".join(lines)


def literals(rows):
    out = [HEADER, """import RealRooted.CombinatorialExamples.BigDescents321.Basic
import RealRooted.CombinatorialExamples.BigDescents321.SmallCases.ListPoly
import Mathlib.Basic.Real.Basic

/-!
# Literal forms of the small big-descent polynomials

The coefficient lists of `M_k = motzkinRef k` for `k ≤ 22` and of `A_n = bigDescentPoly n`
for `n ≤ 24` over `ℝ`. Each is derived from its convolution recurrence, with the polynomial
products checked as integer-list computations by the kernel.
-/

open Polynomial

namespace RealRooted.BigDescents321.SmallCases
"""]
    out.append("""
theorem motzkinRef_0 : (motzkinRef 0 : ℝ[X]) = ofList [1] := by
  simp [ofList_singleton]

theorem motzkinRef_1 : (motzkinRef 1 : ℝ[X]) = ofList [2] := by
  simp [two_eq_ofList]
""")
    for k in range(2, N - 1):
        items = ["Finset.sum_range_succ", "Finset.sum_range_zero"]
        items += (["Nat.reduceAdd"] if k > 2 else []) + ["Nat.reduceSub", "zero_add",
                                                         "two_eq_ofList"]
        items += [f"motzkinRef_{i}" for i in range(k)]
        out.append("\n" + ofl(f"theorem motzkinRef_{k} : (motzkinRef {k} : ℝ[X]) = ",
                              motzkin(k), " := by") + "\n  rw [motzkinRef_add_two]\n" +
                   simp_only(items) +
                   "\n  simp only [← ofList_zero_cons, ← ofList_mulList, ← ofList_addList]"
                   "\n  exact congrArg ofList (by decide +kernel)\n")
    out.append("""
theorem bigDescentPoly_0 : (bigDescentPoly 0 : ℝ[X]) = ofList [1] := by
  simp [ofList_singleton]

theorem bigDescentPoly_1 : (bigDescentPoly 1 : ℝ[X]) = ofList [1] := by
  simp [ofList_singleton, bigDescentPoly_one]

theorem bigDescentPoly_2 : (bigDescentPoly 2 : ℝ[X]) = ofList [2] := by
  simp [ofList_singleton, bigDescentPoly_two, map_ofNat]
""")
    for n in range(3, N + 1):
        items = ["Finset.sum_range_succ", "Finset.sum_range_zero", "Nat.reduceAdd",
                 "Nat.reduceSub", "zero_add", "firstReturn_one", "firstReturn_two",
                 "firstReturn_add_three", "one_mul"]
        items += [f"motzkinRef_{k}" for k in range(1, n - 1)]
        items += [f"bigDescentPoly_{m}" for m in range(n)]
        out.append("\n" + ofl(f"theorem bigDescentPoly_{n} : (bigDescentPoly {n} : ℝ[X]) = ",
                              rows[n], " := by") + "\n  rw [bigDescentPoly_succ]\n" +
                   simp_only(items) +
                   "\n  simp only [← ofList_zero_cons, ← ofList_mulList, ← ofList_addList]"
                   "\n  exact congrArg ofList (by decide +kernel)\n")
    out.append("\nend RealRooted.BigDescents321.SmallCases\n")
    return "".join(out)


def to_poly(coeffs):
    return sp.Poly(sum(c * t ** i for i, c in enumerate(coeffs)), t)


def bezout(a, m):
    u, v, g = sp.gcdex(a, m)
    assert g.as_expr() == 1
    den = reduce(lcm, [sp.Rational(c).q for c in u.all_coeffs() + v.all_coeffs()], 1)
    U, V = u * den, v * den
    cont = reduce(sp.gcd, [sp.Integer(c) for c in U.all_coeffs() + V.all_coeffs()] + [den])
    U, V, D = U.exquo_ground(cont), V.exquo_ground(cont), den // cont
    assert (U * a + V * m).as_expr() == D
    return ([int(c) for c in U.all_coeffs()[::-1]], [int(c) for c in V.all_coeffs()[::-1]],
            int(D))


def certificates(rows):
    out = [HEADER, """import RealRooted.CombinatorialExamples.BigDescents321.SmallCases.Literals
import RealRooted.Basic.PolynomialFacts
import RealRooted.Bezoutian.Successor
import RealRooted.Tactic.InterlacesExplicit

/-!
# Finite interlacing certificates for the small big-descent polynomials

For `3 ≤ n ≤ 24`, `M_(n-2)` interlaces `A_n`, by the exact Euclid chain of
`rr_interlaces_explicit`. An integer Bezout identity `U A_n + V M_(n-2) = D`, checked as an
integer-list computation, shows that the two polynomials have no common root, so both have
simple roots.
-/

open Polynomial

namespace RealRooted.BigDescents321.SmallCases

/-- Interlacing together with a Bezout identity `U * A + V * M = D`, `D ≠ 0`, gives simple
roots of both polynomials and no common root. -/
theorem nodup_of_interlaces_of_bezout {A M U V : ℝ[X]} {D : ℝ} (hI : Interlaces M A)
    (hB : U * A + V * M = C D) (hD' : D ≠ 0) :
    A.roots.Nodup ∧ M.roots.Nodup ∧ ∀ x, M.IsRoot x → ¬ A.IsRoot x := by
  have hcop : IsCoprime M A :=
    ⟨C D⁻¹ * V, C D⁻¹ * U, by
      rw [mul_assoc, mul_assoc, ← mul_add, add_comm, hB, ← C_mul, inv_mul_cancel₀ hD', C_1]⟩
  have hdisj : ∀ x, A.IsRoot x → ¬ M.IsRoot x := fun x hA hM ↦ hcop.not_isRoot_right hM hA
  exact ⟨(hI.roots_nodup_of_disjoint hdisj).1, (hI.roots_nodup_of_disjoint hdisj).2,
    fun x hM hA ↦ hdisj x hA hM⟩
"""]
    for n in range(3, N + 1):
        k = n - 2
        U, V, D = bezout(to_poly(rows[n]), to_poly(motzkin(k)))
        # the exact list `addList (mulList U A) (mulList V M)` computes, trailing zeros included
        length = max(len(U) + len(rows[n]) - 1, len(V) + len(motzkin(k)) - 1)
        zeros = length - 1
        if n == 3:
            lits = "rw [motzkinRef_one, bigDescentPoly_three]"
        else:
            polys = (motzkin(k), rows[n])
            items = ["ofList_cons", "ofList_nil", "Int.cast_ofNat"]
            if any(c == 1 for q in polys for c in q):
                items += ["Int.cast_one"]
            items += ["map_ofNat"]
            if any(c == 1 for q in polys for c in q):
                items += ["map_one"]
            items += ["mul_zero", "add_zero"]
            if any(q[-1] == 1 for q in polys):
                items += ["mul_one"]
            lits = f"rw [motzkinRef_{k}, bigDescentPoly_{n}]\n" + simp_only(items)
        out.append(f"""
private theorem interlaces_{n} :
    Interlaces (motzkinRef {k} : ℝ[X]) (bigDescentPoly {n}) := by
  {lits.lstrip()}
  rr_interlaces_explicit

private theorem bezout_{n} :
{ofl("    ", U, f" * (bigDescentPoly {n} : ℝ[X])", 6)}
{ofl("      + ", V, f" * motzkinRef {k}", 6)}
{wrap_sum("      = C (", integer(D), 8, " : ℝ) := by")}
  rw [motzkinRef_{k}, bigDescentPoly_{n}, ← ofList_mulList, ← ofList_mulList,
    ← ofList_addList]
{wrap_sum("  trans ofList (", integer(D), 4, f" :: List.replicate {zeros} 0)")}
  · exact congrArg ofList (by decide +kernel)
  · rw [ofList_cons_replicate_zero]
    norm_cast

theorem interlaces_and_nodup_{n} :
    Interlaces (motzkinRef {k} : ℝ[X]) (bigDescentPoly {n}) ∧
      (bigDescentPoly {n} : ℝ[X]).roots.Nodup ∧ (motzkinRef {k} : ℝ[X]).roots.Nodup ∧
      ∀ x, (motzkinRef {k} : ℝ[X]).IsRoot x → ¬ (bigDescentPoly {n} : ℝ[X]).IsRoot x :=
  ⟨interlaces_{n}, nodup_of_interlaces_of_bezout interlaces_{n} bezout_{n} (by norm_num)⟩
""")
    out.append("""
/-- The finite cases `3 ≤ n + 3 ≤ 24`: `M_(n+1)` interlaces `A_(n+3)`, both have simple
roots, and they have no common root. -/
theorem interlaces_and_nodup_of_le {n : ℕ} (hn : n ≤ 21) :
    Interlaces (motzkinRef (n + 1) : ℝ[X]) (bigDescentPoly (n + 3)) ∧
      (bigDescentPoly (n + 3) : ℝ[X]).roots.Nodup ∧
      (motzkinRef (n + 1) : ℝ[X]).roots.Nodup ∧
      ∀ x, (motzkinRef (n + 1) : ℝ[X]).IsRoot x →
        ¬ (bigDescentPoly (n + 3) : ℝ[X]).IsRoot x := by
  interval_cases n
""")
    for n in range(3, N + 1):
        out.append(f"  · exact interlaces_and_nodup_{n}\n")
    out.append("\nend RealRooted.BigDescents321.SmallCases\n")
    return "".join(out)


def main():
    rows = big_descent(N)
    OUT.mkdir(parents=True, exist_ok=True)
    for name, text in (("Literals.lean", literals(rows)),
                       ("Certificates.lean", certificates(rows))):
        (OUT / name).write_text(text)
        long = [i + 1 for i, line in enumerate(text.splitlines()) if len(line) > WIDTH]
        print(name, len(text.splitlines()), "lines", "long lines:", long[:5])


if __name__ == "__main__":
    main()
