import RealRooted.CombinatorialExamples.SturmDerangementsExc
import RealRooted.CombinatorialExamples.Eulerian
import RealRooted.CombinatorialExamples.Narayana
import RealRooted.CombinatorialExamples.Touchard
import RealRooted.CombinatorialExamples.SingletonFreeSetPartitions
import RealRooted.CombinatorialExamples.TypeBEulerian
import RealRooted.CombinatorialExamples.Simsun
import RealRooted.CombinatorialExamples.Motzkin
import RealRooted.CombinatorialExamples.OneDescentGamma
import RealRooted.CombinatorialExamples.ColoredSetPartitions
import RealRooted.CombinatorialExamples.StirlingPermutations

/-!
# Combinatorial Examples

Collected polynomial families used as regression examples for real-rootedness,
interlacing, and Sturm-sequence APIs.
-/
