import Mathlib.Algebra.Polynomial.Splits
import Mathlib.Algebra.Polynomial.Div
import Mathlib.Algebra.Polynomial.SpecificDegree
import Mathlib.Algebra.QuadraticDiscriminant
import Mathlib.Analysis.Complex.Polynomial.Basic
import Mathlib.Analysis.Real.Sqrt
import RealRooted.CubicNewton

/-!
# The discriminant criterion for a real cubic to split

A real cubic `p = a X^3 + b X^2 + c X + d` (`a = p.coeff 3`, `b = p.coeff 2`,
`c = p.coeff 1`, `d = p.coeff 0`) splits over `ℝ` (all three roots are real) as
soon as its coefficient discriminant

`Δ = 18 a b c d - 4 b^3 d + b^2 c^2 - 4 a c^3 - 27 a^2 d^2`

is nonnegative.

The proof is elementary and avoids the complex numbers entirely.  Any real
cubic has at least one real root `r` (a degree-three polynomial with no root
would be irreducible, contradicting that irreducible real polynomials have
degree at most two).  Writing `p = (X - r) q` with `q` a real quadratic, a
direct algebraic identity gives

`Δ = (q.eval r)^2 * discrim (q.coeff 2) (q.coeff 1) (q.coeff 0)`,

so `Δ ≥ 0` forces the discriminant of the cofactor `q` to be nonnegative
whenever `q.eval r ≠ 0`; and if `q.eval r = 0` then `r` is already a root of
`q`.  Either way `q` splits, hence so does `p = (X - r) q`.

Here `Polynomial.Splits f` is the self-splitting predicate of
`Mathlib.Algebra.Polynomial.Splits` (`f` lies in the submonoid generated by the
constants and the linear polynomials), which for a nonzero real polynomial is
equivalent to having as many roots (with multiplicity) as its degree.
-/

open Polynomial

noncomputable section

namespace RealRooted

/-- The coefficient discriminant of a cubic `a X^3 + b X^2 + c X + d`, with
`a = p.coeff 3`, `b = p.coeff 2`, `c = p.coeff 1`, `d = p.coeff 0`. -/
def cubicDiscr (p : ℝ[X]) : ℝ :=
  18 * p.coeff 3 * p.coeff 2 * p.coeff 1 * p.coeff 0
    - 4 * p.coeff 2 ^ 3 * p.coeff 0
    + p.coeff 2 ^ 2 * p.coeff 1 ^ 2
    - 4 * p.coeff 3 * p.coeff 1 ^ 3
    - 27 * p.coeff 3 ^ 2 * p.coeff 0 ^ 2

/-- The coefficient discriminant `cubicDiscr` is homogeneous of degree four in the
coefficients, so scaling by a constant `C k` multiplies it by `k ^ 4`. -/
theorem cubicDiscr_C_mul (k : ℝ) (p : ℝ[X]) :
    cubicDiscr (C k * p) = k ^ 4 * cubicDiscr p := by
  unfold cubicDiscr
  simp only [coeff_C_mul]
  ring

/-- Expansion of a monic product of three linear factors. -/
theorem prod_three_X_sub_C_expand (a b c : ℝ) :
    (X - C a) * (X - C b) * (X - C c)
      = X ^ 3 - C (a + b + c) * X ^ 2 + C (a * b + b * c + c * a) * X
          - C (a * b * c) := by
  simp only [C_add, C_mul]
  ring

/-- The coefficient discriminant of a monic split cubic equals the square of the
product of the pairwise differences of its roots. -/
theorem cubicDiscr_prod_three_X_sub_C (a b c : ℝ) :
    cubicDiscr ((X - C a) * (X - C b) * (X - C c))
      = ((a - b) * (b - c) * (a - c)) ^ 2 := by
  rw [prod_three_X_sub_C_expand]
  unfold cubicDiscr
  simp only [coeff_sub, coeff_add, coeff_C_mul, coeff_X_pow, coeff_C,
    coeff_X, mul_ite, mul_one, mul_zero]
  norm_num
  ring

/-- Every real cubic has a real root: a degree-three real polynomial without a
root would be irreducible, contradicting that irreducible real polynomials have
degree at most two. -/
lemma cubic_exists_isRoot {p : ℝ[X]} (hdeg : p.natDegree = 3) :
    ∃ r : ℝ, p.IsRoot r := by
  by_contra h
  have hnot : ∀ x : ℝ, ¬ p.IsRoot x := fun x hx => h ⟨x, hx⟩
  have hirr : Irreducible p :=
    irreducible_of_degree_le_three_of_not_isRoot (by rw [hdeg]; decide) hnot
  have hle : p.natDegree ≤ 2 := Irreducible.natDegree_le_two hirr
  rw [hdeg] at hle
  exact absurd hle (by decide)

/-- Pure algebraic identity underlying the discriminant criterion.  With
`A, B, D` the coefficients of a quadratic `q = A X^2 + B X + D` and `r` a scalar,
the coefficient discriminant of `(X - r) q` equals `(q.eval r)^2` times the
quadratic discriminant `B^2 - 4 A D`. -/
lemma cubicDiscr_factor_identity (A B D r : ℝ) :
    18 * A * (B - r * A) * (D - r * B) * (-(r * D))
        - 4 * (B - r * A) ^ 3 * (-(r * D))
        + (B - r * A) ^ 2 * (D - r * B) ^ 2
        - 4 * A * (D - r * B) ^ 3
        - 27 * A ^ 2 * (-(r * D)) ^ 2
      = (A * r ^ 2 + B * r + D) ^ 2 * (B ^ 2 - 4 * A * D) := by
  ring

/-- Evaluation of a quadratic `q` at a point in terms of its coefficients. -/
lemma eval_of_natDegree_two {q : ℝ[X]} (r : ℝ) (hqdeg : q.natDegree = 2) :
    q.eval r = q.coeff 2 * r ^ 2 + q.coeff 1 * r + q.coeff 0 := by
  rw [eval_eq_sum_range, hqdeg]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero, pow_zero, pow_one,
    zero_add, mul_one]
  ring

/-- The four coefficients of `(X - C r) * q` in terms of the coefficients of a
quadratic `q`. -/
lemma coeff_X_sub_C_mul_of_natDegree_two {q : ℝ[X]} (r : ℝ) (hqdeg : q.natDegree = 2) :
    ((X - C r) * q).coeff 3 = q.coeff 2 ∧
      ((X - C r) * q).coeff 2 = q.coeff 1 - r * q.coeff 2 ∧
      ((X - C r) * q).coeff 1 = q.coeff 0 - r * q.coeff 1 ∧
      ((X - C r) * q).coeff 0 = -(r * q.coeff 0) := by
  have hq3 : q.coeff 3 = 0 := coeff_eq_zero_of_natDegree_lt (by rw [hqdeg]; decide)
  refine ⟨?_, ?_, ?_, ?_⟩
  · rw [show (3 : ℕ) = 2 + 1 from rfl, coeff_X_sub_C_mul, hq3, mul_zero, sub_zero]
    simp
  · rw [show (2 : ℕ) = 1 + 1 from rfl, coeff_X_sub_C_mul]
    simp
  · rw [show (1 : ℕ) = 0 + 1 from rfl, coeff_X_sub_C_mul]
    simp
  · rw [sub_mul, coeff_sub, coeff_C_mul, coeff_X_mul_zero, zero_sub]

/-- Discriminant factorisation for a cubic given as `(X - C r) * q` with `q` a
real quadratic. -/
lemma cubicDiscr_eq_of_factor {q : ℝ[X]} {r : ℝ} (hqdeg : q.natDegree = 2) :
    cubicDiscr ((X - C r) * q)
      = (q.eval r) ^ 2 * discrim (q.coeff 2) (q.coeff 1) (q.coeff 0) := by
  obtain ⟨h3, h2, h1, h0⟩ := coeff_X_sub_C_mul_of_natDegree_two r hqdeg
  rw [eval_of_natDegree_two r hqdeg]
  unfold cubicDiscr discrim
  rw [h3, h2, h1, h0]
  ring

/-- A real quadratic with nonnegative discriminant splits. -/
lemma quadratic_splits_of_discrim_nonneg {q : ℝ[X]} (hqdeg : q.natDegree = 2)
    (hdisc : 0 ≤ discrim (q.coeff 2) (q.coeff 1) (q.coeff 0)) : q.Splits := by
  have hq_ne : q ≠ 0 := by
    intro h; rw [h, natDegree_zero] at hqdeg; exact absurd hqdeg (by decide)
  have hc2 : q.coeff 2 ≠ 0 := by
    have hlc : q.leadingCoeff ≠ 0 := leadingCoeff_ne_zero.mpr hq_ne
    rwa [leadingCoeff, hqdeg] at hlc
  obtain ⟨x, hx⟩ := exists_quadratic_eq_zero hc2
    ⟨Real.sqrt (discrim (q.coeff 2) (q.coeff 1) (q.coeff 0)),
      (Real.mul_self_sqrt hdisc).symm⟩
  have hroot : q.eval x = 0 := by
    rw [eval_of_natDegree_two x hqdeg]; linear_combination hx
  exact Splits.of_natDegree_eq_two hqdeg hroot

/-- **Discriminant criterion for real cubics.**  A real polynomial of
`natDegree` three with nonnegative coefficient discriminant splits over `ℝ`. -/
theorem splits_of_cubicDiscr_nonneg {p : ℝ[X]} (hdeg : p.natDegree = 3)
    (hdisc : 0 ≤ cubicDiscr p) : p.Splits := by
  obtain ⟨r, hr⟩ := cubic_exists_isRoot hdeg
  have hfact : (X - C r) * (p /ₘ (X - C r)) = p := mul_divByMonic_eq_iff_isRoot.mpr hr
  set q := p /ₘ (X - C r) with hq
  have hqdeg : q.natDegree = 2 := by
    rw [hq, natDegree_divByMonic p (monic_X_sub_C r), hdeg, natDegree_X_sub_C]
  have hsplit : q.Splits := by
    by_cases hroot : q.IsRoot r
    · exact Splits.of_natDegree_eq_two hqdeg hroot
    · have hkey : cubicDiscr p
          = (q.eval r) ^ 2 * discrim (q.coeff 2) (q.coeff 1) (q.coeff 0) := by
        rw [← hfact]; exact cubicDiscr_eq_of_factor hqdeg
      have hne : q.eval r ≠ 0 := hroot
      have hsq : 0 < (q.eval r) ^ 2 :=
        (sq_nonneg _).lt_of_ne (Ne.symm (pow_ne_zero 2 hne))
      have hdisc' : 0 ≤ discrim (q.coeff 2) (q.coeff 1) (q.coeff 0) :=
        (mul_nonneg_iff_of_pos_left hsq).mp (hkey ▸ hdisc)
      exact quadratic_splits_of_discrim_nonneg hqdeg hdisc'
  rw [← hfact, splits_X_sub_C_mul_iff]
  exact hsplit

/-- If `p` has degree exactly two, then its cubic discriminant is the square of
its quadratic leading coefficient times its quadratic discriminant. -/
lemma cubicDiscr_eq_coeff_two_sq_mul_discrim_of_natDegree_two
    {p : ℝ[X]} (hdeg : p.natDegree = 2) :
    cubicDiscr p =
      p.coeff 2 ^ 2 * discrim (p.coeff 2) (p.coeff 1) (p.coeff 0) := by
  have hc3 : p.coeff 3 = 0 :=
    coeff_eq_zero_of_natDegree_lt (by rw [hdeg]; norm_num)
  unfold cubicDiscr discrim
  rw [hc3]
  ring

/-- **Discriminant criterion through degree three.**  A real polynomial of
`natDegree` at most three with nonnegative cubic coefficient discriminant splits
over `ℝ`.  In degree two, this reduces to the usual quadratic discriminant
because the cubic discriminant is the square of the quadratic leading
coefficient times the quadratic discriminant. -/
theorem splits_of_natDegree_le_three_cubicDiscr_nonneg
    {p : ℝ[X]} (hdeg : p.natDegree ≤ 3) (hdisc : 0 ≤ cubicDiscr p) :
    p.Splits := by
  by_cases h3 : p.natDegree = 3
  · exact splits_of_cubicDiscr_nonneg h3 hdisc
  have hle2 : p.natDegree ≤ 2 :=
    Nat.lt_succ_iff.mp (lt_of_le_of_ne hdeg h3)
  by_cases h2 : p.natDegree = 2
  · have hkey := cubicDiscr_eq_coeff_two_sq_mul_discrim_of_natDegree_two h2
    have hc2_ne : p.coeff 2 ≠ 0 := by
      have hp_ne : p ≠ 0 := by
        intro hp
        rw [hp, natDegree_zero] at h2
        norm_num at h2
      have hlc : p.leadingCoeff ≠ 0 := leadingCoeff_ne_zero.mpr hp_ne
      rwa [leadingCoeff, h2] at hlc
    have hsquare : 0 < p.coeff 2 ^ 2 :=
      (sq_nonneg _).lt_of_ne (Ne.symm (pow_ne_zero 2 hc2_ne))
    have hquad : 0 ≤ discrim (p.coeff 2) (p.coeff 1) (p.coeff 0) :=
      (mul_nonneg_iff_of_pos_left hsquare).mp (hkey ▸ hdisc)
    exact quadratic_splits_of_discrim_nonneg h2 hquad
  have hle1 : p.natDegree ≤ 1 :=
    Nat.lt_succ_iff.mp (lt_of_le_of_ne hle2 h2)
  rcases Nat.eq_or_lt_of_le hle1 with h1 | hlt1
  · exact Polynomial.Splits.of_natDegree_eq_one h1
  · have h0 : p.natDegree = 0 :=
      Nat.eq_zero_of_le_zero (Nat.le_of_lt_succ hlt1)
    exact Polynomial.Splits.of_natDegree_eq_zero h0

/-- A splitting real cubic has nonnegative cubic coefficient discriminant. -/
theorem cubicDiscr_nonneg_of_splits_natDegree_three
    {p : ℝ[X]} (hdeg : p.natDegree = 3) (hs : p.Splits) :
    0 ≤ cubicDiscr p := by
  obtain ⟨r, hr⟩ := cubic_exists_isRoot hdeg
  have hfact : (X - C r) * (p /ₘ (X - C r)) = p := mul_divByMonic_eq_iff_isRoot.mpr hr
  set q := p /ₘ (X - C r) with hq
  have hqdeg : q.natDegree = 2 := by
    rw [hq, natDegree_divByMonic p (monic_X_sub_C r), hdeg, natDegree_X_sub_C]
  have hqsplit : q.Splits := by
    have hp : ((X - C r) * q).Splits := by
      rwa [hfact]
    rwa [splits_X_sub_C_mul_iff] at hp
  have hdisc_q : 0 ≤ discrim (q.coeff 2) (q.coeff 1) (q.coeff 0) := by
    have hquad := quadratic_disc_coeff_le_of_splits_natDegree_two hqdeg hqsplit
    unfold discrim
    nlinarith [hquad]
  have hkey : cubicDiscr p
      = (q.eval r) ^ 2 * discrim (q.coeff 2) (q.coeff 1) (q.coeff 0) := by
    rw [← hfact]
    exact cubicDiscr_eq_of_factor hqdeg
  rw [hkey]
  exact mul_nonneg (sq_nonneg _) hdisc_q

/-- A splitting real polynomial of degree at most three has nonnegative cubic
coefficient discriminant. -/
theorem cubicDiscr_nonneg_of_splits_natDegree_le_three
    {p : ℝ[X]} (hdeg : p.natDegree ≤ 3) (hs : p.Splits) :
    0 ≤ cubicDiscr p := by
  by_cases h3 : p.natDegree = 3
  · exact cubicDiscr_nonneg_of_splits_natDegree_three h3 hs
  have hle2 : p.natDegree ≤ 2 :=
    Nat.lt_succ_iff.mp (lt_of_le_of_ne hdeg h3)
  by_cases h2 : p.natDegree = 2
  · have hkey := cubicDiscr_eq_coeff_two_sq_mul_discrim_of_natDegree_two h2
    have hdisc_q : 0 ≤ discrim (p.coeff 2) (p.coeff 1) (p.coeff 0) := by
      have hquad := quadratic_disc_coeff_le_of_splits_natDegree_two h2 hs
      unfold discrim
      nlinarith [hquad]
    rw [hkey]
    exact mul_nonneg (sq_nonneg _) hdisc_q
  have hle1 : p.natDegree ≤ 1 :=
    Nat.lt_succ_iff.mp (lt_of_le_of_ne hle2 h2)
  have hc2 : p.coeff 2 = 0 :=
    coeff_eq_zero_of_natDegree_lt (lt_of_le_of_lt hle1 (by norm_num))
  have hc3 : p.coeff 3 = 0 :=
    coeff_eq_zero_of_natDegree_lt (lt_of_le_of_lt hle1 (by norm_num))
  unfold cubicDiscr
  rw [hc2, hc3]
  ring_nf
  norm_num

/-- Through degree three, nonnegativity of the cubic coefficient discriminant
is equivalent to splitting over `ℝ`. -/
theorem cubicDiscr_nonneg_iff_splits_of_natDegree_le_three
    {p : ℝ[X]} (hdeg : p.natDegree ≤ 3) :
    0 ≤ cubicDiscr p ↔ p.Splits :=
  ⟨splits_of_natDegree_le_three_cubicDiscr_nonneg hdeg,
    cubicDiscr_nonneg_of_splits_natDegree_le_three hdeg⟩

end RealRooted
