import Mathlib.Algebra.Polynomial.Splits
import Mathlib.Algebra.Polynomial.Div
import Mathlib.Algebra.Polynomial.SpecificDegree
import Mathlib.Algebra.QuadraticDiscriminant
import Mathlib.Analysis.Complex.Polynomial.Basic
import Mathlib.Analysis.Real.Sqrt
import RealRooted.Mathlib.Algebra.Polynomial.Degree.Operations
import RealRooted.QuadraticRoot

/-!
# The discriminant criterion for a real cubic to split

A real cubic `p = a X^3 + b X^2 + c X + d` (`a = p.coeff 3`, `b = p.coeff 2`,
`c = p.coeff 1`, `d = p.coeff 0`) splits over `ℝ` (all three roots are real) as
soon as its coefficient discriminant

`Δ = 18 a b c d - 4 b^3 d + b^2 c^2 - 4 a c^3 - 27 a^2 d^2`

is nonnegative.

The proof is elementary and avoids the complex numbers entirely.  Any real
cubic has at least one real root `r` (a degree-three polynomial with no root
would be irreducible, contradicting that irreducible real polynomials have
degree at most two).  Writing `p = (X - r) q` with `q` a real quadratic, a
direct algebraic identity gives

`Δ = (q.eval r)^2 * discrim (q.coeff 2) (q.coeff 1) (q.coeff 0)`,

so `Δ ≥ 0` forces the discriminant of the cofactor `q` to be nonnegative
whenever `q.eval r ≠ 0`; and if `q.eval r = 0` then `r` is already a root of
`q`.  Either way `q` splits, hence so does `p = (X - r) q`.

Here `Polynomial.Splits f` is the self-splitting predicate of
`Mathlib.Algebra.Polynomial.Splits` (`f` lies in the submonoid generated by the
constants and the linear polynomials), which for a nonzero real polynomial is
equivalent to having as many roots (with multiplicity) as its degree.
-/

open Polynomial

noncomputable section

namespace RealRooted

/-- The coefficient discriminant of a cubic `a X^3 + b X^2 + c X + d`, with
`a = p.coeff 3`, `b = p.coeff 2`, `c = p.coeff 1`, `d = p.coeff 0`. -/
def cubicDiscr (p : ℝ[X]) : ℝ :=
  18 * p.coeff 3 * p.coeff 2 * p.coeff 1 * p.coeff 0
    - 4 * p.coeff 2 ^ 3 * p.coeff 0
    + p.coeff 2 ^ 2 * p.coeff 1 ^ 2
    - 4 * p.coeff 3 * p.coeff 1 ^ 3
    - 27 * p.coeff 3 ^ 2 * p.coeff 0 ^ 2

/-- The coefficient discriminant `cubicDiscr` is homogeneous of degree four in the
coefficients, so scaling by a constant `C k` multiplies it by `k ^ 4`. -/
theorem cubicDiscr_C_mul (k : ℝ) (p : ℝ[X]) :
    cubicDiscr (C k * p) = k ^ 4 * cubicDiscr p := by
  unfold cubicDiscr
  simp only [coeff_C_mul]
  ring

/-- Coefficient-form evaluation of the cubic discriminant.  For a cubic
written in the standard basis `α X^3 + β X^2 + γ X + δ`, this rewrites
`cubicDiscr` as the explicit degree-four polynomial in the coefficients. -/
theorem cubicDiscr_of_coeffs (α β γ δ : ℝ) :
    cubicDiscr (C α * X ^ 3 + C β * X ^ 2 + C γ * X + C δ)
      = 18 * α * β * γ * δ - 4 * β ^ 3 * δ + β ^ 2 * γ ^ 2
          - 4 * α * γ ^ 3 - 27 * α ^ 2 * δ ^ 2 := by
  unfold cubicDiscr
  simp only [coeff_add, coeff_C_mul, coeff_X_pow, coeff_C,
    coeff_X, mul_ite, mul_one, mul_zero]
  norm_num

/-- Critical-value form of the discriminant of a monic cubic.

If `t` is a critical point of `X^3 + p X^2 + q X + r`, the cubic discriminant
can be expressed using the value at `t` and the second-derivative factor
`3 * t + p`. -/
theorem cubicDiscr_of_coeffs_of_deriv_eq_zero (p q r t : ℝ)
    (hcrit : 3 * t ^ 2 + 2 * p * t + q = 0) :
    cubicDiscr (C (1 : ℝ) * X ^ 3 + C p * X ^ 2 + C q * X + C r) =
      -27 * (t ^ 3 + p * t ^ 2 + q * t + r) ^ 2 -
        4 * (t ^ 3 + p * t ^ 2 + q * t + r) * (3 * t + p) ^ 3 := by
  have hq : q = -(3 * t ^ 2 + 2 * p * t) := by linarith
  subst q
  rw [cubicDiscr_of_coeffs]
  ring

/-- Exact negative-discriminant criterion from a named critical value. -/
theorem cubicDiscr_neg_iff_critical_value
    {p q r t y : ℝ}
    (hcrit : 3 * t ^ 2 + 2 * p * t + q = 0)
    (hvalue : y = t ^ 3 + p * t ^ 2 + q * t + r) :
    cubicDiscr (C (1 : ℝ) * X ^ 3 + C p * X ^ 2 + C q * X + C r) < 0 ↔
      0 < y * (27 * y + 4 * (3 * t + p) ^ 3) := by
  rw [cubicDiscr_of_coeffs_of_deriv_eq_zero _ _ _ _ hcrit]
  rw [← hvalue]
  rw [show
      -27 * y ^ 2 - 4 * y * (3 * t + p) ^ 3 =
        -(y * (27 * y + 4 * (3 * t + p) ^ 3)) by ring]
  exact neg_lt_zero

/-- Negative-discriminant certificate from a nonzero critical value.

At a critical point `t` of the monic cubic `X^3 + p X^2 + q X + r`, if the
critical value `y` has weakly the same sign as `(3*t+p)^3`, then the cubic
coefficient discriminant is negative. -/
theorem cubicDiscr_neg_of_critical_value
    {p q r t y : ℝ}
    (hcrit : 3 * t ^ 2 + 2 * p * t + q = 0)
    (hvalue : y = t ^ 3 + p * t ^ 2 + q * t + r)
    (hy : y ≠ 0)
    (hsign : 0 ≤ y * (3 * t + p) ^ 3) :
    cubicDiscr (C (1 : ℝ) * X ^ 3 + C p * X ^ 2 + C q * X + C r) < 0 := by
  have hy_sq_pos : 0 < y ^ 2 := sq_pos_of_ne_zero hy
  exact (cubicDiscr_neg_iff_critical_value hcrit hvalue).mpr (by nlinarith)

/-- The discriminant of the Hessian quadratic covariant of a cubic is
`-3` times the cubic discriminant.

For `α X^3 + β X^2 + γ X + δ`, the Hessian quadratic coefficients used here
are `β^2 - 3αγ`, `βγ - 9αδ`, and `γ^2 - 3βδ`. -/
theorem cubicHessianDiscr_eq_neg_three_mul_cubicDiscr (α β γ δ : ℝ) :
    (β * γ - 9 * α * δ) ^ 2 -
        4 * (β ^ 2 - 3 * α * γ) * (γ ^ 2 - 3 * β * δ) =
      -3 * cubicDiscr (C α * X ^ 3 + C β * X ^ 2 + C γ * X + C δ) := by
  rw [cubicDiscr_of_coeffs]
  ring

/-- Coefficient-discriminant negativity is equivalent to positivity of the
Hessian quadratic discriminant. -/
theorem cubicDiscr_neg_iff_hessianDiscr_pos (α β γ δ : ℝ) :
    cubicDiscr (C α * X ^ 3 + C β * X ^ 2 + C γ * X + C δ) < 0 ↔
      0 <
        (β * γ - 9 * α * δ) ^ 2 -
          4 * (β ^ 2 - 3 * α * γ) * (γ ^ 2 - 3 * β * δ) := by
  rw [cubicHessianDiscr_eq_neg_three_mul_cubicDiscr]
  constructor <;> intro h <;> nlinarith

/-- Negative-discriminant certificate from the quadratic Hessian covariant.

For a cubic `α X^3 + β X^2 + γ X + δ`, the Hessian quadratic has coefficients
`β^2 - 3αγ`, `βγ - 9αδ`, and `γ^2 - 3βδ`.  If this quadratic opens upward and
is negative somewhere, then its discriminant is positive, hence the cubic
discriminant is negative. -/
theorem cubicDiscr_neg_of_hessian_neg_at (α β γ δ t : ℝ)
    (hlead : 0 < β ^ 2 - 3 * α * γ)
    (hval :
      (β ^ 2 - 3 * α * γ) * t ^ 2 + (β * γ - 9 * α * δ) * t +
          (γ ^ 2 - 3 * β * δ) < 0) :
    cubicDiscr (C α * X ^ 3 + C β * X ^ 2 + C γ * X + C δ) < 0 := by
  have hdisc :
      0 < (β * γ - 9 * α * δ) ^ 2 -
        4 * (β ^ 2 - 3 * α * γ) * (γ ^ 2 - 3 * β * δ) := by
    nlinarith [sq_nonneg
      (2 * (β ^ 2 - 3 * α * γ) * t + (β * γ - 9 * α * δ)),
      mul_pos hlead (neg_pos.mpr hval)]
  exact (cubicDiscr_neg_iff_hessianDiscr_pos α β γ δ).mpr hdisc

/-- Expansion of a monic product of three linear factors. -/
theorem prod_three_X_sub_C_expand (a b c : ℝ) :
    (X - C a) * (X - C b) * (X - C c)
      = X ^ 3 - C (a + b + c) * X ^ 2 + C (a * b + b * c + c * a) * X
          - C (a * b * c) := by
  simp only [C_add, C_mul]
  ring

/-- The coefficient discriminant of a monic split cubic equals the square of the
product of the pairwise differences of its roots. -/
theorem cubicDiscr_prod_three_X_sub_C (a b c : ℝ) :
    cubicDiscr ((X - C a) * (X - C b) * (X - C c))
      = ((a - b) * (b - c) * (a - c)) ^ 2 := by
  rw [prod_three_X_sub_C_expand]
  unfold cubicDiscr
  simp only [coeff_sub, coeff_add, coeff_C_mul, coeff_X_pow, coeff_C,
    coeff_X, mul_ite, mul_one, mul_zero]
  norm_num
  ring

/-- #41-only cubic support, not #42.  Affine covariance of the cubic
coefficient discriminant of a monic cubic root pencil.  Applying the affine
change of variable `x ↦ (x - t) / k` to every root scales `cubicDiscr` by
`k ^ 6`. -/
theorem cubicDiscr_monicPencil_affine
    (k t a b c p q r s : ℝ) (hk : k ≠ 0) :
    cubicDiscr ((X - C a) * (X - C b) * (X - C c)
        + C s * ((X - C p) * (X - C q) * (X - C r))) =
      k ^ 6 * cubicDiscr
        ((X - C ((a - t) / k)) * (X - C ((b - t) / k)) *
            (X - C ((c - t) / k))
          + C s * ((X - C ((p - t) / k)) * (X - C ((q - t) / k)) *
            (X - C ((r - t) / k)))) := by
  have hcoeff : ∀ u v w x y z : ℝ,
      (X - C u) * (X - C v) * (X - C w)
          + C s * ((X - C x) * (X - C y) * (X - C z)) =
        C (1 + s) * X ^ 3
          + C (-((u + v + w) + s * (x + y + z))) * X ^ 2
          + C ((u * v + v * w + w * u) + s * (x * y + y * z + z * x)) * X
          + C (-(u * v * w + s * (x * y * z))) := by
    intro u v w x y z
    simp only [C_add, C_mul, C_neg, C_1]
    ring
  rw [hcoeff, hcoeff, cubicDiscr_of_coeffs, cubicDiscr_of_coeffs]
  field_simp
  ring

/-- #41-only cubic support, not #42.  Single-monic-cubic special case of
`cubicDiscr_monicPencil_affine`. -/
theorem cubicDiscr_prod_three_X_sub_C_affine
    (k t a b c : ℝ) (hk : k ≠ 0) :
    cubicDiscr ((X - C a) * (X - C b) * (X - C c)) =
      k ^ 6 * cubicDiscr
        ((X - C ((a - t) / k)) * (X - C ((b - t) / k)) *
          (X - C ((c - t) / k))) := by
  rw [cubicDiscr_prod_three_X_sub_C, cubicDiscr_prod_three_X_sub_C]
  field_simp
  ring

/-- Every real cubic has a real root: a degree-three real polynomial without a
root would be irreducible, contradicting that irreducible real polynomials have
degree at most two. -/
lemma cubic_exists_isRoot {p : ℝ[X]} (hdeg : p.natDegree = 3) :
    ∃ r : ℝ, p.IsRoot r := by
  by_contra h
  have hnot : ∀ x : ℝ, ¬ p.IsRoot x := fun x hx => h ⟨x, hx⟩
  have hirr : Irreducible p :=
    irreducible_of_degree_le_three_of_not_isRoot (by rw [hdeg]; decide) hnot
  have hle : p.natDegree ≤ 2 := Irreducible.natDegree_le_two hirr
  rw [hdeg] at hle
  exact absurd hle (by decide)

/-- Pure algebraic identity underlying the discriminant criterion.  With
`A, B, D` the coefficients of a quadratic `q = A X^2 + B X + D` and `r` a scalar,
the coefficient discriminant of `(X - r) q` equals `(q.eval r)^2` times the
quadratic discriminant `B^2 - 4 A D`. -/
lemma cubicDiscr_factor_identity (A B D r : ℝ) :
    18 * A * (B - r * A) * (D - r * B) * (-(r * D))
        - 4 * (B - r * A) ^ 3 * (-(r * D))
        + (B - r * A) ^ 2 * (D - r * B) ^ 2
        - 4 * A * (D - r * B) ^ 3
        - 27 * A ^ 2 * (-(r * D)) ^ 2
      = (A * r ^ 2 + B * r + D) ^ 2 * (B ^ 2 - 4 * A * D) := by
  ring

/-- Evaluation of a quadratic `q` at a point in terms of its coefficients. -/
lemma eval_of_natDegree_two {q : ℝ[X]} (r : ℝ) (hqdeg : q.natDegree = 2) :
    q.eval r = q.coeff 2 * r ^ 2 + q.coeff 1 * r + q.coeff 0 := by
  rw [eval_eq_sum_range, hqdeg]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero, pow_zero, pow_one,
    zero_add, mul_one]
  ring

/-- The four coefficients of `(X - C r) * q` in terms of the coefficients of a
quadratic `q`. -/
lemma coeff_X_sub_C_mul_of_natDegree_two {q : ℝ[X]} (r : ℝ) (hqdeg : q.natDegree = 2) :
    ((X - C r) * q).coeff 3 = q.coeff 2 ∧
      ((X - C r) * q).coeff 2 = q.coeff 1 - r * q.coeff 2 ∧
      ((X - C r) * q).coeff 1 = q.coeff 0 - r * q.coeff 1 ∧
      ((X - C r) * q).coeff 0 = -(r * q.coeff 0) := by
  have hq3 : q.coeff 3 = 0 := coeff_eq_zero_of_natDegree_lt (by rw [hqdeg]; decide)
  refine ⟨?_, ?_, ?_, ?_⟩
  · rw [show (3 : ℕ) = 2 + 1 from rfl, coeff_X_sub_C_mul, hq3, mul_zero, sub_zero]
  · rw [show (2 : ℕ) = 1 + 1 from rfl, coeff_X_sub_C_mul]
  · rw [show (1 : ℕ) = 0 + 1 from rfl, coeff_X_sub_C_mul]
  · rw [sub_mul, coeff_sub, coeff_C_mul, coeff_X_mul_zero, zero_sub]

/-- Discriminant factorisation for a cubic given as `(X - C r) * q` with `q` a
real quadratic. -/
lemma cubicDiscr_eq_of_factor {q : ℝ[X]} {r : ℝ} (hqdeg : q.natDegree = 2) :
    cubicDiscr ((X - C r) * q)
      = (q.eval r) ^ 2 * discrim (q.coeff 2) (q.coeff 1) (q.coeff 0) := by
  obtain ⟨h3, h2, h1, h0⟩ := coeff_X_sub_C_mul_of_natDegree_two r hqdeg
  rw [eval_of_natDegree_two r hqdeg]
  unfold cubicDiscr discrim
  rw [h3, h2, h1, h0]
  ring

/-- A real quadratic with nonnegative discriminant splits. -/
lemma quadratic_splits_of_discrim_nonneg {q : ℝ[X]} (hqdeg : q.natDegree = 2)
    (hdisc : 0 ≤ discrim (q.coeff 2) (q.coeff 1) (q.coeff 0)) : q.Splits := by
  have hq_ne : q ≠ 0 := by intro h; rw [h, natDegree_zero] at hqdeg; exact absurd hqdeg (by decide)
  have hc2 : q.coeff 2 ≠ 0 := by
    have hlc : q.leadingCoeff ≠ 0 := leadingCoeff_ne_zero.mpr hq_ne
    rwa [leadingCoeff, hqdeg] at hlc
  obtain ⟨x, hx⟩ := exists_quadratic_eq_zero hc2
    ⟨Real.sqrt (discrim (q.coeff 2) (q.coeff 1) (q.coeff 0)),
      (Real.mul_self_sqrt hdisc).symm⟩
  have hroot : q.eval x = 0 := by rw [eval_of_natDegree_two x hqdeg]; linear_combination hx
  exact Splits.of_natDegree_eq_two hqdeg hroot

/-- **Discriminant criterion for real cubics.**  A real polynomial of
`natDegree` three with nonnegative coefficient discriminant splits over `ℝ`. -/
theorem splits_of_cubicDiscr_nonneg {p : ℝ[X]} (hdeg : p.natDegree = 3)
    (hdisc : 0 ≤ cubicDiscr p) : p.Splits := by
  obtain ⟨r, hr⟩ := cubic_exists_isRoot hdeg
  have hfact : (X - C r) * (p /ₘ (X - C r)) = p := mul_divByMonic_eq_iff_isRoot.mpr hr
  set q := p /ₘ (X - C r) with hq
  have hqdeg : q.natDegree = 2 := by
    rw [hq, natDegree_divByMonic_X_sub_C, hdeg]
  have hsplit : q.Splits := by
    by_cases hroot : q.IsRoot r
    · exact Splits.of_natDegree_eq_two hqdeg hroot
    · have hkey : cubicDiscr p
          = (q.eval r) ^ 2 * discrim (q.coeff 2) (q.coeff 1) (q.coeff 0) := by
        rw [← hfact]; exact cubicDiscr_eq_of_factor hqdeg
      have hne : q.eval r ≠ 0 := hroot
      have hsq : 0 < (q.eval r) ^ 2 :=
        (sq_nonneg _).lt_of_ne (Ne.symm (pow_ne_zero 2 hne))
      have hdisc' : 0 ≤ discrim (q.coeff 2) (q.coeff 1) (q.coeff 0) :=
        (mul_nonneg_iff_of_pos_left hsq).mp (hkey ▸ hdisc)
      exact quadratic_splits_of_discrim_nonneg hqdeg hdisc'
  rw [← hfact, splits_X_sub_C_mul_iff]
  exact hsplit

/-- If `p` has degree exactly two, then its cubic discriminant is the square of
its quadratic leading coefficient times its quadratic discriminant. -/
lemma cubicDiscr_eq_coeff_two_sq_mul_discrim_of_natDegree_two
    {p : ℝ[X]} (hdeg : p.natDegree = 2) :
    cubicDiscr p =
      p.coeff 2 ^ 2 * discrim (p.coeff 2) (p.coeff 1) (p.coeff 0) := by
  have hc3 : p.coeff 3 = 0 :=
    coeff_eq_zero_of_natDegree_lt (by rw [hdeg]; norm_num)
  unfold cubicDiscr discrim
  rw [hc3]
  ring

/-- **Discriminant criterion through degree three.**  A real polynomial of
`natDegree` at most three with nonnegative cubic coefficient discriminant splits
over `ℝ`.  In degree two, this reduces to the usual quadratic discriminant
because the cubic discriminant is the square of the quadratic leading
coefficient times the quadratic discriminant. -/
theorem splits_of_natDegree_le_three_cubicDiscr_nonneg
    {p : ℝ[X]} (hdeg : p.natDegree ≤ 3) (hdisc : 0 ≤ cubicDiscr p) :
    p.Splits := by
  by_cases h3 : p.natDegree = 3
  · exact splits_of_cubicDiscr_nonneg h3 hdisc
  have hle2 : p.natDegree ≤ 2 :=
    Nat.lt_succ_iff.mp (lt_of_le_of_ne hdeg h3)
  by_cases h2 : p.natDegree = 2
  · have hkey := cubicDiscr_eq_coeff_two_sq_mul_discrim_of_natDegree_two h2
    have hc2_ne : p.coeff 2 ≠ 0 := by
      have hp_ne : p ≠ 0 := by
        intro hp
        rw [hp, natDegree_zero] at h2
        norm_num at h2
      have hlc : p.leadingCoeff ≠ 0 := leadingCoeff_ne_zero.mpr hp_ne
      rwa [leadingCoeff, h2] at hlc
    have hsquare : 0 < p.coeff 2 ^ 2 :=
      (sq_nonneg _).lt_of_ne (Ne.symm (pow_ne_zero 2 hc2_ne))
    have hquad : 0 ≤ discrim (p.coeff 2) (p.coeff 1) (p.coeff 0) :=
      (mul_nonneg_iff_of_pos_left hsquare).mp (hkey ▸ hdisc)
    exact quadratic_splits_of_discrim_nonneg h2 hquad
  have hle1 : p.natDegree ≤ 1 :=
    Nat.lt_succ_iff.mp (lt_of_le_of_ne hle2 h2)
  rcases Nat.eq_or_lt_of_le hle1 with h1 | hlt1
  · exact Polynomial.Splits.of_natDegree_eq_one h1
  · have h0 : p.natDegree = 0 :=
      Nat.eq_zero_of_le_zero (Nat.le_of_lt_succ hlt1)
    exact Polynomial.Splits.of_natDegree_eq_zero h0

/-- A splitting real cubic has nonnegative cubic coefficient discriminant. -/
theorem cubicDiscr_nonneg_of_splits_natDegree_three
    {p : ℝ[X]} (hdeg : p.natDegree = 3) (hs : p.Splits) :
    0 ≤ cubicDiscr p := by
  obtain ⟨r, hr⟩ := cubic_exists_isRoot hdeg
  have hfact : (X - C r) * (p /ₘ (X - C r)) = p := mul_divByMonic_eq_iff_isRoot.mpr hr
  set q := p /ₘ (X - C r) with hq
  have hqdeg : q.natDegree = 2 := by
    rw [hq, natDegree_divByMonic_X_sub_C, hdeg]
  have hqsplit : q.Splits := by
    have hp : ((X - C r) * q).Splits := by rwa [hfact]
    rwa [splits_X_sub_C_mul_iff] at hp
  have hdisc_q : 0 ≤ discrim (q.coeff 2) (q.coeff 1) (q.coeff 0) := by
    have hquad := quadratic_disc_coeff_le_of_splits_natDegree_two hqdeg hqsplit
    unfold discrim
    nlinarith [hquad]
  have hkey : cubicDiscr p
      = (q.eval r) ^ 2 * discrim (q.coeff 2) (q.coeff 1) (q.coeff 0) := by
    rw [← hfact]
    exact cubicDiscr_eq_of_factor hqdeg
  rw [hkey]
  exact mul_nonneg (sq_nonneg _) hdisc_q

/-- A splitting real polynomial of degree at most three has nonnegative cubic
coefficient discriminant. -/
theorem cubicDiscr_nonneg_of_splits_natDegree_le_three
    {p : ℝ[X]} (hdeg : p.natDegree ≤ 3) (hs : p.Splits) :
    0 ≤ cubicDiscr p := by
  by_cases h3 : p.natDegree = 3
  · exact cubicDiscr_nonneg_of_splits_natDegree_three h3 hs
  have hle2 : p.natDegree ≤ 2 :=
    Nat.lt_succ_iff.mp (lt_of_le_of_ne hdeg h3)
  by_cases h2 : p.natDegree = 2
  · have hkey := cubicDiscr_eq_coeff_two_sq_mul_discrim_of_natDegree_two h2
    have hdisc_q : 0 ≤ discrim (p.coeff 2) (p.coeff 1) (p.coeff 0) := by
      have hquad := quadratic_disc_coeff_le_of_splits_natDegree_two h2 hs
      unfold discrim
      nlinarith [hquad]
    rw [hkey]
    exact mul_nonneg (sq_nonneg _) hdisc_q
  have hle1 : p.natDegree ≤ 1 :=
    Nat.lt_succ_iff.mp (lt_of_le_of_ne hle2 h2)
  have hc2 : p.coeff 2 = 0 :=
    coeff_eq_zero_of_natDegree_lt (lt_of_le_of_lt hle1 (by norm_num))
  have hc3 : p.coeff 3 = 0 :=
    coeff_eq_zero_of_natDegree_lt (lt_of_le_of_lt hle1 (by norm_num))
  unfold cubicDiscr
  rw [hc2, hc3]
  ring_nf
  norm_num

/-- A real polynomial of degree at most three with negative cubic coefficient
discriminant cannot split. -/
theorem not_splits_of_cubicDiscr_neg_of_natDegree_le_three
    {p : ℝ[X]} (hdeg : p.natDegree ≤ 3) (hdisc : cubicDiscr p < 0) :
    ¬ p.Splits := by
  intro hs
  exact (not_le.mpr hdisc)
    (cubicDiscr_nonneg_of_splits_natDegree_le_three hdeg hs)

/-- Through degree three, nonnegativity of the cubic coefficient discriminant
is equivalent to splitting over `ℝ`. -/
theorem cubicDiscr_nonneg_iff_splits_of_natDegree_le_three
    {p : ℝ[X]} (hdeg : p.natDegree ≤ 3) :
    0 ≤ cubicDiscr p ↔ p.Splits :=
  ⟨splits_of_natDegree_le_three_cubicDiscr_nonneg hdeg,
    cubicDiscr_nonneg_of_splits_natDegree_le_three hdeg⟩

/-- The cubic discriminant of a monic split cubic with three distinct real roots
is strictly positive. -/
theorem cubicDiscr_prod_three_X_sub_C_pos {a b c : ℝ}
    (hab : a ≠ b) (hbc : b ≠ c) (hac : a ≠ c) :
    0 < cubicDiscr ((X - C a) * (X - C b) * (X - C c)) := by
  rw [cubicDiscr_prod_three_X_sub_C]
  have hne : (a - b) * (b - c) * (a - c) ≠ 0 :=
    mul_ne_zero (mul_ne_zero (sub_ne_zero.mpr hab) (sub_ne_zero.mpr hbc))
      (sub_ne_zero.mpr hac)
  exact (sq_nonneg _).lt_of_ne (Ne.symm (pow_ne_zero 2 hne))

/-- Nonvanishing form of `cubicDiscr_prod_three_X_sub_C_pos`. -/
theorem cubicDiscr_prod_three_X_sub_C_ne_zero {a b c : ℝ}
    (hab : a ≠ b) (hbc : b ≠ c) (hac : a ≠ c) :
    cubicDiscr ((X - C a) * (X - C b) * (X - C c)) ≠ 0 :=
  ne_of_gt (cubicDiscr_prod_three_X_sub_C_pos hab hbc hac)

/-- The discriminant of a monic split cubic vanishes exactly when two roots
coincide. -/
theorem cubicDiscr_prod_three_X_sub_C_eq_zero_iff (a b c : ℝ) :
    cubicDiscr ((X - C a) * (X - C b) * (X - C c)) = 0
      ↔ a = b ∨ b = c ∨ a = c := by
  rw [cubicDiscr_prod_three_X_sub_C, pow_eq_zero_iff (by norm_num)]
  rw [mul_eq_zero, mul_eq_zero, sub_eq_zero, sub_eq_zero, sub_eq_zero, or_assoc]

/-- Nonnegativity of the discriminant of a split monic cubic. -/
theorem cubicDiscr_prod_three_X_sub_C_nonneg (a b c : ℝ) :
    0 ≤ cubicDiscr ((X - C a) * (X - C b) * (X - C c)) := by
  rw [cubicDiscr_prod_three_X_sub_C]
  exact sq_nonneg _

/-- Nonvanishing criterion for the discriminant of a split monic cubic. -/
theorem cubicDiscr_prod_three_X_sub_C_ne_zero_iff (a b c : ℝ) :
    cubicDiscr ((X - C a) * (X - C b) * (X - C c)) ≠ 0
      ↔ a ≠ b ∧ b ≠ c ∧ a ≠ c := by
  rw [ne_eq, cubicDiscr_prod_three_X_sub_C_eq_zero_iff]
  simp [not_or]

/-- Positivity criterion for the discriminant of a split monic cubic. -/
theorem cubicDiscr_prod_three_X_sub_C_pos_iff (a b c : ℝ) :
    0 < cubicDiscr ((X - C a) * (X - C b) * (X - C c))
      ↔ a ≠ b ∧ b ≠ c ∧ a ≠ c := by
  constructor
  · intro h
    have hne : cubicDiscr ((X - C a) * (X - C b) * (X - C c)) ≠ 0 := ne_of_gt h
    rw [ne_eq, cubicDiscr_prod_three_X_sub_C_eq_zero_iff] at hne
    simpa [not_or] using hne
  · rintro ⟨hab, hbc, hac⟩
    exact cubicDiscr_prod_three_X_sub_C_pos hab hbc hac

/-- A split monic cubic has positive discriminant iff its discriminant is nonzero. -/
theorem cubicDiscr_prod_three_X_sub_C_pos_iff_ne_zero (a b c : ℝ) :
    0 < cubicDiscr ((X - C a) * (X - C b) * (X - C c)) ↔
      cubicDiscr ((X - C a) * (X - C b) * (X - C c)) ≠ 0 :=
  ⟨ne_of_gt,
    fun h => lt_of_le_of_ne (cubicDiscr_prod_three_X_sub_C_nonneg a b c) (Ne.symm h)⟩

/-- A split monic cubic has nonpositive discriminant iff its discriminant
vanishes. -/
theorem cubicDiscr_prod_three_X_sub_C_nonpos_iff_eq_zero (a b c : ℝ) :
    cubicDiscr ((X - C a) * (X - C b) * (X - C c)) ≤ 0 ↔
      cubicDiscr ((X - C a) * (X - C b) * (X - C c)) = 0 :=
  ⟨fun h => le_antisymm h (cubicDiscr_prod_three_X_sub_C_nonneg a b c),
    fun h => le_of_eq h⟩

/-- Reverse-direction form of
`cubicDiscr_prod_three_X_sub_C_nonpos_iff_eq_zero`. -/
theorem cubicDiscr_prod_three_X_sub_C_eq_zero_iff_nonpos (a b c : ℝ) :
    cubicDiscr ((X - C a) * (X - C b) * (X - C c)) = 0 ↔
      cubicDiscr ((X - C a) * (X - C b) * (X - C c)) ≤ 0 :=
  (cubicDiscr_prod_three_X_sub_C_nonpos_iff_eq_zero a b c).symm

/-- A split monic cubic cannot have negative discriminant. -/
theorem cubicDiscr_prod_three_X_sub_C_not_neg (a b c : ℝ) :
    ¬ cubicDiscr ((X - C a) * (X - C b) * (X - C c)) < 0 :=
  not_lt.mpr (cubicDiscr_prod_three_X_sub_C_nonneg a b c)

/-- Elimination form for an impossible negative discriminant of a split monic
cubic. -/
theorem cubicDiscr_prod_three_X_sub_C_neg_elim {a b c : ℝ} {P : Prop}
    (h : cubicDiscr ((X - C a) * (X - C b) * (X - C c)) < 0) : P :=
  absurd h (cubicDiscr_prod_three_X_sub_C_not_neg a b c)

/-- Disjunctive elimination form for an impossible negative discriminant of a
split monic cubic. -/
theorem cubicDiscr_prod_three_X_sub_C_neg_or_elim {a b c : ℝ} {P : Prop}
    (h : cubicDiscr ((X - C a) * (X - C b) * (X - C c)) < 0 ∨ P) : P :=
  h.resolve_left (cubicDiscr_prod_three_X_sub_C_not_neg a b c)

/-- Right-disjunctive elimination form for an impossible negative
discriminant of a split monic cubic. -/
theorem cubicDiscr_prod_three_X_sub_C_or_neg_elim {a b c : ℝ} {P : Prop}
    (h : P ∨ cubicDiscr ((X - C a) * (X - C b) * (X - C c)) < 0) : P :=
  h.resolve_right (cubicDiscr_prod_three_X_sub_C_not_neg a b c)

/-- Positivity of the cubic discriminant from strictly ordered roots. -/
theorem cubicDiscr_prod_three_X_sub_C_pos_of_lt {a b c : ℝ}
    (hab : a < b) (hbc : b < c) :
    0 < cubicDiscr ((X - C a) * (X - C b) * (X - C c)) :=
  cubicDiscr_prod_three_X_sub_C_pos (ne_of_lt hab) (ne_of_lt hbc)
    (ne_of_lt (hab.trans hbc))

/-- Nonvanishing of the cubic discriminant from strictly ordered roots. -/
theorem cubicDiscr_prod_three_X_sub_C_ne_zero_of_lt {a b c : ℝ}
    (hab : a < b) (hbc : b < c) :
    cubicDiscr ((X - C a) * (X - C b) * (X - C c)) ≠ 0 :=
  ne_of_gt (cubicDiscr_prod_three_X_sub_C_pos_of_lt hab hbc)

end RealRooted
