import RealRooted.FactorialCompression.Definitions
import RealRooted.FactorialCompression.RootGeometry
import RealRooted.FactorialCompression.CommonKernel
import RealRooted.FactorialCompression.SchurSzego
import RealRooted.FactorialCompression.Compression
import RealRooted.FactorialCompression.KernelGeometry
import RealRooted.FactorialCompression.DegreeChanging
import RealRooted.FactorialCompression.Lifting
