import Mathlib.Algebra.Polynomial.Derivative
import Mathlib.Algebra.Order.Field.Basic
import Mathlib.Basic.Real.Basic

/-!
# Degrees of derivative recurrences

Many OEIS triangles are generated by recurrences of the form
`P (n + 1) = A n * (P n)'' + B n * (P n)' + C n * P n`.  If every row grows by
`d` degrees, the coefficient of `P (n + 1)` in degree `natDegree (P n) + d` is
`λ n * leadingCoeff (P n)`, where

`λ n = (A n)_{d+2} D (D - 1) + (B n)_{d+1} D + (C n)_d`,   `D = natDegree (P n)`.

So whenever `λ n` never vanishes, the degree grows by exactly `d` in every step.
If moreover `λ n > 0` and `P 0` has a positive coefficient in degree `D₀`, then
every row has a positive leading coefficient.

## Main results

* `natDegree_mul_iterate_derivative_le`, `coeff_mul_iterate_derivative_of_natDegree_le`:
  the top coefficient of a single term `A * p^{(j)}`.
* `natDegree_eq_of_top_coeff_step`, `ne_zero_of_top_coeff_step`,
  `leadingCoeff_pos_of_top_coeff_step`:
  the induction for any sequence whose top coefficient is multiplied by a
  nonvanishing (or positive) factor in each step.
* `derivRec_natDegree`, `derivRec_ne_zero`, `derivRec_leadingCoeff_pos`:
  first-order derivative recurrences `P (n + 1) = A n * (P n)' + B n * P n`.
* `derivRec₂_natDegree`, `derivRec₂_ne_zero`, `derivRec₂_leadingCoeff_pos`:
  `P (n + 1) = A n * (P n)'' + B n * (P n)' + C n * P n`.
-/

open Polynomial

namespace RealRooted

section Step

/-- The coefficient of `p * q` in degree `m + n` when `natDegree p ≤ m` and
`natDegree q ≤ n`. -/
theorem coeff_mul_add_of_natDegree_le {p q : ℝ[X]} {m n : ℕ} (hp : p.natDegree ≤ m)
    (hq : q.natDegree ≤ n) : (p * q).coeff (m + n) = p.coeff m * q.coeff n := by
  rcases hp.lt_or_eq with hp | rfl
  · rw [coeff_eq_zero_of_natDegree_lt hp, zero_mul,
      coeff_eq_zero_of_natDegree_lt (natDegree_mul_le.trans_lt (by lia))]
  rcases hq.lt_or_eq with hq | rfl
  · rw [coeff_eq_zero_of_natDegree_lt hq, mul_zero,
      coeff_eq_zero_of_natDegree_lt (natDegree_mul_le.trans_lt (by lia))]
  exact coeff_mul_degree_add_degree p q

variable {A p : ℝ[X]} {d j D : ℕ}

theorem natDegree_mul_iterate_derivative_le (hA : A.natDegree ≤ d + j) (hp : p.natDegree ≤ D) :
    (A * derivative^[j] p).natDegree ≤ D + d := by
  rcases lt_or_ge D j with hDj | hDj
  · rw [iterate_derivative_eq_zero (hp.trans_lt hDj), mul_zero, natDegree_zero]
    exact Nat.zero_le _
  · refine (natDegree_mul_le_of_le hA ((natDegree_iterate_derivative p j).trans
      (Nat.sub_le_sub_right hp j))).trans ?_
    lia

theorem coeff_mul_iterate_derivative_of_natDegree_le (hA : A.natDegree ≤ d + j)
    (hp : p.natDegree ≤ D) :
    (A * derivative^[j] p).coeff (D + d) =
      A.coeff (d + j) * (D.descFactorial j : ℝ) * p.coeff D := by
  rcases lt_or_ge D j with hDj | hDj
  · rw [iterate_derivative_eq_zero (hp.trans_lt hDj), mul_zero, coeff_zero,
      Nat.descFactorial_eq_zero_iff_lt.mpr hDj, Nat.cast_zero, mul_zero, zero_mul]
  · have hq : (derivative^[j] p).natDegree ≤ D - j :=
      (natDegree_iterate_derivative p j).trans (Nat.sub_le_sub_right hp j)
    rw [show D + d = (d + j) + (D - j) by lia, coeff_mul_add_of_natDegree_le hA hq,
      coeff_iterate_derivative, Nat.sub_add_cancel hDj, nsmul_eq_mul]
    ring

end Step

section Induction

variable {P : ℕ → ℝ[X]} {d D₀ : ℕ} {lam : ℕ → ℝ}

/-- If the degree bound grows by `d` and the coefficient in the bounding degree
is multiplied by `lam n ≠ 0` in each step, then every row has degree at most
`D₀ + d * n` with a nonzero coefficient in that degree. -/
theorem top_coeff_ne_zero_of_step (hP0 : P 0 ≠ 0) (h0 : (P 0).natDegree = D₀)
    (hle : ∀ n, (P n).natDegree ≤ D₀ + d * n → (P (n + 1)).natDegree ≤ D₀ + d * (n + 1))
    (hcoeff : ∀ n, (P n).natDegree ≤ D₀ + d * n →
      (P (n + 1)).coeff (D₀ + d * (n + 1)) = lam n * (P n).coeff (D₀ + d * n))
    (hlam : ∀ n, lam n ≠ 0) :
    ∀ n, (P n).natDegree ≤ D₀ + d * n ∧ (P n).coeff (D₀ + d * n) ≠ 0
  | 0 => ⟨by simp [h0], by simpa [← h0] using hP0⟩
  | n + 1 =>
      have ih := top_coeff_ne_zero_of_step hP0 h0 hle hcoeff hlam n
      ⟨hle n ih.1, by rw [hcoeff n ih.1]; exact mul_ne_zero (hlam n) ih.2⟩

theorem natDegree_eq_of_top_coeff_step (hP0 : P 0 ≠ 0) (h0 : (P 0).natDegree = D₀)
    (hle : ∀ n, (P n).natDegree ≤ D₀ + d * n → (P (n + 1)).natDegree ≤ D₀ + d * (n + 1))
    (hcoeff : ∀ n, (P n).natDegree ≤ D₀ + d * n →
      (P (n + 1)).coeff (D₀ + d * (n + 1)) = lam n * (P n).coeff (D₀ + d * n))
    (hlam : ∀ n, lam n ≠ 0) (n : ℕ) :
    (P n).natDegree = D₀ + d * n :=
  have h := top_coeff_ne_zero_of_step hP0 h0 hle hcoeff hlam n
  natDegree_eq_of_le_of_coeff_ne_zero h.1 h.2

theorem ne_zero_of_top_coeff_step (hP0 : P 0 ≠ 0) (h0 : (P 0).natDegree = D₀)
    (hle : ∀ n, (P n).natDegree ≤ D₀ + d * n → (P (n + 1)).natDegree ≤ D₀ + d * (n + 1))
    (hcoeff : ∀ n, (P n).natDegree ≤ D₀ + d * n →
      (P (n + 1)).coeff (D₀ + d * (n + 1)) = lam n * (P n).coeff (D₀ + d * n))
    (hlam : ∀ n, lam n ≠ 0) (n : ℕ) :
    P n ≠ 0 := fun h => (top_coeff_ne_zero_of_step hP0 h0 hle hcoeff hlam n).2 (by simp [h])

/-- The positive-leading-coefficient companion of `natDegree_eq_of_top_coeff_step`. -/
theorem leadingCoeff_pos_of_top_coeff_step (hP0 : P 0 ≠ 0) (h0 : (P 0).natDegree = D₀)
    (hl0 : 0 < (P 0).coeff D₀)
    (hle : ∀ n, (P n).natDegree ≤ D₀ + d * n → (P (n + 1)).natDegree ≤ D₀ + d * (n + 1))
    (hcoeff : ∀ n, (P n).natDegree ≤ D₀ + d * n →
      (P (n + 1)).coeff (D₀ + d * (n + 1)) = lam n * (P n).coeff (D₀ + d * n))
    (hlam : ∀ n, 0 < lam n) (n : ℕ) :
    0 < (P n).leadingCoeff := by
  have hdeg := natDegree_eq_of_top_coeff_step hP0 h0 hle hcoeff (fun n => (hlam n).ne')
  induction n with
  | zero => rwa [leadingCoeff, h0]
  | succ n ih =>
      rw [leadingCoeff, hdeg (n + 1), hcoeff n (hdeg n).le]
      rw [leadingCoeff, hdeg n] at ih
      exact mul_pos (hlam n) ih

end Induction

section FirstOrder

variable {P A B : ℕ → ℝ[X]} {d D₀ : ℕ}

private theorem derivRec_step
    (hrec : ∀ n, P (n + 1) = A n * (P n).derivative + B n * P n)
    (hA : ∀ n, (A n).natDegree ≤ d + 1) (hB : ∀ n, (B n).natDegree ≤ d) (n : ℕ)
    (hn : (P n).natDegree ≤ D₀ + d * n) :
    (P (n + 1)).natDegree ≤ D₀ + d * (n + 1) ∧
      (P (n + 1)).coeff (D₀ + d * (n + 1)) =
        ((A n).coeff (d + 1) * ((D₀ + d * n : ℕ) : ℝ) + (B n).coeff d) *
          (P n).coeff (D₀ + d * n) := by
  have h1 := natDegree_mul_iterate_derivative_le (j := 1) (hA n) hn
  have h1c := coeff_mul_iterate_derivative_of_natDegree_le (j := 1) (hA n) hn
  have h0 := natDegree_mul_iterate_derivative_le (j := 0) (hB n) hn
  have h0c := coeff_mul_iterate_derivative_of_natDegree_le (j := 0) (hB n) hn
  simp only [Function.iterate_one, Function.iterate_zero, id_eq, add_zero,
    Nat.descFactorial_one, Nat.descFactorial_zero, Nat.cast_one, mul_one] at h1 h1c h0 h0c
  rw [hrec n, show D₀ + d * (n + 1) = D₀ + d * n + d by ring]
  refine ⟨natDegree_add_le_of_degree_le h1 h0, ?_⟩
  rw [coeff_add, h1c, h0c]
  ring

/-- Rows of `P (n + 1) = A n * (P n)' + B n * P n` have degree `D₀ + d * n` when
the top-coefficient multiplier never vanishes. -/
theorem derivRec_natDegree
    (hrec : ∀ n, P (n + 1) = A n * (P n).derivative + B n * P n)
    (hA : ∀ n, (A n).natDegree ≤ d + 1) (hB : ∀ n, (B n).natDegree ≤ d)
    (hP0 : P 0 ≠ 0) (h0 : (P 0).natDegree = D₀)
    (hlam : ∀ n : ℕ, (A n).coeff (d + 1) * ((D₀ + d * n : ℕ) : ℝ) + (B n).coeff d ≠ 0)
    (n : ℕ) : (P n).natDegree = D₀ + d * n :=
  natDegree_eq_of_top_coeff_step hP0 h0 (fun n hn => (derivRec_step hrec hA hB n hn).1)
    (fun n hn => (derivRec_step hrec hA hB n hn).2) hlam n

theorem derivRec_ne_zero
    (hrec : ∀ n, P (n + 1) = A n * (P n).derivative + B n * P n)
    (hA : ∀ n, (A n).natDegree ≤ d + 1) (hB : ∀ n, (B n).natDegree ≤ d)
    (hP0 : P 0 ≠ 0) (h0 : (P 0).natDegree = D₀)
    (hlam : ∀ n : ℕ, (A n).coeff (d + 1) * ((D₀ + d * n : ℕ) : ℝ) + (B n).coeff d ≠ 0)
    (n : ℕ) : P n ≠ 0 :=
  ne_zero_of_top_coeff_step hP0 h0 (fun n hn => (derivRec_step hrec hA hB n hn).1)
    (fun n hn => (derivRec_step hrec hA hB n hn).2) hlam n

theorem derivRec_leadingCoeff_pos
    (hrec : ∀ n, P (n + 1) = A n * (P n).derivative + B n * P n)
    (hA : ∀ n, (A n).natDegree ≤ d + 1) (hB : ∀ n, (B n).natDegree ≤ d)
    (hP0 : P 0 ≠ 0) (h0 : (P 0).natDegree = D₀) (hl0 : 0 < (P 0).coeff D₀)
    (hlam : ∀ n : ℕ, 0 < (A n).coeff (d + 1) * ((D₀ + d * n : ℕ) : ℝ) + (B n).coeff d)
    (n : ℕ) : 0 < (P n).leadingCoeff :=
  leadingCoeff_pos_of_top_coeff_step hP0 h0 hl0 (fun n hn => (derivRec_step hrec hA hB n hn).1)
    (fun n hn => (derivRec_step hrec hA hB n hn).2) hlam n

end FirstOrder

section SecondOrder

variable {P A B C : ℕ → ℝ[X]} {d D₀ : ℕ}

private theorem descFactorial_two_cast (N : ℕ) :
    (N.descFactorial 2 : ℝ) = (N : ℝ) * ((N : ℝ) - 1) := by
  rcases N with _ | N
  · simp
  · rw [Nat.succ_descFactorial_succ, Nat.descFactorial_one]
    push_cast
    ring

private theorem derivRec₂_step
    (hrec : ∀ n, P (n + 1) =
      A n * (P n).derivative.derivative + B n * (P n).derivative + C n * P n)
    (hA : ∀ n, (A n).natDegree ≤ d + 2) (hB : ∀ n, (B n).natDegree ≤ d + 1)
    (hC : ∀ n, (C n).natDegree ≤ d) (n : ℕ) (hn : (P n).natDegree ≤ D₀ + d * n) :
    (P (n + 1)).natDegree ≤ D₀ + d * (n + 1) ∧
      (P (n + 1)).coeff (D₀ + d * (n + 1)) =
        ((A n).coeff (d + 2) * ((D₀ + d * n : ℕ) : ℝ) * (((D₀ + d * n : ℕ) : ℝ) - 1) +
          (B n).coeff (d + 1) * ((D₀ + d * n : ℕ) : ℝ) + (C n).coeff d) *
          (P n).coeff (D₀ + d * n) := by
  have h2 := natDegree_mul_iterate_derivative_le (j := 2) (hA n) hn
  have h2c := coeff_mul_iterate_derivative_of_natDegree_le (j := 2) (hA n) hn
  have h1 := natDegree_mul_iterate_derivative_le (j := 1) (hB n) hn
  have h1c := coeff_mul_iterate_derivative_of_natDegree_le (j := 1) (hB n) hn
  have h0 := natDegree_mul_iterate_derivative_le (j := 0) (hC n) hn
  have h0c := coeff_mul_iterate_derivative_of_natDegree_le (j := 0) (hC n) hn
  have hd2 : derivative^[2] (P n) = (P n).derivative.derivative := rfl
  rw [hd2, descFactorial_two_cast] at h2c
  rw [hd2] at h2
  simp only [Function.iterate_one, Function.iterate_zero, id_eq, add_zero,
    Nat.descFactorial_one, Nat.descFactorial_zero, Nat.cast_one, mul_one] at h1 h1c h0 h0c
  rw [hrec n, show D₀ + d * (n + 1) = D₀ + d * n + d by ring]
  refine ⟨natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le h2 h1) h0, ?_⟩
  rw [coeff_add, coeff_add, h2c, h1c, h0c]
  ring

/-- Rows of `P (n + 1) = A n * (P n)'' + B n * (P n)' + C n * P n` have degree
`D₀ + d * n` when the top-coefficient multiplier never vanishes. -/
theorem derivRec₂_natDegree
    (hrec : ∀ n, P (n + 1) =
      A n * (P n).derivative.derivative + B n * (P n).derivative + C n * P n)
    (hA : ∀ n, (A n).natDegree ≤ d + 2) (hB : ∀ n, (B n).natDegree ≤ d + 1)
    (hC : ∀ n, (C n).natDegree ≤ d) (hP0 : P 0 ≠ 0) (h0 : (P 0).natDegree = D₀)
    (hlam : ∀ n : ℕ,
      (A n).coeff (d + 2) * ((D₀ + d * n : ℕ) : ℝ) * (((D₀ + d * n : ℕ) : ℝ) - 1) +
        (B n).coeff (d + 1) * ((D₀ + d * n : ℕ) : ℝ) + (C n).coeff d ≠ 0)
    (n : ℕ) : (P n).natDegree = D₀ + d * n :=
  natDegree_eq_of_top_coeff_step hP0 h0 (fun n hn => (derivRec₂_step hrec hA hB hC n hn).1)
    (fun n hn => (derivRec₂_step hrec hA hB hC n hn).2) hlam n

theorem derivRec₂_ne_zero
    (hrec : ∀ n, P (n + 1) =
      A n * (P n).derivative.derivative + B n * (P n).derivative + C n * P n)
    (hA : ∀ n, (A n).natDegree ≤ d + 2) (hB : ∀ n, (B n).natDegree ≤ d + 1)
    (hC : ∀ n, (C n).natDegree ≤ d) (hP0 : P 0 ≠ 0) (h0 : (P 0).natDegree = D₀)
    (hlam : ∀ n : ℕ,
      (A n).coeff (d + 2) * ((D₀ + d * n : ℕ) : ℝ) * (((D₀ + d * n : ℕ) : ℝ) - 1) +
        (B n).coeff (d + 1) * ((D₀ + d * n : ℕ) : ℝ) + (C n).coeff d ≠ 0)
    (n : ℕ) : P n ≠ 0 :=
  ne_zero_of_top_coeff_step hP0 h0 (fun n hn => (derivRec₂_step hrec hA hB hC n hn).1)
    (fun n hn => (derivRec₂_step hrec hA hB hC n hn).2) hlam n

theorem derivRec₂_leadingCoeff_pos
    (hrec : ∀ n, P (n + 1) =
      A n * (P n).derivative.derivative + B n * (P n).derivative + C n * P n)
    (hA : ∀ n, (A n).natDegree ≤ d + 2) (hB : ∀ n, (B n).natDegree ≤ d + 1)
    (hC : ∀ n, (C n).natDegree ≤ d) (hP0 : P 0 ≠ 0) (h0 : (P 0).natDegree = D₀)
    (hl0 : 0 < (P 0).coeff D₀)
    (hlam : ∀ n : ℕ,
      0 < (A n).coeff (d + 2) * ((D₀ + d * n : ℕ) : ℝ) * (((D₀ + d * n : ℕ) : ℝ) - 1) +
        (B n).coeff (d + 1) * ((D₀ + d * n : ℕ) : ℝ) + (C n).coeff d)
    (n : ℕ) : 0 < (P n).leadingCoeff :=
  leadingCoeff_pos_of_top_coeff_step hP0 h0 hl0
    (fun n hn => (derivRec₂_step hrec hA hB hC n hn).1)
    (fun n hn => (derivRec₂_step hrec hA hB hC n hn).2) hlam n

end SecondOrder

end RealRooted
