import RealRooted.BorceaBranden.Applications.RealUnivariateSymbol
import RealRooted.OperatorPreservesInterlacing

/-!
# Interlacing consequences of real finite symbols

This module transports the degree-bounded real-rootedness preservation theorem
for a stable finite symbol to polynomial pencils and oriented interlacing.
The statements concern arbitrary real linear maps; concrete operators belong in
separate application modules.
-/

open Polynomial

noncomputable section

namespace RealRooted.BorceaBranden

/-- A stable finite symbol sends every split polynomial in its degree box to a
split polynomial or to zero. -/
theorem linearMap_splits_of_finiteSymbol_stable
    {T : ℝ[X] →ₗ[ℝ] ℝ[X]} {d : ℕ} {p : ℝ[X]}
    (hSymbol : MvUpperHalfPlaneStable
      (complexifyMv (Challenges.BorceaBranden.finiteAlgebraicSymbol d T)))
    (hpdeg : p.natDegree ≤ d) (hp : p.Splits) :
    T p = 0 ∨ (T p).Splits :=
  finiteSymbol_preservesRealRootedUpTo hSymbol hpdeg hp

/-- A stable finite symbol transports the full real-rooted pencil generated by
two inputs in its degree box. -/
theorem linearMap_allComboRealRooted_of_finiteSymbol_stable
    {T : ℝ[X] →ₗ[ℝ] ℝ[X]} {d : ℕ} {p q : ℝ[X]}
    (hSymbol : MvUpperHalfPlaneStable
      (complexifyMv (Challenges.BorceaBranden.finiteAlgebraicSymbol d T)))
    (hpdeg : p.natDegree ≤ d) (hqdeg : q.natDegree ≤ d)
    (hall : AllComboRealRooted p q) :
    AllComboRealRooted (T p) (T q) := by
  apply allComboRealRooted_map_of_pencil hall
  intro a b hab
  apply linearMap_splits_of_finiteSymbol_stable hSymbol
  · exact (Polynomial.natDegree_add_le _ _).trans (max_le
      ((Polynomial.natDegree_C_mul_le a p).trans hpdeg)
      ((Polynomial.natDegree_C_mul_le b q).trans hqdeg))
  · exact hab.2

/-- A stable finite symbol preserves an interlacing pair up to the order and
zero ambiguities recorded by `Prec0`. -/
theorem linearMap_prec0_or_revPrec0_of_finiteSymbol_stable
    {T : ℝ[X] →ₗ[ℝ] ℝ[X]} {d : ℕ} {p q : ℝ[X]}
    (hSymbol : MvUpperHalfPlaneStable
      (complexifyMv (Challenges.BorceaBranden.finiteAlgebraicSymbol d T)))
    (hpdeg : p.natDegree ≤ d) (hqdeg : q.natDegree ≤ d)
    (hpq : Prec p q) :
    Prec0 (T p) (T q) ∨ Prec0 (T q) (T p) := by
  apply prec0_or_revPrec0_of_allComboRealRooted
  exact linearMap_allComboRealRooted_of_finiteSymbol_stable
    hSymbol hpdeg hqdeg (allComboRealRooted_of_prec hpq)

private lemma hermiteBiehlerPolynomial_natDegree_le
    {p q : ℝ[X]} {d : ℕ} (hpdeg : p.natDegree ≤ d)
    (hqdeg : q.natDegree ≤ d) :
    (hermiteBiehlerPolynomial p q).natDegree ≤ d := by
  unfold hermiteBiehlerPolynomial
  apply (Polynomial.natDegree_add_le _ _).trans
  apply max_le
  · simpa [complexify] using hpdeg
  · apply Polynomial.natDegree_mul_le.trans
    simpa [complexify] using hqdeg

lemma complexificationLinearMap_hermiteBiehler
    (T : ℝ[X] →ₗ[ℝ] ℝ[X]) (p q : ℝ[X]) :
    complexificationLinearMap T (hermiteBiehlerPolynomial p q) =
      hermiteBiehlerPolynomial (T p) (T q) := by
  unfold hermiteBiehlerPolynomial
  rw [LinearMap.map_add]
  rw [show C Complex.I * complexify q =
      Complex.I • complexify q by rw [smul_eq_C_mul]]
  rw [LinearMap.map_smul, complexificationLinearMap_complexify,
    complexificationLinearMap_complexify, smul_eq_C_mul]

private lemma complexificationLinearMapDegreeBox_hermiteBiehler_value
    (T : ℝ[X] →ₗ[ℝ] ℝ[X]) (d : ℕ) (p q : ℝ[X])
    (hpdeg : p.natDegree ≤ d) (hqdeg : q.natDegree ≤ d) :
    let f : MvPolynomial.degreeOfLE (Fin 1) ℂ (fun _ => d) :=
      ⟨(MvPolynomial.uniqueAlgEquiv ℂ (Fin 1)).symm
          (hermiteBiehlerPolynomial p q), by
        rw [MvPolynomial.mem_degreeOfLE_iff_degreeOf]
        intro i
        rw [Subsingleton.elim i default,
          MvPolynomial.degreeOf_uniqueAlgEquiv_symm]
        simpa using hermiteBiehlerPolynomial_natDegree_le hpdeg hqdeg⟩
    MvPolynomial.uniqueAlgEquiv ℂ (Fin 1)
        (complexUnivariateDegreeBoxOperator d (complexificationLinearMap T) f) =
      hermiteBiehlerPolynomial (T p) (T q) := by
  simp only [complexUnivariateDegreeBoxOperator, LinearMap.coe_mk,
    AddHom.coe_mk, AlgEquiv.apply_symm_apply]
  exact complexificationLinearMap_hermiteBiehler T p q

/-- A stable finite symbol preserves an oriented interlacing pair when the
nonzero outputs retain positive leading coefficients. -/
theorem linearMap_prec_of_finiteSymbol_stable
    {T : ℝ[X] →ₗ[ℝ] ℝ[X]} {d : ℕ} {p q : ℝ[X]}
    (hSymbol : MvUpperHalfPlaneStable
      (complexifyMv (Challenges.BorceaBranden.finiteAlgebraicSymbol d T)))
    (hpdeg : p.natDegree ≤ d) (hqdeg : q.natDegree ≤ d)
    (hpq : Prec q p)
    (hp : HasPosLeadingCoeff p) (hq : HasPosLeadingCoeff q)
    (hpout : HasPosLeadingCoeff (T p))
    (hqout : HasPosLeadingCoeff (T q))
    (hpoutdeg : 1 ≤ (T p).natDegree) :
    Prec (T q) (T p) := by
  let f : MvPolynomial.degreeOfLE (Fin 1) ℂ (fun _ => d) :=
    ⟨(MvPolynomial.uniqueAlgEquiv ℂ (Fin 1)).symm
        (hermiteBiehlerPolynomial p q), by
      rw [MvPolynomial.mem_degreeOfLE_iff_degreeOf]
      intro i
      rw [Subsingleton.elim i default,
        MvPolynomial.degreeOf_uniqueAlgEquiv_symm]
      simpa using hermiteBiehlerPolynomial_natDegree_le hpdeg hqdeg⟩
  have hfstable : MvUpperHalfPlaneStable f.1 := by
    apply (isUpperHalfPlaneStable_iff_mvUpperHalfPlaneStable _).mp
    exact hermiteBiehlerForwardPos hp hq hpq
  have hout := complexificationLinearMapDegreeBox_preserves_stability
    T d hSymbol f hfstable
  have hvalue := complexificationLinearMapDegreeBox_hermiteBiehler_value
    T d p q hpdeg hqdeg
  rcases hout with hzero | hstable
  · exfalso
    have hz := congrArg (MvPolynomial.uniqueAlgEquiv ℂ (Fin 1)) hzero
    rw [hvalue] at hz
    simp only [map_zero] at hz
    apply hpout.ne_zero
    apply Polynomial.ext
    intro k
    have hz' := congrArg (fun r : ℂ[X] => r.coeff k) hz
    have hre := congrArg Complex.re hz'
    simpa [hermiteBiehlerPolynomial, complexify] using hre
  · apply prec_of_stable_general hpout hqout
    · have hu : IsUpperHalfPlaneStable
          (MvPolynomial.uniqueAlgEquiv ℂ (Fin 1)
            (complexUnivariateDegreeBoxOperator d (complexificationLinearMap T) f)) := by
        apply (isUpperHalfPlaneStable_iff_mvUpperHalfPlaneStable _).mpr
        rw [AlgEquiv.symm_apply_apply]
        simp_all
      grind
    · grind

end RealRooted.BorceaBranden
